import type { Brand } from "@/types";

export const BRANDS: Brand[] = [
  {
    id: "zeneco",
    name: "Zen Eco Homes",
    type: "real_estate",
    description: "Eco-friendly sustainable housing in Spain",
    color: "#10b981",
    website: "https://zenecohomes.com",
    tone: "eco-conscious, modern, innovative",
    target_audience: "Environmentally conscious international buyers",
    specialties: ["sustainable homes", "solar energy", "green building"],
  },
  {
    id: "soleada",
    name: "Soleada.no",
    type: "real_estate",
    description: "Premium Spanish real estate for Scandinavian buyers",
    color: "#06b6d4",
    website: "https://soleada.no",
    tone: "professional, warm, luxurious",
    target_audience: "Norwegian property buyers in Spain",
    specialties: ["Costa Blanca", "Costa Cálida", "luxury villas"],
  },
  {
    id: "keyholding",
    name: "Keyholding Costa Blanca",
    type: "other",
    description: "Premium keyholding, documented property inspections and local home services for Norwegian owners on Costa Blanca North",
    color: "#C66B45",
    website: "https://keyholding.no",
    tone: "premium, reassuring, precise, personal",
    target_audience: "Norwegian owners of holiday homes, apartments and villas from Albir to Calpe",
    specialties: ["keyholding", "42-point property inspections", "arrival preparation", "contractor coordination", "emergency response", "property care"],
  },
  {
    id: "mondeo",
    name: "Mondeo Eiendom AS",
    type: "other",
    description: "Intern oppfølging av boligdrift, utleie, betalinger, renter, KPI og sikkerheter",
    color: "#f97316",
    website: "",
    tone: "presis, kontrollert, finansiell, juridisk ryddig",
    target_audience: "Egen admin- og økonomioversikt for Raveien 152E",
    specialties: ["boligdrift", "utleie", "renteinntekter", "KPI", "betalingsplan", "sikkerhet"],
  },
  {
    id: "chatgenius",
    name: "ChatGenius.pro",
    type: "saas",
    description: "AI-powered chat platform for businesses",
    color: "#8b5cf6",
    website: "https://chatgenius.pro",
    tone: "technical, innovative, solution-oriented",
    target_audience: "SMB owners and marketing teams",
    specialties: ["AI chatbots", "customer service automation", "lead generation"],
  },
  {
    id: "donaanna",
    name: "Dona Anna",
    type: "agriculture",
    description: "Premium olive oil and sustainable agriculture",
    color: "#f59e0b",
    website: "https://donaanna.com",
    tone: "authentic, artisanal, Mediterranean",
    target_audience: "Gourmet food enthusiasts and health-conscious consumers",
    specialties: ["extra virgin olive oil", "Mediterranean health", "organic farming", "farm-to-table"],
  },
  {
    id: "freddypublishing",
    name: "Freddy Publishing",
    type: "publishing",
    description: "Books, Kindle publishing, lead magnets and authority content across Amazon and owned channels",
    color: "#ef4444",
    website: "https://www.amazon.com/s?k=Freddy+Bremseth",
    tone: "authoritative, practical, conversion-focused",
    target_audience: "Readers, buyers and niche audiences reached through Kindle, email and search",
    specialties: ["Kindle SEO", "book funnels", "authority books", "Amazon metadata"],
  },
  {
    id: "freddyb",
    name: "Freddy Bremseth",
    type: "personal",
    description: "Personal brand - entrepreneur and real estate expert in Spain",
    color: "#3b82f6",
    website: "https://freddybremseth.com",
    tone: "authentic, inspiring, knowledgeable",
    target_audience: "Aspiring entrepreneurs and expats in Spain",
    specialties: ["entrepreneurship", "Spanish real estate", "digital nomad life"],
  },
  {
    id: "pinosoecolife",
    name: "Pinoso Ecolife",
    type: "real_estate",
    description: "Sustainable rural living in Pinosos, Alicante - eco-friendly country homes",
    color: "#84cc16",
    website: "https://pinosoecolife.com",
    tone: "natural, sustainable, community-oriented",
    target_audience: "Eco-conscious families seeking rural Spanish lifestyle",
    specialties: ["country homes", "sustainable living", "Pinosos area", "rural properties"],
  },
  {
    id: "neuralbeat",
    name: "Re-Master Freddy",
    type: "music",
    description: "AI-driven EDM and electronic music production",
    color: "#ec4899",
    website: "https://youtube.com/@remasterfreddy",
    tone: "energetic, futuristic, creative",
    target_audience: "EDM fans and electronic music listeners",
    specialties: ["AI music", "EDM production", "music videos", "remasters"],
  },
];

export const LEAD_STATUSES = ["NEW", "CONTACT", "QUALIFIED", "VIEWING", "NEGOTIATION", "WON", "ON_HOLD", "LOST"] as const;
export const PLATFORMS = ["instagram", "facebook", "linkedin", "twitter", "tiktok", "youtube"] as const;

export const SIDEBAR_NAV = {
  overview: [
    { label: "Executive Briefing", href: "/executive-briefing", icon: "ClipboardCheck" },
    { label: "Beslutningsjournal", href: "/operating-review", icon: "BookOpen" },
    { label: "Ukentlig ledelsesreview", href: "/weekly-management-review", icon: "BarChart3" },
    { label: "Kontinuerlig forbedring", href: "/continuous-improvement", icon: "Wrench" },
    { label: "Revenue Command", href: "/revenue-command", icon: "Gauge" },
    { label: "Varsler & eskalering", href: "/internal-alerts", icon: "BellRing" },
    { label: "Mål & Ukeplan", href: "/goals", icon: "Flag" },
    { label: "Lead Source ROI", href: "/attribution", icon: "Megaphone" },
    { label: "Månedsrapport", href: "/monthly-close", icon: "FileSpreadsheet" },
    { label: "Revenue Data Health", href: "/revenue-data-health", icon: "ShieldCheck" },
    { label: "I dag", href: "/today", icon: "Target" },
    { label: "Revenue Forecast", href: "/forecast", icon: "TrendingUp" },
    { label: "Commission & Cash", href: "/commissions", icon: "Banknote" },
    { label: "Approval Center", href: "/approvals", icon: "CheckSquare" },
    { label: "Kommunikasjon", href: "/communications", icon: "MessageSquareText" },
    { label: "Dashboard", href: "/", icon: "LayoutDashboard" },
    { label: "Business Overview", href: "/business-overview", icon: "PieChart" },
  ],
  saas: [
    { label: "SaaS & abonnement", href: "/saas", icon: "Rocket" },
    { label: "DemoSites CRM", href: "/demosites", icon: "Globe" },
    { label: "Revenue Engine", href: "/revenue-engine", icon: "Target" },
  ],
  operations: [
    { label: "CRM & kunder", href: "/customers", icon: "Users" },
    { label: "Team & arbeidsfordeling", href: "/team-workload", icon: "UsersRound" },
    { label: "Execution & Kalender", href: "/execution", icon: "CalendarCheck2" },
    { label: "Closing Workspace", href: "/closing", icon: "Target" },
    { label: "Deal Documents", href: "/closing-pack", icon: "FolderLock" },
    { label: "After-sales & Referral", href: "/after-sales", icon: "HeartHandshake" },
    { label: "Keyholding Revenue", href: "/service-revenue", icon: "KeyRound" },
    { label: "Lost Lead Recovery", href: "/recovery", icon: "RefreshCw" },
    { label: "AI Lead Inbox", href: "/lead-intelligence", icon: "Sparkles" },
    { label: "Oppgave-HUB", href: "/marketing-tasks", icon: "CheckSquare" },
    { label: "Booking Admin", href: "/booking-admin", icon: "Calendar" },
    { label: "Kalender", href: "/calendar", icon: "Calendar" },
  ],
  properties: [
    { label: "Eiendommer", href: "/inventory", icon: "Building2" },
    { label: "Scanner", href: "/scanner", icon: "ScanLine" },
    { label: "Tomtebase", href: "/tomtebase", icon: "Map" },
    { label: "Områder", href: "/areas", icon: "MapPin" },
    { label: "Vurdering", href: "/valuation", icon: "Calculator" },
    { label: "Dokumenter", href: "/document-hub", icon: "FileText" },
  ],
  content: [
    { label: "Content Studio", href: "/content-studio", icon: "Sparkles" },
    { label: "Publisert innhold (CMS)", href: "/website-cms", icon: "Globe" },
    { label: "Content Hub", href: "/content-hub", icon: "FileText" },
    { label: "Bilde Studio", href: "/image-studio", icon: "Image" },
    { label: "Ad Campaigns", href: "/ad-campaigns", icon: "Target" },
    { label: "YouTube Studio", href: "/youtube-studio", icon: "Youtube" },
    { label: "Re-Master Freddy", href: "/neural-beat", icon: "Music" },
  ],
  growth: [
    { label: "Publishing Hub", href: "/publishing", icon: "BookOpen" },
    { label: "Growth Hub", href: "/growth-hub", icon: "Rocket" },
    { label: "Market Intelligence", href: "/reports", icon: "TrendingUp" },
    { label: "Analytics", href: "/analytics", icon: "BarChart3" },
  ],
  automation: [
    { label: "Automatisering", href: "/automation", icon: "Zap" },
    { label: "Lead Nurture", href: "/automation/nurture", icon: "Sparkles" },
    { label: "Kommandosenter", href: "/agents", icon: "Bot" },
    { label: "E-post AI", href: "/email", icon: "Mail" },
  ],
  admin: [
    { label: "Roller & tilgang", href: "/access-control", icon: "UserCog" },
    { label: "Audit Log", href: "/audit-log", icon: "Activity" },
    { label: "Brands", href: "/brands", icon: "Palette" },
    { label: "Business Hub", href: "/business-hub", icon: "Briefcase" },
    { label: "Mondeo Eiendom", href: "/mondeo", icon: "Building2" },
    { label: "Data Health", href: "/data-health", icon: "Database" },
    { label: "Innstillinger", href: "/settings", icon: "Settings" },
  ],
} as const;
