import type { Brand } from "@/types";

export const BRANDS: Brand[] = [
  {
    id: "zeneco",
    name: "Zen Eco Homes",
    type: "real_estate",
    description: "Eco-friendly sustainable housing in Spain",
    color: "#10b981",
    website: "https://zenecohomes.com",
    tone: "eco-conscious, modern, innovative",
    target_audience: "Environmentally conscious international buyers",
    specialties: ["sustainable homes", "solar energy", "green building"],
  },
  {
    id: "soleada",
    name: "Soleada.no",
    type: "real_estate",
    description: "Premium Spanish real estate for Scandinavian buyers",
    color: "#06b6d4",
    website: "https://soleada.no",
    tone: "professional, warm, luxurious",
    target_audience: "Norwegian property buyers in Spain",
    specialties: ["Costa Blanca", "Costa Cálida", "luxury villas"],
  },
  {
    id: "chatgenius",
    name: "ChatGenius.pro",
    type: "saas",
    description: "AI-powered chat platform for businesses",
    color: "#8b5cf6",
    website: "https://chatgenius.pro",
    tone: "technical, innovative, solution-oriented",
    target_audience: "SMB owners and marketing teams",
    specialties: ["AI chatbots", "customer service automation", "lead generation"],
  },
  {
    id: "donaanna",
    name: "Dona Anna",
    type: "agriculture",
    description: "Premium olive oil and sustainable agriculture",
    color: "#f59e0b",
    website: "https://donaanna.com",
    tone: "authentic, artisanal, Mediterranean",
    target_audience: "Gourmet food enthusiasts and health-conscious consumers",
    specialties: ["extra virgin olive oil", "organic farming", "farm-to-table"],
  },
  {
    id: "freddyb",
    name: "Freddy Bremseth",
    type: "personal",
    description: "Personal brand - entrepreneur and real estate expert in Spain",
    color: "#3b82f6",
    website: "https://freddybremseth.com",
    tone: "authentic, inspiring, knowledgeable",
    target_audience: "Aspiring entrepreneurs and expats in Spain",
    specialties: ["entrepreneurship", "Spanish real estate", "digital nomad life"],
  },
  {
    id: "pinosoecolife",
    name: "Pinoso Ecolife",
    type: "real_estate",
    description: "Sustainable rural living in Pinosos, Alicante - eco-friendly country homes",
    color: "#84cc16",
    website: "https://pinosoecolife.com",
    tone: "natural, sustainable, community-oriented",
    target_audience: "Eco-conscious families seeking rural Spanish lifestyle",
    specialties: ["country homes", "sustainable living", "Pinosos area", "rural properties"],
  },
  {
    id: "neuralbeat",
    name: "Re-Master Freddy",
    type: "music",
    description: "AI-driven EDM and electronic music production",
    color: "#ec4899",
    website: "https://youtube.com/@remasterfreddy",
    tone: "energetic, futuristic, creative",
    target_audience: "EDM fans and electronic music listeners",
    specialties: ["AI music", "EDM production", "music videos", "remasters"],
  },
];

export const LEAD_STATUSES = [
  "NEW",
  "CONTACT",
  "QUALIFIED",
  "VIEWING",
  "NEGOTIATION",
  "WON",
  "ON_HOLD",
  "LOST",
] as const;

export const PLATFORMS = [
  "instagram",
  "facebook",
  "linkedin",
  "twitter",
  "tiktok",
  "youtube",
] as const;

export const SIDEBAR_NAV = {
  overview: [
    { label: "Dashboard", href: "/", icon: "LayoutDashboard" },
  ],
  realty: [
    { label: "CRM", href: "/pipeline", icon: "Users" },
    { label: "Eiendommer", href: "/inventory", icon: "Building2" },
    { label: "Vurdering", href: "/valuation", icon: "Calculator" },
    { label: "Tomtebase", href: "/tomtebase", icon: "Map" },
  ],
  content: [
    { label: "Content Studio", href: "/content-studio", icon: "Sparkles" },
    { label: "Bilde Studio", href: "/image-studio", icon: "Image" },
    { label: "Content Hub", href: "/content-hub", icon: "FileText" },
    { label: "Re-Master Freddy", href: "/neural-beat", icon: "Music" },
  ],
  business: [
    { label: "Vekstmotor", href: "/growth-hub", icon: "Rocket" },
    { label: "Brands", href: "/brands", icon: "Palette" },
    { label: "ChatGenius SaaS", href: "/saas", icon: "Globe" },
    { label: "Business Oversikt", href: "/business-overview", icon: "PieChart" },
  ],
  tools: [
    { label: "Kommandosenter", href: "/agents", icon: "Bot" },
    { label: "E-post AI", href: "/email", icon: "Mail" },
    { label: "Market Intelligence", href: "/reports", icon: "TrendingUp" },
    { label: "Analytics", href: "/analytics", icon: "BarChart3" },
    { label: "Scanner", href: "/scanner", icon: "ScanLine" },
    { label: "Innstillinger", href: "/settings", icon: "Settings" },
  ],
} as const;
