"use client";

import { useCallback, useEffect, useState } from "react";
import { ArrowRight, BarChart3, Loader2, RefreshCw } from "lucide-react";

type ForwardRow = { from:string; to:string; transitions:number; measuredExits:number; forwardShare:number|null };
type Payload = { generatedAt:string; windowDays:number; tracking:{ active:boolean; firstTrackedAt:string|null; latestTrackedAt:string|null; transitionEvents:number; uniqueContacts:number; historicalComplete:boolean; note:string }; snapshot:Record<string,number>; forward:ForwardRow[]; transitionCounts:Record<string,number> };

export default function PipelineConversionPage(){
  const [data,setData]=useState<Payload|null>(null); const [days,setDays]=useState(30); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch(`/api/nexus/pipeline-conversion?days=${days}`,{cache:"no-store",credentials:"same-origin"});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error||"Kunne ikke hente conversion-data");setData(b as Payload);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setLoading(false);}},[days]);
  useEffect(()=>{void load();},[load]);
  return <main className="mx-auto max-w-[1450px] space-y-6 p-4 sm:p-6">
    <header className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[0.2em] text-cyan-700"><BarChart3 size={16}/> Pipeline Conversion</div><h1 className="mt-2 text-3xl font-black text-slate-950">Snapshot og faktisk stegflyt</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Snapshot viser hvor kundene står nå. Conversion viser bare eksplisitt målte pipeline-overganger etter at tracking ble aktivert.</p></div><div className="flex flex-wrap gap-2">{[7,30,90].map(v=><button key={v} onClick={()=>setDays(v)} className={`rounded-xl px-3 py-2 text-sm font-black ${days===v?"bg-cyan-700 text-white":"bg-slate-100 text-slate-700"}`}>{v} dager</button>)}<button onClick={()=>void load()} className="rounded-xl bg-slate-950 px-3 py-2 text-sm font-black text-white">{loading?<Loader2 size={15} className="mr-2 inline animate-spin"/>:<RefreshCw size={15} className="mr-2 inline"/>}Oppdater</button></div></div></header>
    {error&&<div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-900">{error}</div>}
    <section className="grid gap-3 sm:grid-cols-3"><Metric label="Målte overganger" value={data?.tracking.transitionEvents??0}/><Metric label="Kunder med målt bevegelse" value={data?.tracking.uniqueContacts??0}/><Metric label="Måling aktiv" value={data?.tracking.active?"Ja":"Ikke ennå"}/></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-black text-slate-950">Pipeline snapshot nå</h2><p className="mt-1 text-sm text-slate-500">Dette er beholdningen, ikke historisk conversion.</p><div className="mt-4 flex flex-wrap gap-2">{Object.entries(data?.snapshot||{}).sort((a,b)=>b[1]-a[1]).map(([stage,count])=><span key={stage} className="rounded-full bg-slate-100 px-3 py-2 text-xs font-black text-slate-700">{stage} · {count}</span>)}</div></section>
    <section className="space-y-3"><div><h2 className="text-xl font-black text-slate-950">Målt fremdrift mellom steg</h2><p className="mt-1 text-sm text-slate-500">Andelen er av målte exits fra samme steg i valgt periode, ikke av alle historiske leads.</p></div>{(data?.forward||[]).map(row=><article key={`${row.from}-${row.to}`} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 font-black text-slate-950"><span>{row.from}</span><ArrowRight size={16}/><span>{row.to}</span></div><div className="mt-1 text-xs text-slate-500">{row.transitions} direkte overganger · {row.measuredExits} målte exits fra {row.from}</div></div><div className="text-2xl font-black text-cyan-800">{row.forwardShare==null?"–":`${row.forwardShare}%`}</div></div></article>)}</section>
    {data?.tracking.note&&<div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><b>Datagrunnlag:</b> {data.tracking.note}</div>}
  </main>;
}
function Metric({label,value}:{label:string;value:number|string}){return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="text-2xl font-black text-slate-950">{value}</div><div className="text-xs font-semibold text-slate-500">{label}</div></div>}
