import Anthropic from '@anthropic-ai/sdk';

interface BuildConfig {
  title: string;
  slug: string;
  description: string;
  features: string[];
  pricing: string;
  color: string;
  target_audience: string;
  category: string;
}

interface DeployResult {
  success: boolean;
  repo_url?: string;
  vercel_url?: string;
  error?: string;
}

export class SaaSAutoDeployer {
  private githubToken: string;
  private vercelToken: string;
  private anthropicApiKey: string;
  private anthropic: Anthropic;
  private githubUsername: string | null = null;

  constructor() {
    this.githubToken = process.env.GITHUB_TOKEN || '';
    this.vercelToken = process.env.VERCEL_TOKEN || '';
    this.anthropicApiKey = process.env.ANTHROPIC_API_KEY || '';

    if (!this.githubToken || !this.vercelToken || !this.anthropicApiKey) {
      throw new Error(
        'Missing required environment variables: GITHUB_TOKEN, VERCEL_TOKEN, ANTHROPIC_API_KEY'
      );
    }

    this.anthropic = new Anthropic({ apiKey: this.anthropicApiKey });
  }

  // ─── Main Entry Point ───────────────────────────────────────────────

  async buildAndDeploy(config: BuildConfig): Promise<DeployResult> {
    console.log(`[AutoDeployer] Starting build and deploy for "${config.title}" (${config.slug})`);

    try {
      // Step 1: Generate the full app codebase
      console.log('[AutoDeployer] Step 1/4 - Generating app code via Claude...');
      const files = await this.generateAppCode(config);
      console.log(`[AutoDeployer] Generated ${files.size} files`);

      // Step 2: Create GitHub repo
      console.log('[AutoDeployer] Step 2/4 - Creating GitHub repository...');
      const repoFullName = await this.createGitHubRepo(config.slug);
      console.log(`[AutoDeployer] Created repo: ${repoFullName}`);

      // Step 3: Push all files to GitHub
      console.log('[AutoDeployer] Step 3/4 - Pushing files to GitHub...');
      await this.pushToGitHub(repoFullName, files);
      console.log('[AutoDeployer] Files pushed successfully');

      // Step 4: Deploy to Vercel
      console.log('[AutoDeployer] Step 4/4 - Deploying to Vercel...');
      const vercelUrl = await this.deployToVercel(repoFullName);
      console.log(`[AutoDeployer] Deployed to: ${vercelUrl}`);

      const repoUrl = `https://github.com/${repoFullName}`;

      console.log('[AutoDeployer] Build and deploy complete!');
      console.log(`[AutoDeployer]   Repo: ${repoUrl}`);
      console.log(`[AutoDeployer]   Live: ${vercelUrl}`);

      return {
        success: true,
        repo_url: repoUrl,
        vercel_url: vercelUrl,
      };
    } catch (error: any) {
      console.error('[AutoDeployer] Build and deploy failed:', error.message);
      return {
        success: false,
        error: error.message || 'Unknown error during build and deploy',
      };
    }
  }

  // ─── GitHub Helpers ─────────────────────────────────────────────────

  private async getGitHubUsername(): Promise<string> {
    if (this.githubUsername) return this.githubUsername;

    const res = await fetch('https://api.github.com/user', {
      headers: {
        Authorization: `Bearer ${this.githubToken}`,
        Accept: 'application/vnd.github.v3+json',
      },
    });

    if (!res.ok) {
      const body = await res.text();
      throw new Error(`Failed to get GitHub user: ${res.status} ${body}`);
    }

    const data = await res.json();
    this.githubUsername = data.login;
    console.log(`[AutoDeployer] GitHub user: ${data.login}`);
    return data.login;
  }

  private async createGitHubRepo(slug: string): Promise<string> {
    const username = await this.getGitHubUsername();

    const res = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${this.githubToken}`,
        Accept: 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: slug,
        description: `SaaS app generated by RealtyFlow Pro AutoDeployer`,
        private: false,
        auto_init: true, // Creates an initial commit with README so we have a ref
      }),
    });

    if (!res.ok) {
      const body = await res.text();
      throw new Error(`Failed to create GitHub repo: ${res.status} ${body}`);
    }

    const data = await res.json();
    console.log(`[AutoDeployer] Repo created: ${data.full_name}`);
    return data.full_name; // e.g. "username/slug"
  }

  private async pushToGitHub(
    repoFullName: string,
    files: Map<string, string>
  ): Promise<void> {
    const headers = {
      Authorization: `Bearer ${this.githubToken}`,
      Accept: 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
    };

    const baseUrl = `https://api.github.com/repos/${repoFullName}`;

    // 1. Get the current commit SHA for main branch
    console.log('[AutoDeployer] Getting current HEAD ref...');
    const refRes = await fetch(`${baseUrl}/git/ref/heads/main`, { headers });
    if (!refRes.ok) {
      // Wait a moment for auto_init to finish, then retry
      console.log('[AutoDeployer] Ref not ready, waiting 3 seconds...');
      await new Promise((r) => setTimeout(r, 3000));
      const retryRes = await fetch(`${baseUrl}/git/ref/heads/main`, { headers });
      if (!retryRes.ok) {
        const body = await retryRes.text();
        throw new Error(`Failed to get ref heads/main: ${retryRes.status} ${body}`);
      }
      var refData = await retryRes.json();
    } else {
      var refData = await refRes.json();
    }

    const latestCommitSha = refData.object.sha;
    console.log(`[AutoDeployer] Current HEAD: ${latestCommitSha}`);

    // 2. Get the tree SHA of the latest commit
    const commitRes = await fetch(`${baseUrl}/git/commits/${latestCommitSha}`, { headers });
    if (!commitRes.ok) {
      const body = await commitRes.text();
      throw new Error(`Failed to get commit: ${commitRes.status} ${body}`);
    }
    const commitData = await commitRes.json();
    const baseTreeSha = commitData.tree.sha;

    // 3. Create blobs for all files
    console.log(`[AutoDeployer] Creating ${files.size} blobs...`);
    const treeItems: Array<{
      path: string;
      mode: string;
      type: string;
      sha: string;
    }> = [];

    // Process blobs in batches of 5 to avoid rate limiting
    const fileEntries = Array.from(files.entries());
    for (let i = 0; i < fileEntries.length; i += 5) {
      const batch = fileEntries.slice(i, i + 5);
      const blobPromises = batch.map(async ([filePath, content]) => {
        const blobRes = await fetch(`${baseUrl}/git/blobs`, {
          method: 'POST',
          headers,
          body: JSON.stringify({
            content,
            encoding: 'utf-8',
          }),
        });

        if (!blobRes.ok) {
          const body = await blobRes.text();
          throw new Error(`Failed to create blob for ${filePath}: ${blobRes.status} ${body}`);
        }

        const blobData = await blobRes.json();
        return {
          path: filePath,
          mode: '100644' as const,
          type: 'blob' as const,
          sha: blobData.sha as string,
        };
      });

      const results = await Promise.all(blobPromises);
      treeItems.push(...results);
    }

    console.log(`[AutoDeployer] Created ${treeItems.length} blobs`);

    // 4. Create a new tree
    console.log('[AutoDeployer] Creating tree...');
    const treeRes = await fetch(`${baseUrl}/git/trees`, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        base_tree: baseTreeSha,
        tree: treeItems,
      }),
    });

    if (!treeRes.ok) {
      const body = await treeRes.text();
      throw new Error(`Failed to create tree: ${treeRes.status} ${body}`);
    }

    const treeData = await treeRes.json();
    console.log(`[AutoDeployer] Tree created: ${treeData.sha}`);

    // 5. Create a new commit
    console.log('[AutoDeployer] Creating commit...');
    const newCommitRes = await fetch(`${baseUrl}/git/commits`, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        message: 'Initial SaaS app scaffolding - generated by AutoDeployer',
        tree: treeData.sha,
        parents: [latestCommitSha],
      }),
    });

    if (!newCommitRes.ok) {
      const body = await newCommitRes.text();
      throw new Error(`Failed to create commit: ${newCommitRes.status} ${body}`);
    }

    const newCommitData = await newCommitRes.json();
    console.log(`[AutoDeployer] Commit created: ${newCommitData.sha}`);

    // 6. Update the ref to point to the new commit
    console.log('[AutoDeployer] Updating ref...');
    const updateRefRes = await fetch(`${baseUrl}/git/refs/heads/main`, {
      method: 'PATCH',
      headers,
      body: JSON.stringify({
        sha: newCommitData.sha,
        force: true,
      }),
    });

    if (!updateRefRes.ok) {
      const body = await updateRefRes.text();
      throw new Error(`Failed to update ref: ${updateRefRes.status} ${body}`);
    }

    console.log('[AutoDeployer] Ref updated to new commit');
  }

  // ─── Vercel Deploy ──────────────────────────────────────────────────

  private async deployToVercel(repoFullName: string): Promise<string> {
    const [owner, repo] = repoFullName.split('/');

    // 1. Create a Vercel project linked to the GitHub repo
    console.log('[AutoDeployer] Creating Vercel project...');
    const createRes = await fetch('https://api.vercel.com/v9/projects', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${this.vercelToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: repo,
        framework: 'nextjs',
        gitRepository: {
          type: 'github',
          repo: repoFullName,
        },
        buildCommand: 'next build',
        outputDirectory: '.next',
        installCommand: 'npm install',
      }),
    });

    if (!createRes.ok) {
      const body = await createRes.text();
      throw new Error(`Failed to create Vercel project: ${createRes.status} ${body}`);
    }

    const projectData = await createRes.json();
    console.log(`[AutoDeployer] Vercel project created: ${projectData.name}`);

    // 2. Trigger a deployment by creating a deployment from the repo
    console.log('[AutoDeployer] Triggering deployment...');
    const deployRes = await fetch('https://api.vercel.com/v13/deployments', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${this.vercelToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: repo,
        project: projectData.id,
        gitSource: {
          type: 'github',
          org: owner,
          repo: repo,
          ref: 'main',
        },
      }),
    });

    if (!deployRes.ok) {
      const body = await deployRes.text();
      // If deploy API fails, the project is still linked and will auto-deploy on push
      console.warn(
        `[AutoDeployer] Manual deploy trigger failed (${deployRes.status}), but project is linked to GitHub. Deployment should happen automatically.`
      );
      return `https://${repo}.vercel.app`;
    }

    const deployData = await deployRes.json();
    const vercelUrl = deployData.url
      ? `https://${deployData.url}`
      : `https://${repo}.vercel.app`;

    console.log(`[AutoDeployer] Deployment triggered: ${vercelUrl}`);

    // 3. Wait for deployment to be ready (poll status)
    if (deployData.id) {
      console.log('[AutoDeployer] Waiting for deployment to complete...');
      const deployUrl = await this.waitForDeployment(deployData.id);
      if (deployUrl) return deployUrl;
    }

    return vercelUrl;
  }

  private async waitForDeployment(deploymentId: string): Promise<string | null> {
    const maxAttempts = 30;
    const pollInterval = 10_000; // 10 seconds

    for (let attempt = 1; attempt <= maxAttempts; attempt++) {
      await new Promise((r) => setTimeout(r, pollInterval));

      try {
        const res = await fetch(
          `https://api.vercel.com/v13/deployments/${deploymentId}`,
          {
            headers: {
              Authorization: `Bearer ${this.vercelToken}`,
            },
          }
        );

        if (!res.ok) continue;

        const data = await res.json();
        console.log(
          `[AutoDeployer] Deployment status (attempt ${attempt}/${maxAttempts}): ${data.readyState}`
        );

        if (data.readyState === 'READY') {
          const url = data.url ? `https://${data.url}` : null;
          console.log(`[AutoDeployer] Deployment ready: ${url}`);
          return url;
        }

        if (data.readyState === 'ERROR') {
          console.error('[AutoDeployer] Deployment failed');
          return null;
        }
      } catch (err: any) {
        console.warn(`[AutoDeployer] Poll error: ${err.message}`);
      }
    }

    console.warn('[AutoDeployer] Deployment poll timed out');
    return null;
  }

  // ─── Code Generation via Claude ─────────────────────────────────────

  private async generateAppCode(config: BuildConfig): Promise<Map<string, string>> {
    // Start with the base template
    const files = this.getBaseTemplate(config);

    // Use Claude to customize the landing page copy and features
    console.log('[AutoDeployer] Calling Claude to customize landing page...');
    const customizedPage = await this.customizeLandingPage(config);
    if (customizedPage) {
      files.set('src/app/page.tsx', customizedPage);
    }

    return files;
  }

  private async customizeLandingPage(config: BuildConfig): Promise<string | null> {
    try {
      const prompt = `You are a senior frontend developer. Generate a complete Next.js page.tsx file for a SaaS landing page.

The SaaS product details:
- Name: ${config.title}
- Description: ${config.description}
- Target Audience: ${config.target_audience}
- Category: ${config.category}
- Features: ${config.features.join(', ')}
- Pricing Info: ${config.pricing}
- Brand Color: ${config.color}

Requirements:
1. Use "use client" directive
2. Use Tailwind CSS only (no external UI libraries)
3. The page must include ALL of these sections:
   - Sticky navigation bar with logo text and "Get Started" CTA button
   - Hero section with compelling headline, subheadline, two CTA buttons, and a floating UI mockup/illustration using CSS
   - Social proof bar with metrics (e.g., "10,000+ users", "99.9% uptime", "4.9/5 rating")
   - Features grid (use the provided features) with SVG icons and descriptions
   - Pricing table with 3 tiers: Free, Pro ($29/mo), Business ($79/mo) - each with feature checkmark lists and CTA button
   - FAQ section with 5 expandable/collapsible items using React state
   - Final CTA section with headline and button
   - Footer with logo, link columns, and copyright
4. Use the brand color (${config.color}) as the primary accent color via Tailwind arbitrary values
5. Support dark mode using Tailwind dark: prefix
6. Use gradients, glass morphism effects (backdrop-blur, bg-opacity), smooth transitions
7. Make it fully responsive (mobile-first)
8. Use Inter font (already loaded in layout)
9. All content should be specific to this SaaS product - NOT generic placeholder text
10. Include smooth scroll behavior for anchor links
11. The design should look premium and modern - comparable to top SaaS landing pages

Return ONLY the complete TypeScript/React code for page.tsx. No markdown, no explanation, no code fences.`;

      const message = await this.anthropic.messages.create({
        model: 'claude-sonnet-5',
        max_tokens: 16000,
        messages: [
          {
            role: 'user',
            content: prompt,
          },
        ],
      });

      const textContent = message.content.find((block) => block.type === 'text');
      if (textContent && textContent.type === 'text') {
        let code = textContent.text.trim();
        // Strip markdown code fences if Claude included them despite instructions
        if (code.startsWith('```')) {
          code = code.replace(/^```(?:tsx?|javascript|jsx)?\n?/, '').replace(/\n?```$/, '');
        }
        console.log('[AutoDeployer] Landing page customized successfully');
        return code;
      }

      console.warn('[AutoDeployer] No text content in Claude response');
      return null;
    } catch (error: any) {
      console.error('[AutoDeployer] Claude API error:', error.message);
      console.log('[AutoDeployer] Falling back to base template landing page');
      return null;
    }
  }

  // ─── Base Template ──────────────────────────────────────────────────

  private getBaseTemplate(config: BuildConfig): Map<string, string> {
    const files = new Map<string, string>();

    // ── package.json ──────────────────────────────────────────────────
    files.set(
      'package.json',
      JSON.stringify(
        {
          name: config.slug,
          version: '0.1.0',
          private: true,
          scripts: {
            dev: 'next dev',
            build: 'next build',
            start: 'next start',
            lint: 'next lint',
          },
          dependencies: {
            next: '14.2.5',
            react: '^18.3.1',
            'react-dom': '^18.3.1',
            '@supabase/supabase-js': '^2.45.0',
            '@supabase/ssr': '^0.4.0',
            stripe: '^16.2.0',
            '@stripe/stripe-js': '^4.1.0',
          },
          devDependencies: {
            typescript: '^5.5.4',
            '@types/node': '^20.14.12',
            '@types/react': '^18.3.3',
            '@types/react-dom': '^18.3.0',
            tailwindcss: '^3.4.7',
            postcss: '^8.4.40',
            autoprefixer: '^10.4.19',
            eslint: '^8.57.0',
            'eslint-config-next': '14.2.5',
          },
        },
        null,
        2
      )
    );

    // ── next.config.js ────────────────────────────────────────────────
    files.set(
      'next.config.js',
      `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    domains: [],
  },
};

module.exports = nextConfig;
`
    );

    // ── tailwind.config.ts ────────────────────────────────────────────
    files.set(
      'tailwind.config.ts',
      `import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        brand: {
          50: '${adjustColor(config.color, 0.95)}',
          100: '${adjustColor(config.color, 0.9)}',
          200: '${adjustColor(config.color, 0.8)}',
          300: '${adjustColor(config.color, 0.6)}',
          400: '${adjustColor(config.color, 0.4)}',
          500: '${config.color}',
          600: '${adjustColor(config.color, -0.1)}',
          700: '${adjustColor(config.color, -0.2)}',
          800: '${adjustColor(config.color, -0.3)}',
          900: '${adjustColor(config.color, -0.4)}',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
};

export default config;
`
    );

    // ── tsconfig.json ─────────────────────────────────────────────────
    files.set(
      'tsconfig.json',
      JSON.stringify(
        {
          compilerOptions: {
            target: 'es5',
            lib: ['dom', 'dom.iterable', 'esnext'],
            allowJs: true,
            skipLibCheck: true,
            strict: true,
            noEmit: true,
            esModuleInterop: true,
            module: 'esnext',
            moduleResolution: 'bundler',
            resolveJsonModule: true,
            isolatedModules: true,
            jsx: 'preserve',
            incremental: true,
            plugins: [{ name: 'next' }],
            paths: {
              '@/*': ['./src/*'],
            },
          },
          include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
          exclude: ['node_modules'],
        },
        null,
        2
      )
    );

    // ── postcss.config.js ─────────────────────────────────────────────
    files.set(
      'postcss.config.js',
      `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`
    );

    // ── .env.example ──────────────────────────────────────────────────
    files.set(
      '.env.example',
      `# Supabase
NEXT_PUBLIC_SUPABASE_URL=your_supabase_url
NEXT_PUBLIC_SUPABASE_ANON_KEY=your_supabase_anon_key

# Stripe
STRIPE_SECRET_KEY=sk_test_...
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_...
STRIPE_WEBHOOK_SECRET=whsec_...

# App
NEXT_PUBLIC_APP_URL=https://your-app.example.com
`
    );

    // ── src/app/globals.css ───────────────────────────────────────────
    files.set(
      'src/app/globals.css',
      `@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --brand-color: ${config.color};
  }

  html {
    scroll-behavior: smooth;
  }

  body {
    @apply bg-white text-gray-900 dark:bg-gray-950 dark:text-gray-100;
  }
}

@layer components {
  .glass {
    @apply bg-white/70 dark:bg-gray-900/70 backdrop-blur-xl border border-white/20 dark:border-gray-700/30;
  }

  .glass-card {
    @apply bg-white/60 dark:bg-gray-800/60 backdrop-blur-lg border border-gray-200/50 dark:border-gray-700/50 rounded-2xl;
  }

  .gradient-text {
    @apply bg-clip-text text-transparent bg-gradient-to-r from-brand-500 to-brand-700;
  }

  .btn-primary {
    @apply inline-flex items-center justify-center px-6 py-3 text-sm font-semibold text-white bg-brand-500 rounded-xl hover:bg-brand-600 transition-all duration-200 shadow-lg shadow-brand-500/25 hover:shadow-brand-500/40 hover:-translate-y-0.5;
  }

  .btn-secondary {
    @apply inline-flex items-center justify-center px-6 py-3 text-sm font-semibold text-brand-600 dark:text-brand-400 bg-brand-50 dark:bg-brand-900/20 rounded-xl hover:bg-brand-100 dark:hover:bg-brand-900/30 transition-all duration-200;
  }
}

@layer utilities {
  .animate-float {
    animation: float 6s ease-in-out infinite;
  }

  @keyframes float {
    0%, 100% { transform: translateY(0px); }
    50% { transform: translateY(-20px); }
  }
}
`
    );

    // ── src/app/layout.tsx ────────────────────────────────────────────
    files.set(
      'src/app/layout.tsx',
      `import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '${config.title} - ${config.description}',
  description: '${config.description}',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
`
    );

    // ── src/app/page.tsx (Base Landing Page) ──────────────────────────
    files.set(
      'src/app/page.tsx',
      `'use client';

import { useState } from 'react';
import Link from 'next/link';

const features = [
${config.features.map((f, i) => `  { title: '${f.replace(/'/g, "\\'")}', description: 'Powerful ${f.toLowerCase().replace(/'/g, "\\'")} capabilities designed for ${config.target_audience.replace(/'/g, "\\'")}.' }`).join(',\n')}
];

const pricingPlans = [
  {
    name: 'Free',
    price: '$0',
    period: '/month',
    description: 'Perfect for getting started',
    features: ['Up to 3 projects', 'Basic analytics', 'Community support', '1 team member'],
    cta: 'Start Free',
    highlighted: false,
  },
  {
    name: 'Pro',
    price: '$29',
    period: '/month',
    description: 'For growing teams',
    features: ['Unlimited projects', 'Advanced analytics', 'Priority support', 'Up to 10 team members', 'Custom integrations', 'API access'],
    cta: 'Start Pro Trial',
    highlighted: true,
  },
  {
    name: 'Business',
    price: '$79',
    period: '/month',
    description: 'For scaling organizations',
    features: ['Everything in Pro', 'Unlimited team members', 'Dedicated account manager', 'SSO / SAML', 'Custom contracts', 'SLA guarantee', 'Advanced security'],
    cta: 'Contact Sales',
    highlighted: false,
  },
];

const faqs = [
  { q: 'How does the free trial work?', a: 'You get full access to all Pro features for 14 days. No credit card required. At the end of your trial, you can choose to upgrade or continue with our free plan.' },
  { q: 'Can I cancel my subscription anytime?', a: 'Absolutely. You can cancel your subscription at any time from your dashboard. There are no long-term contracts or cancellation fees.' },
  { q: 'Do you offer refunds?', a: 'Yes, we offer a 30-day money-back guarantee. If you are not satisfied with ${config.title}, we will refund your payment in full.' },
  { q: 'Is my data secure?', a: 'Security is our top priority. We use industry-standard encryption, regular security audits, and comply with SOC 2 and GDPR requirements.' },
  { q: 'What integrations do you support?', a: 'We integrate with all major tools including Slack, Zapier, Google Workspace, Microsoft 365, and many more. Our API also allows custom integrations.' },
];

const featureIcons = [
  <svg key="0" className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>,
  <svg key="1" className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" /></svg>,
  <svg key="2" className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" /></svg>,
  <svg key="3" className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4zm0 0h12a2 2 0 002-2v-4a2 2 0 00-2-2h-2.343M11 7.343l1.657-1.657a2 2 0 012.828 0l2.829 2.829a2 2 0 010 2.828l-8.486 8.485M7 17h.01" /></svg>,
  <svg key="4" className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 5a1 1 0 011-1h14a1 1 0 011 1v2a1 1 0 01-1 1H5a1 1 0 01-1-1V5zM4 13a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H5a1 1 0 01-1-1v-6zM16 13a1 1 0 011-1h2a1 1 0 011 1v6a1 1 0 01-1 1h-2a1 1 0 01-1-1v-6z" /></svg>,
  <svg key="5" className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z" /></svg>,
];

export default function LandingPage() {
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  return (
    <div className="min-h-screen bg-white dark:bg-gray-950">
      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 glass border-b border-gray-200/50 dark:border-gray-800/50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-brand-400 to-brand-600 flex items-center justify-center text-white font-bold text-sm">
                {('${config.title}')[0]}
              </div>
              <span className="text-xl font-bold text-gray-900 dark:text-white">${config.title}</span>
            </div>
            <div className="hidden md:flex items-center gap-8">
              <a href="#features" className="text-sm text-gray-600 dark:text-gray-300 hover:text-brand-500 transition-colors">Features</a>
              <a href="#pricing" className="text-sm text-gray-600 dark:text-gray-300 hover:text-brand-500 transition-colors">Pricing</a>
              <a href="#faq" className="text-sm text-gray-600 dark:text-gray-300 hover:text-brand-500 transition-colors">FAQ</a>
              <Link href="/login" className="text-sm text-gray-600 dark:text-gray-300 hover:text-brand-500 transition-colors">Log In</Link>
              <Link href="/login" className="btn-primary">Get Started</Link>
            </div>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="relative pt-32 pb-20 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-brand-50 via-white to-brand-50/50 dark:from-brand-950/20 dark:via-gray-950 dark:to-gray-950" />
        <div className="absolute top-20 left-1/4 w-72 h-72 bg-brand-400/20 rounded-full blur-3xl" />
        <div className="absolute bottom-10 right-1/4 w-96 h-96 bg-brand-300/10 rounded-full blur-3xl" />

        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div>
              <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-brand-50 dark:bg-brand-900/20 text-brand-600 dark:text-brand-400 text-sm font-medium mb-6">
                <span className="w-2 h-2 rounded-full bg-brand-500 animate-pulse" />
                Built for ${config.target_audience}
              </div>
              <h1 className="text-5xl sm:text-6xl font-extrabold text-gray-900 dark:text-white leading-tight mb-6">
                ${config.title.split(' ').length > 1 ? config.title.split(' ').slice(0, -1).join(' ') + ' ' : ''}<span className="gradient-text">${config.title.split(' ').slice(-1)[0]}</span>
              </h1>
              <p className="text-xl text-gray-600 dark:text-gray-300 mb-8 leading-relaxed">
                ${config.description}
              </p>
              <div className="flex flex-col sm:flex-row gap-4">
                <Link href="/login" className="btn-primary text-base px-8 py-4">
                  Get Started Free
                  <svg className="w-5 h-5 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" /></svg>
                </Link>
                <a href="#features" className="btn-secondary text-base px-8 py-4">
                  Learn More
                </a>
              </div>
            </div>

            {/* Floating UI Mockup */}
            <div className="relative hidden lg:block">
              <div className="animate-float">
                <div className="glass-card p-6 shadow-2xl">
                  <div className="flex items-center gap-2 mb-4">
                    <div className="w-3 h-3 rounded-full bg-red-400" />
                    <div className="w-3 h-3 rounded-full bg-yellow-400" />
                    <div className="w-3 h-3 rounded-full bg-green-400" />
                  </div>
                  <div className="space-y-3">
                    <div className="h-4 bg-gradient-to-r from-brand-200 to-brand-100 dark:from-brand-800 dark:to-brand-900 rounded w-3/4" />
                    <div className="h-4 bg-gray-100 dark:bg-gray-800 rounded w-full" />
                    <div className="h-4 bg-gray-100 dark:bg-gray-800 rounded w-5/6" />
                    <div className="h-20 bg-gradient-to-br from-brand-100 to-brand-50 dark:from-brand-900/50 dark:to-brand-950/50 rounded-lg mt-4" />
                    <div className="grid grid-cols-3 gap-3 mt-4">
                      <div className="h-16 bg-brand-50 dark:bg-brand-900/30 rounded-lg" />
                      <div className="h-16 bg-brand-100 dark:bg-brand-900/40 rounded-lg" />
                      <div className="h-16 bg-brand-50 dark:bg-brand-900/30 rounded-lg" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Social Proof */}
      <section className="py-12 border-y border-gray-100 dark:border-gray-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
            {[
              { value: '10,000+', label: 'Active Users' },
              { value: '99.9%', label: 'Uptime' },
              { value: '4.9/5', label: 'User Rating' },
              { value: '150+', label: 'Countries' },
            ].map((stat) => (
              <div key={stat.label}>
                <div className="text-3xl font-bold text-gray-900 dark:text-white">{stat.value}</div>
                <div className="text-sm text-gray-500 dark:text-gray-400 mt-1">{stat.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="py-24">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 dark:text-white mb-4">
              Everything you need to <span className="gradient-text">succeed</span>
            </h2>
            <p className="text-lg text-gray-600 dark:text-gray-400 max-w-2xl mx-auto">
              Powerful features designed to help ${config.target_audience} achieve more with less effort.
            </p>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, idx) => (
              <div key={idx} className="glass-card p-6 hover:shadow-lg transition-all duration-300 hover:-translate-y-1">
                <div className="w-12 h-12 rounded-xl bg-brand-50 dark:bg-brand-900/20 text-brand-500 flex items-center justify-center mb-4">
                  {featureIcons[idx % featureIcons.length]}
                </div>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">{feature.title}</h3>
                <p className="text-gray-600 dark:text-gray-400 text-sm leading-relaxed">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="py-24 bg-gray-50 dark:bg-gray-900/50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 dark:text-white mb-4">
              Simple, transparent <span className="gradient-text">pricing</span>
            </h2>
            <p className="text-lg text-gray-600 dark:text-gray-400 max-w-2xl mx-auto">
              Choose the plan that fits your needs. Upgrade or downgrade at any time.
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-8 max-w-5xl mx-auto">
            {pricingPlans.map((plan) => (
              <div
                key={plan.name}
                className={\`rounded-2xl p-8 transition-all duration-300 \${
                  plan.highlighted
                    ? 'bg-brand-500 text-white shadow-2xl shadow-brand-500/30 scale-105 relative'
                    : 'glass-card hover:shadow-lg'
                }\`}
              >
                {plan.highlighted && (
                  <div className="absolute -top-4 left-1/2 -translate-x-1/2 px-4 py-1 bg-brand-700 text-white text-xs font-semibold rounded-full">
                    Most Popular
                  </div>
                )}
                <h3 className={\`text-xl font-bold mb-2 \${plan.highlighted ? 'text-white' : 'text-gray-900 dark:text-white'}\`}>
                  {plan.name}
                </h3>
                <p className={\`text-sm mb-4 \${plan.highlighted ? 'text-brand-100' : 'text-gray-500 dark:text-gray-400'}\`}>
                  {plan.description}
                </p>
                <div className="mb-6">
                  <span className={\`text-4xl font-extrabold \${plan.highlighted ? 'text-white' : 'text-gray-900 dark:text-white'}\`}>
                    {plan.price}
                  </span>
                  <span className={\`text-sm \${plan.highlighted ? 'text-brand-100' : 'text-gray-500 dark:text-gray-400'}\`}>
                    {plan.period}
                  </span>
                </div>
                <ul className="space-y-3 mb-8">
                  {plan.features.map((f) => (
                    <li key={f} className="flex items-center gap-3 text-sm">
                      <svg className={\`w-5 h-5 flex-shrink-0 \${plan.highlighted ? 'text-brand-200' : 'text-brand-500'}\`} fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                      </svg>
                      <span className={plan.highlighted ? 'text-brand-50' : 'text-gray-600 dark:text-gray-300'}>{f}</span>
                    </li>
                  ))}
                </ul>
                <Link
                  href="/login"
                  className={\`block w-full text-center py-3 rounded-xl font-semibold transition-all duration-200 \${
                    plan.highlighted
                      ? 'bg-white text-brand-600 hover:bg-brand-50 shadow-lg'
                      : 'btn-primary w-full'
                  }\`}
                >
                  {plan.cta}
                </Link>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section id="faq" className="py-24">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 dark:text-white mb-4">
              Frequently asked <span className="gradient-text">questions</span>
            </h2>
          </div>

          <div className="space-y-4">
            {faqs.map((faq, idx) => (
              <div key={idx} className="glass-card overflow-hidden">
                <button
                  onClick={() => setOpenFaq(openFaq === idx ? null : idx)}
                  className="w-full flex items-center justify-between p-6 text-left"
                >
                  <span className="font-semibold text-gray-900 dark:text-white">{faq.q}</span>
                  <svg
                    className={\`w-5 h-5 text-gray-500 transition-transform duration-200 \${openFaq === idx ? 'rotate-180' : ''}\`}
                    fill="none" viewBox="0 0 24 24" stroke="currentColor"
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                  </svg>
                </button>
                {openFaq === idx && (
                  <div className="px-6 pb-6 text-gray-600 dark:text-gray-400 text-sm leading-relaxed">
                    {faq.a}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 bg-gradient-to-br from-brand-500 to-brand-700 relative overflow-hidden">
        <div className="absolute inset-0 bg-[url('data:image/svg+xml,%3Csvg%20width%3D%2260%22%20height%3D%2260%22%20viewBox%3D%220%200%2060%2060%22%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%3E%3Cg%20fill%3D%22none%22%20fill-rule%3D%22evenodd%22%3E%3Cg%20fill%3D%22%23ffffff%22%20fill-opacity%3D%220.05%22%3E%3Cpath%20d%3D%22M36%2034v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6%2034v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6%204V0H4v4H0v2h4v4h2V6h4V4H6z%22/%3E%3C/g%3E%3C/g%3E%3C/svg%3E')] opacity-50" />
        <div className="relative max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl sm:text-4xl font-bold text-white mb-6">
            Ready to transform your workflow?
          </h2>
          <p className="text-xl text-brand-100 mb-8">
            Join thousands of ${config.target_audience} who are already using ${config.title}.
          </p>
          <Link href="/login" className="inline-flex items-center px-8 py-4 bg-white text-brand-600 font-semibold rounded-xl hover:bg-brand-50 transition-all duration-200 shadow-lg hover:-translate-y-0.5 text-lg">
            Get Started Free
            <svg className="w-5 h-5 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" /></svg>
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-16 bg-gray-900 dark:bg-gray-950 text-gray-400">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid md:grid-cols-4 gap-12 mb-12">
            <div>
              <div className="flex items-center gap-2 mb-4">
                <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-brand-400 to-brand-600 flex items-center justify-center text-white font-bold text-sm">
                  {('${config.title}')[0]}
                </div>
                <span className="text-lg font-bold text-white">${config.title}</span>
              </div>
              <p className="text-sm leading-relaxed">${config.description}</p>
            </div>
            <div>
              <h4 className="text-white font-semibold mb-4">Product</h4>
              <ul className="space-y-2 text-sm">
                <li><a href="#features" className="hover:text-white transition-colors">Features</a></li>
                <li><a href="#pricing" className="hover:text-white transition-colors">Pricing</a></li>
                <li><a href="#" className="hover:text-white transition-colors">Integrations</a></li>
                <li><a href="#" className="hover:text-white transition-colors">Changelog</a></li>
              </ul>
            </div>
            <div>
              <h4 className="text-white font-semibold mb-4">Company</h4>
              <ul className="space-y-2 text-sm">
                <li><a href="#" className="hover:text-white transition-colors">About</a></li>
                <li><a href="#" className="hover:text-white transition-colors">Blog</a></li>
                <li><a href="#" className="hover:text-white transition-colors">Careers</a></li>
                <li><a href="#" className="hover:text-white transition-colors">Contact</a></li>
              </ul>
            </div>
            <div>
              <h4 className="text-white font-semibold mb-4">Legal</h4>
              <ul className="space-y-2 text-sm">
                <li><a href="#" className="hover:text-white transition-colors">Privacy Policy</a></li>
                <li><a href="#" className="hover:text-white transition-colors">Terms of Service</a></li>
                <li><a href="#" className="hover:text-white transition-colors">Cookie Policy</a></li>
              </ul>
            </div>
          </div>
          <div className="border-t border-gray-800 pt-8 text-sm text-center">
            &copy; {new Date().getFullYear()} ${config.title}. All rights reserved.
          </div>
        </div>
      </footer>
    </div>
  );
}
`
    );

    // ── src/lib/supabase.ts ───────────────────────────────────────────
    files.set(
      'src/lib/supabase.ts',
      `import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

export function getSupabaseClient() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  );
}
`
    );

    // ── src/app/login/page.tsx ────────────────────────────────────────
    files.set(
      'src/app/login/page.tsx',
      `'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { supabase } from '@/lib/supabase';

export default function LoginPage() {
  const router = useRouter();
  const [isSignUp, setIsSignUp] = useState(false);
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setMessage(null);

    try {
      if (isSignUp) {
        const { error } = await supabase.auth.signUp({
          email,
          password,
          options: {
            emailRedirectTo: \`\${window.location.origin}/dashboard\`,
          },
        });
        if (error) throw error;
        setMessage('Check your email for a confirmation link!');
      } else {
        const { error } = await supabase.auth.signInWithPassword({
          email,
          password,
        });
        if (error) throw error;
        router.push('/dashboard');
        router.refresh();
      }
    } catch (err: any) {
      setError(err.message || 'An error occurred');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-950 dark:to-gray-900 px-4">
      <div className="w-full max-w-md">
        <div className="text-center mb-8">
          <Link href="/" className="inline-flex items-center gap-2">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-brand-400 to-brand-600 flex items-center justify-center text-white font-bold">
              ${config.title[0]}
            </div>
            <span className="text-2xl font-bold text-gray-900 dark:text-white">${config.title}</span>
          </Link>
        </div>

        <div className="glass-card p-8 shadow-xl">
          <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">
            {isSignUp ? 'Create your account' : 'Welcome back'}
          </h2>
          <p className="text-gray-500 dark:text-gray-400 text-sm mb-6">
            {isSignUp ? 'Start your free trial today' : 'Sign in to your account'}
          </p>

          {error && (
            <div className="mb-4 p-3 rounded-lg bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-400 text-sm">
              {error}
            </div>
          )}

          {message && (
            <div className="mb-4 p-3 rounded-lg bg-green-50 dark:bg-green-900/20 text-green-600 dark:text-green-400 text-sm">
              {message}
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label htmlFor="email" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                Email address
              </label>
              <input
                id="email"
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                required
                className="w-full px-4 py-3 rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:ring-2 focus:ring-brand-500 focus:border-transparent outline-none transition-all"
                placeholder="you@example.com"
              />
            </div>

            <div>
              <label htmlFor="password" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                Password
              </label>
              <input
                id="password"
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
                minLength={6}
                className="w-full px-4 py-3 rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:ring-2 focus:ring-brand-500 focus:border-transparent outline-none transition-all"
                placeholder="••••••••"
              />
            </div>

            <button
              type="submit"
              disabled={loading}
              className="w-full btn-primary py-3 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {loading ? (
                <svg className="animate-spin h-5 w-5" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                </svg>
              ) : isSignUp ? 'Create Account' : 'Sign In'}
            </button>
          </form>

          <div className="mt-6 text-center">
            <button
              onClick={() => {
                setIsSignUp(!isSignUp);
                setError(null);
                setMessage(null);
              }}
              className="text-sm text-brand-500 hover:text-brand-600 transition-colors"
            >
              {isSignUp ? 'Already have an account? Sign in' : "Don't have an account? Sign up"}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
`
    );

    // ── src/app/dashboard/layout.tsx ──────────────────────────────────
    files.set(
      'src/app/dashboard/layout.tsx',
      `'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { supabase } from '@/lib/supabase';

const navItems = [
  { name: 'Dashboard', href: '/dashboard', icon: 'M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6' },
  { name: 'Analytics', href: '/dashboard', icon: 'M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z' },
  { name: 'Settings', href: '/dashboard', icon: 'M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.066 2.573c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.573 1.066c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.066-2.573c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z' },
];

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  const router = useRouter();
  const [user, setUser] = useState<any>(null);
  const [sidebarOpen, setSidebarOpen] = useState(false);

  useEffect(() => {
    const getUser = async () => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) {
        router.push('/login');
        return;
      }
      setUser(user);
    };
    getUser();
  }, [router]);

  const handleLogout = async () => {
    await supabase.auth.signOut();
    router.push('/');
    router.refresh();
  };

  if (!user) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-950">
        <svg className="animate-spin h-8 w-8 text-brand-500" viewBox="0 0 24 24">
          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
        </svg>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-950">
      {/* Mobile sidebar toggle */}
      <button
        onClick={() => setSidebarOpen(!sidebarOpen)}
        className="fixed top-4 left-4 z-50 lg:hidden p-2 rounded-lg bg-white dark:bg-gray-800 shadow-lg"
      >
        <svg className="w-6 h-6 text-gray-600 dark:text-gray-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
        </svg>
      </button>

      {/* Sidebar */}
      <aside className={\`fixed inset-y-0 left-0 z-40 w-64 bg-white dark:bg-gray-900 border-r border-gray-200 dark:border-gray-800 transform transition-transform duration-200 \${sidebarOpen ? 'translate-x-0' : '-translate-x-full'} lg:translate-x-0\`}>
        <div className="flex flex-col h-full">
          <div className="flex items-center gap-2 px-6 py-5 border-b border-gray-100 dark:border-gray-800">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-brand-400 to-brand-600 flex items-center justify-center text-white font-bold text-sm">
              ${config.title[0]}
            </div>
            <span className="text-lg font-bold text-gray-900 dark:text-white">${config.title}</span>
          </div>

          <nav className="flex-1 px-4 py-6 space-y-1">
            {navItems.map((item) => (
              <Link
                key={item.name}
                href={item.href}
                className="flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm text-gray-600 dark:text-gray-300 hover:bg-brand-50 dark:hover:bg-brand-900/20 hover:text-brand-600 dark:hover:text-brand-400 transition-colors"
              >
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d={item.icon} />
                </svg>
                {item.name}
              </Link>
            ))}
          </nav>

          <div className="px-4 py-4 border-t border-gray-100 dark:border-gray-800">
            <div className="flex items-center gap-3 px-3 py-2 mb-2">
              <div className="w-8 h-8 rounded-full bg-brand-100 dark:bg-brand-900/30 flex items-center justify-center text-brand-600 dark:text-brand-400 text-sm font-semibold">
                {user.email?.[0]?.toUpperCase() || 'U'}
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-sm font-medium text-gray-900 dark:text-white truncate">{user.email}</p>
              </div>
            </div>
            <button
              onClick={handleLogout}
              className="flex items-center gap-3 w-full px-3 py-2.5 rounded-xl text-sm text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/20 transition-colors"
            >
              <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
              </svg>
              Log Out
            </button>
          </div>
        </div>
      </aside>

      {/* Main content */}
      <main className="lg:pl-64">
        <div className="px-6 py-8 lg:px-8">
          {children}
        </div>
      </main>

      {/* Mobile overlay */}
      {sidebarOpen && (
        <div
          className="fixed inset-0 bg-black/50 z-30 lg:hidden"
          onClick={() => setSidebarOpen(false)}
        />
      )}
    </div>
  );
}
`
    );

    // ── src/app/dashboard/page.tsx ────────────────────────────────────
    files.set(
      'src/app/dashboard/page.tsx',
      `'use client';

import { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';

export default function DashboardPage() {
  const [user, setUser] = useState<any>(null);

  useEffect(() => {
    const getUser = async () => {
      const { data: { user } } = await supabase.auth.getUser();
      setUser(user);
    };
    getUser();
  }, []);

  const stats = [
    { label: 'Total Revenue', value: '$0.00', change: '+0%', icon: 'M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z' },
    { label: 'Active Users', value: '0', change: '+0%', icon: 'M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z' },
    { label: 'Subscriptions', value: '0', change: '+0%', icon: 'M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01' },
    { label: 'Conversion Rate', value: '0%', change: '+0%', icon: 'M13 7h8m0 0v8m0-8l-8 8-4-4-6 6' },
  ];

  return (
    <div>
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Dashboard</h1>
        <p className="text-gray-500 dark:text-gray-400 mt-1">
          Welcome back{user?.email ? \`, \${user.email}\` : ''}! Here is your overview.
        </p>
      </div>

      {/* Stats Grid */}
      <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
        {stats.map((stat) => (
          <div key={stat.label} className="glass-card p-6">
            <div className="flex items-center justify-between mb-4">
              <div className="w-10 h-10 rounded-xl bg-brand-50 dark:bg-brand-900/20 text-brand-500 flex items-center justify-center">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d={stat.icon} />
                </svg>
              </div>
              <span className="text-xs font-medium text-green-500 bg-green-50 dark:bg-green-900/20 px-2 py-1 rounded-full">
                {stat.change}
              </span>
            </div>
            <div className="text-2xl font-bold text-gray-900 dark:text-white">{stat.value}</div>
            <div className="text-sm text-gray-500 dark:text-gray-400 mt-1">{stat.label}</div>
          </div>
        ))}
      </div>

      {/* Getting Started */}
      <div className="glass-card p-8">
        <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-4">Getting Started</h2>
        <div className="space-y-4">
          {[
            { step: '1', title: 'Configure your environment variables', desc: 'Add your Supabase and Stripe keys to the .env file' },
            { step: '2', title: 'Set up your Supabase database', desc: 'Create tables for users, subscriptions, and your app data' },
            { step: '3', title: 'Configure Stripe products', desc: 'Create your pricing plans in the Stripe dashboard' },
            { step: '4', title: 'Customize your landing page', desc: 'Update the copy, colors, and features to match your brand' },
          ].map((item) => (
            <div key={item.step} className="flex items-start gap-4 p-4 rounded-xl hover:bg-gray-50 dark:hover:bg-gray-800/50 transition-colors">
              <div className="w-8 h-8 rounded-full bg-brand-100 dark:bg-brand-900/30 text-brand-600 dark:text-brand-400 flex items-center justify-center text-sm font-bold flex-shrink-0">
                {item.step}
              </div>
              <div>
                <h3 className="font-semibold text-gray-900 dark:text-white">{item.title}</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400 mt-0.5">{item.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
`
    );

    // ── src/middleware.ts ──────────────────────────────────────────────
    files.set(
      'src/middleware.ts',
      `import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';
import { createClient } from '@supabase/supabase-js';

export async function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // Only protect /dashboard routes
  if (!pathname.startsWith('/dashboard')) {
    return NextResponse.next();
  }

  // Check for Supabase auth token in cookies
  const supabaseAuthToken = request.cookies.get('sb-access-token')?.value
    || request.cookies.get('sb-refresh-token')?.value;

  // If no auth cookie found, check for the Supabase auth storage cookie pattern
  const allCookies = request.cookies.getAll();
  const hasSupabaseCookie = allCookies.some(
    (cookie) => cookie.name.includes('sb-') && cookie.name.includes('auth-token')
  );

  if (!supabaseAuthToken && !hasSupabaseCookie) {
    const loginUrl = new URL('/login', request.url);
    loginUrl.searchParams.set('redirect', pathname);
    return NextResponse.redirect(loginUrl);
  }

  return NextResponse.next();
}

export const config = {
  matcher: ['/dashboard/:path*'],
};
`
    );

    // ── src/app/api/stripe/checkout/route.ts ──────────────────────────
    files.set(
      'src/app/api/stripe/checkout/route.ts',
      `import { NextRequest, NextResponse } from 'next/server';
import Stripe from 'stripe';

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: '2024-06-20',
});

export async function POST(req: NextRequest) {
  try {
    const { priceId, userId, email } = await req.json();

    if (!priceId) {
      return NextResponse.json({ error: 'Price ID is required' }, { status: 400 });
    }

    const session = await stripe.checkout.sessions.create({
      mode: 'subscription',
      payment_method_types: ['card'],
      line_items: [
        {
          price: priceId,
          quantity: 1,
        },
      ],
      success_url: \`\${process.env.NEXT_PUBLIC_APP_URL}/dashboard?session_id={CHECKOUT_SESSION_ID}\`,
      cancel_url: \`\${process.env.NEXT_PUBLIC_APP_URL}/#pricing\`,
      customer_email: email,
      metadata: {
        userId: userId || '',
      },
    });

    return NextResponse.json({ url: session.url });
  } catch (error: any) {
    console.error('[Stripe Checkout] Error:', error.message);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
`
    );

    // ── src/app/api/stripe/webhook/route.ts ───────────────────────────
    files.set(
      'src/app/api/stripe/webhook/route.ts',
      `import { NextRequest, NextResponse } from 'next/server';
import Stripe from 'stripe';

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: '2024-06-20',
});

const webhookSecret = process.env.STRIPE_WEBHOOK_SECRET!;

export async function POST(req: NextRequest) {
  const body = await req.text();
  const signature = req.headers.get('stripe-signature');

  if (!signature) {
    console.error('[Stripe Webhook] No signature found');
    return NextResponse.json({ error: 'No signature' }, { status: 400 });
  }

  let event: Stripe.Event;

  try {
    event = stripe.webhooks.constructEvent(body, signature, webhookSecret);
  } catch (err: any) {
    console.error('[Stripe Webhook] Verification failed:', err.message);
    return NextResponse.json({ error: 'Webhook verification failed' }, { status: 400 });
  }

  console.log(\`[Stripe Webhook] Received event: \${event.type}\`);

  try {
    switch (event.type) {
      case 'checkout.session.completed': {
        const session = event.data.object as Stripe.Checkout.Session;
        console.log('[Stripe Webhook] Checkout completed:', session.id);
        // TODO: Update user subscription status in Supabase
        // const userId = session.metadata?.userId;
        // await supabase.from('subscriptions').upsert({ user_id: userId, status: 'active', ... });
        break;
      }

      case 'customer.subscription.updated': {
        const subscription = event.data.object as Stripe.Subscription;
        console.log('[Stripe Webhook] Subscription updated:', subscription.id, subscription.status);
        // TODO: Update subscription status in database
        break;
      }

      case 'customer.subscription.deleted': {
        const subscription = event.data.object as Stripe.Subscription;
        console.log('[Stripe Webhook] Subscription canceled:', subscription.id);
        // TODO: Update subscription status to canceled in database
        break;
      }

      case 'invoice.payment_succeeded': {
        const invoice = event.data.object as Stripe.Invoice;
        console.log('[Stripe Webhook] Payment succeeded:', invoice.id);
        break;
      }

      case 'invoice.payment_failed': {
        const invoice = event.data.object as Stripe.Invoice;
        console.log('[Stripe Webhook] Payment failed:', invoice.id);
        // TODO: Notify user of failed payment
        break;
      }

      default:
        console.log(\`[Stripe Webhook] Unhandled event type: \${event.type}\`);
    }
  } catch (error: any) {
    console.error('[Stripe Webhook] Error processing event:', error.message);
    return NextResponse.json({ error: 'Webhook handler failed' }, { status: 500 });
  }

  return NextResponse.json({ received: true });
}
`
    );

    return files;
  }
}

// ─── Color Utility ────────────────────────────────────────────────────

function adjustColor(hex: string, amount: number): string {
  // Simple color lightening/darkening for generating a palette
  const cleanHex = hex.replace('#', '');
  const r = parseInt(cleanHex.substring(0, 2), 16);
  const g = parseInt(cleanHex.substring(2, 4), 16);
  const b = parseInt(cleanHex.substring(4, 6), 16);

  if (amount >= 0) {
    // Lighten: mix with white
    const newR = Math.round(r + (255 - r) * amount);
    const newG = Math.round(g + (255 - g) * amount);
    const newB = Math.round(b + (255 - b) * amount);
    return '#' + [newR, newG, newB].map((c) => c.toString(16).padStart(2, '0')).join('');
  } else {
    // Darken: mix with black
    const factor = 1 + amount;
    const newR = Math.round(r * factor);
    const newG = Math.round(g * factor);
    const newB = Math.round(b * factor);
    return '#' + [newR, newG, newB].map((c) => Math.max(0, c).toString(16).padStart(2, '0')).join('');
  }
}
