"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AlertTriangle, CheckCircle2, Link2, Loader2, MessageCircle, MessagesSquare, RefreshCw, Send, ShieldCheck } from "lucide-react";

const LABELS:Record<string,string>={zeneco:"Zen Eco Homes",soleada:"Soleada.no",pinosoecolife:"Pinoso EcoLife",chatgenius:"ChatGenius.pro",donaanna:"Doña Anna",freddyb:"Freddy Bremseth",freddypublishing:"Freddy Publishing",remasterfreddy:"Re-Master Freddy",neuralbeat:"Re-Master Freddy (legacy)"};
type Row={channelId:string;brandId:string;platform:string;displayName:string;scopes:string[];capabilities:{publish:boolean;readEngagement:boolean;directMessages:boolean;commentReply:boolean};needsCommunicationReconnect:boolean;note:string};
type Data={summary:any;socialReadiness:Row[];policy:any};
function Pill({ok,label}:{ok:boolean;label:string}){return <span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${ok?"bg-emerald-100 text-emerald-900":"bg-rose-100 text-rose-900"}`}>{ok?"Klar":"Mangler"} · {label}</span>}

export default function SocialCommunicationReadiness(){
 const[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/nexus/communications",{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b?.error||`HTTP ${r.status}`);setData(b);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 const rows=useMemo(()=>data?.socialReadiness||[],[data]);
 const ready=rows.filter(x=>!x.needsCommunicationReconnect).length;
 return <div className="mx-auto max-w-[1500px] space-y-6 p-4 text-slate-950 sm:p-6">
  <header className="rounded-3xl border border-cyan-800 bg-gradient-to-br from-slate-950 via-slate-900 to-cyan-950 p-6 text-white shadow-xl"><div className="text-xs font-black uppercase tracking-[.22em] text-cyan-200">Nexus OS · Social Communications</div><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-black text-white">Social Communication Readiness</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-200">Viser bare capabilities som faktisk finnes i canonical OAuth-tokenene. Ingen DM- eller kommentarautomatisering aktiveres før riktig tilgang er verifisert.</p></div><button onClick={load} className="rounded-xl bg-cyan-300 px-4 py-2 text-sm font-black text-slate-950">{loading?<Loader2 className="mr-2 inline h-4 w-4 animate-spin"/>:<RefreshCw className="mr-2 inline h-4 w-4"/>}Oppdater</button></div></header>
  {error&&<div className="rounded-xl border border-rose-400 bg-rose-50 p-4 text-sm font-semibold text-rose-950"><AlertTriangle className="mr-2 inline h-4 w-4"/>{error}</div>}
  <section className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-slate-300 bg-white p-5"><div className="text-xs font-black uppercase text-slate-600">Meta-kanaler</div><div className="mt-2 text-3xl font-black">{rows.length}</div></div><div className="rounded-2xl border border-slate-300 bg-white p-5"><div className="text-xs font-black uppercase text-slate-600">Full kommunikasjon klar</div><div className="mt-2 text-3xl font-black text-emerald-800">{ready}</div></div><div className="rounded-2xl border border-slate-300 bg-white p-5"><div className="text-xs font-black uppercase text-slate-600">Trenger utvidet tilgang</div><div className="mt-2 text-3xl font-black text-amber-800">{Math.max(0,rows.length-ready)}</div></div></section>
  <section className="rounded-2xl border border-slate-300 bg-white shadow-sm"><div className="border-b border-slate-300 p-5"><h2 className="text-xl font-black">Capabilities per kanal</h2><p className="mt-1 text-sm text-slate-600">Publisering og lesing av engagement er separat fra DM og kommentarsvar.</p></div><div className="divide-y divide-slate-200">{rows.length===0?<div className="p-8 text-center text-sm text-slate-600">Ingen aktive Meta-kanaler funnet.</div>:rows.map(row=><article key={row.channelId} className="p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-slate-950 px-2.5 py-1 text-[10px] font-black uppercase text-white">{row.platform}</span><span className="text-lg font-black">{LABELS[row.brandId]||row.brandId}</span></div><div className="mt-1 text-sm text-slate-700">{row.displayName}</div><div className="mt-4 flex flex-wrap gap-2"><Pill ok={row.capabilities.publish} label="Publisering"/><Pill ok={row.capabilities.readEngagement} label="Les engagement"/><Pill ok={row.capabilities.directMessages} label="Direktemeldinger"/><Pill ok={row.capabilities.commentReply} label="Kommentarsvar"/></div><p className="mt-4 max-w-3xl text-sm leading-6 text-slate-700">{row.note}</p></div><div className="shrink-0">{row.needsCommunicationReconnect?<Link href="/connections" className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2 text-sm font-black text-white"><Link2 className="h-4 w-4"/>Reconnect Meta</Link>:<div className="inline-flex items-center gap-2 rounded-xl border border-emerald-300 bg-emerald-50 px-4 py-2 text-sm font-black text-emerald-950"><CheckCircle2 className="h-4 w-4"/>Capability klar</div>}</div></div></article>)}</div></section>
  <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><div className="rounded-2xl border border-slate-300 bg-white p-5"><Send className="h-5 w-5 text-cyan-800"/><h3 className="mt-3 font-black">Publisering</h3><p className="mt-2 text-sm text-slate-600">Kan bruke eksisterende publishing pipeline der kanal-token og Runtime tillater det.</p></div><div className="rounded-2xl border border-slate-300 bg-white p-5"><MessageCircle className="h-5 w-5 text-cyan-800"/><h3 className="mt-3 font-black">Kommentarer</h3><p className="mt-2 text-sm text-slate-600">Antall/engagement kan leses i dag. Svar krever separat verified write capability.</p></div><div className="rounded-2xl border border-slate-300 bg-white p-5"><MessagesSquare className="h-5 w-5 text-cyan-800"/><h3 className="mt-3 font-black">DM</h3><p className="mt-2 text-sm text-slate-600">Ikke aktivert uten non-WhatsApp messaging scope. Nexus viser mangelen i stedet for å late som inboxen finnes.</p></div><div className="rounded-2xl border border-slate-300 bg-white p-5"><ShieldCheck className="h-5 w-5 text-cyan-800"/><h3 className="mt-3 font-black">Autonomi</h3><p className="mt-2 text-sm text-slate-600">Selv med riktige scopes skal svar og proaktiv engagement følge Runtime, rate-limits og kvalitetspolicy.</p></div></section>
  <div className="flex gap-3 rounded-2xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0"/><div><b>Nåværende standard:</b> Social Inbox inneholder ikke oppdiktede meldinger. Først når meldings-/kommentar-capabilities er verifisert bygger Nexus faktisk synkronisering, drafts, svar og learning.</div></div>
 </div>;
}
