"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AlertTriangle, CheckCircle2, Clock3, Link2, Loader2, MessageCircle, MessagesSquare, Play, RefreshCw, Send, ShieldCheck } from "lucide-react";

const LABELS:Record<string,string>={zeneco:"Zen Eco Homes",soleada:"Soleada.no",pinosoecolife:"Pinoso EcoLife",chatgenius:"ChatGenius.pro",donaanna:"Doña Anna",freddyb:"Freddy Bremseth",freddypublishing:"Freddy Publishing",remasterfreddy:"Re-Master Freddy",neuralbeat:"Re-Master Freddy (legacy)"};
type Row={channelId:string;brandId:string;platform:string;displayName:string;scopes:string[];capabilities:{publish:boolean;readEngagement:boolean;readComments:boolean;directMessages:boolean;commentReply:boolean};needsCommunicationReconnect:boolean};
type LastSync={status:string;agentName:string;createdAt:string;source:string|null;commentsFetched:number;conversationsUpserted:number;messagesUpserted:number;readOnly:boolean};
type Data={generatedAt:string;sourceState:{canonicalTablesReady:boolean;externalInboxSyncActive:boolean;note:string;lastSync:LastSync|null};summary:any;runtime:any[];readiness:Row[];conversations:any[];recentDrafts:any[];events30d:any[];recentSyncs:any[]};
function Pill({ok,label}:{ok:boolean;label:string}){return <span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${ok?"bg-emerald-100 text-emerald-900":"bg-rose-100 text-rose-900"}`}>{ok?"Klar":"Mangler"} · {label}</span>}
function formatDate(value?:string|null){if(!value)return "Aldri";try{return new Date(value).toLocaleString("nb-NO");}catch{return value;}}

export default function SocialCommunicationReadiness(){
 const[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const[syncBusy,setSyncBusy]=useState(false),[syncMessage,setSyncMessage]=useState("");
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/nexus/communications/social",{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b?.error||`HTTP ${r.status}`);setData(b);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 const rows=useMemo(()=>data?.readiness||[],[data]);
 const runtime=(key:string)=>data?.runtime?.find((x:any)=>x.control_key===key);
 const sync=runtime("feature:social_inbox_sync"), draft=runtime("feature:social_reply_draft"), live=runtime("feature:social_auto_reply_live");
 const lastSync=data?.sourceState?.lastSync;
 async function runSync(){setSyncBusy(true);setSyncMessage("");setError("");try{const r=await fetch("/api/nexus/communications/social/sync",{method:"POST",credentials:"same-origin"});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error||`HTTP ${r.status}`);if(b.skipped){setSyncMessage(`Ikke kjørt: ${b.reason||"Runtime er AV"}.`);}else{setSyncMessage(`Read-only sync ferdig: ${Number(b.commentsFetched||0)} kommentarer lest, ${Number(b.conversationsUpserted||0)} samtaler og ${Number(b.messagesUpserted||0)} meldinger synkronisert.`);}await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setSyncBusy(false);}}
 return <div className="mx-auto max-w-[1500px] space-y-6 p-4 text-slate-950 sm:p-6">
  <header className="rounded-3xl border border-cyan-800 bg-gradient-to-br from-slate-950 via-slate-900 to-cyan-950 p-6 text-white shadow-xl"><div className="text-xs font-black uppercase tracking-[.22em] text-cyan-200">Nexus OS · Social Communications</div><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-black text-white">Social Communication Readiness</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-200">Capability, canonical inbox-status, Runtime og faktisk synkhelse i én flate. Nexus skiller mellom å lese kommentarer, svare på kommentarer og bruke DM.</p></div><button onClick={load} className="rounded-xl bg-cyan-300 px-4 py-2 text-sm font-black text-slate-950">{loading?<Loader2 className="mr-2 inline h-4 w-4 animate-spin"/>:<RefreshCw className="mr-2 inline h-4 w-4"/>}Oppdater</button></div></header>
  {error&&<div className="rounded-xl border border-rose-400 bg-rose-50 p-4 text-sm font-semibold text-rose-950"><AlertTriangle className="mr-2 inline h-4 w-4"/>{error}</div>}
  {syncMessage&&<div className="rounded-xl border border-cyan-300 bg-cyan-50 p-4 text-sm font-semibold text-cyan-950">{syncMessage}</div>}
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{[["Meta-kanaler",data?.summary?.channels??"—"],["Kommentar-read klare",data?.summary?.commentReadReady??"—"],["Canonical samtaler",data?.summary?.conversations??"—"],["Åpne",data?.summary?.openConversations??"—"],["Svarutkast",data?.summary?.drafts??"—"],["Sent 30d",data?.summary?.sentEvents30d??"—"]].map(([l,v])=><div key={String(l)} className="rounded-2xl border border-slate-300 bg-white p-5 text-slate-950 shadow-sm"><div className="text-xs font-black uppercase text-slate-600">{l}</div><div className="mt-2 text-3xl font-black">{v}</div></div>)}</section>
  <section className="grid gap-3 lg:grid-cols-4"><div className="rounded-2xl border border-slate-300 bg-white p-5"><div className="text-xs font-black uppercase text-slate-600">Social Inbox Sync</div><div className={`mt-2 text-lg font-black ${sync?.enabled?"text-emerald-800":"text-slate-600"}`}>{sync?.enabled?"PÅ":"AV"}</div><div className="mt-2 text-sm text-slate-600">Read-only innhenting. Scheduler kjører hvert 15. minutt. Sender ingenting.</div><button onClick={runSync} disabled={!sync?.enabled||syncBusy} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2 text-sm font-black text-white disabled:cursor-not-allowed disabled:bg-slate-300 disabled:text-slate-600">{syncBusy?<Loader2 className="h-4 w-4 animate-spin"/>:<Play className="h-4 w-4"/>}{syncBusy?"Synkroniserer…":"Kjør read-only sync"}</button>{!sync?.enabled&&<div className="mt-2 text-xs text-slate-500">Slå på Social Inbox Sync i Runtime først.</div>}</div>
  <div className="rounded-2xl border border-slate-300 bg-white p-5"><div className="flex items-center gap-2 text-xs font-black uppercase text-slate-600"><Clock3 className="h-4 w-4"/>Siste faktiske sync</div><div className={`mt-2 text-lg font-black ${lastSync?.status==="success"?"text-emerald-800":lastSync?"text-amber-800":"text-slate-600"}`}>{lastSync?.status?.toUpperCase()||"INGEN LOGG"}</div><div className="mt-2 text-sm text-slate-600">{formatDate(lastSync?.createdAt)}</div><div className="mt-3 grid grid-cols-3 gap-2 text-center"><div className="rounded-lg bg-slate-50 p-2"><div className="text-lg font-black">{lastSync?.commentsFetched??"—"}</div><div className="text-[10px] uppercase text-slate-500">lest</div></div><div className="rounded-lg bg-slate-50 p-2"><div className="text-lg font-black">{lastSync?.conversationsUpserted??"—"}</div><div className="text-[10px] uppercase text-slate-500">samtaler</div></div><div className="rounded-lg bg-slate-50 p-2"><div className="text-lg font-black">{lastSync?.messagesUpserted??"—"}</div><div className="text-[10px] uppercase text-slate-500">meldinger</div></div></div>{lastSync&&<div className="mt-2 text-[11px] text-slate-500">{lastSync.readOnly?"Read-only":"Ukjent modus"} · {lastSync.source||lastSync.agentName}</div>}</div>
  <div className="rounded-2xl border border-slate-300 bg-white p-5"><div className="text-xs font-black uppercase text-slate-600">AI Reply Draft</div><div className={`mt-2 text-lg font-black ${draft?.enabled?"text-emerald-800":"text-slate-600"}`}>{draft?.enabled?"PÅ":"AV"}</div><div className="mt-2 text-sm text-slate-600">Utkast uten sending. Holdes separat fra inbox-sync.</div></div><div className="rounded-2xl border border-slate-300 bg-white p-5"><div className="text-xs font-black uppercase text-slate-600">Social Auto-Reply LIVE</div><div className={`mt-2 text-lg font-black ${live?.enabled?"text-rose-800":"text-slate-600"}`}>{live?.enabled?"PÅ":"AV"}</div><div className="mt-2 text-sm text-slate-600">High risk. Skal være AV til scopes, kvalitet og policy er verifisert.</div><Link href="/nexus-os/runtime" className="mt-3 inline-block text-sm font-black text-cyan-800">Åpne Runtime Controls →</Link></div></section>
  <div className={`rounded-2xl border p-4 text-sm font-semibold ${data?.sourceState?.externalInboxSyncActive?"border-emerald-300 bg-emerald-50 text-emerald-950":"border-amber-300 bg-amber-50 text-amber-950"}`}><b>Datastatus:</b> {data?.sourceState?.note||"—"}</div>
  <section className="rounded-2xl border border-slate-300 bg-white shadow-sm"><div className="border-b border-slate-300 p-5"><h2 className="text-xl font-black">Capabilities per kanal</h2><p className="mt-1 text-sm text-slate-600">Read-only og write-capabilities vises separat. Manglende Instagram comment-scope vises som mangler, ikke som 0 aktivitet.</p></div><div className="divide-y divide-slate-200">{rows.length===0?<div className="p-8 text-center text-sm text-slate-600">Ingen aktive Meta-kanaler funnet.</div>:rows.map(row=><article key={row.channelId} className="p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-slate-950 px-2.5 py-1 text-[10px] font-black uppercase text-white">{row.platform}</span><span className="text-lg font-black">{LABELS[row.brandId]||row.brandId}</span></div><div className="mt-1 text-sm text-slate-700">{row.displayName}</div><div className="mt-4 flex flex-wrap gap-2"><Pill ok={row.capabilities.publish} label="Publisering"/><Pill ok={row.capabilities.readEngagement} label="Les engagement"/><Pill ok={row.capabilities.readComments} label="Les kommentarer"/><Pill ok={row.capabilities.commentReply} label="Svar kommentar"/><Pill ok={row.capabilities.directMessages} label="DM"/></div></div><div className="shrink-0">{row.needsCommunicationReconnect?<Link href="/connections" className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2 text-sm font-black text-white"><Link2 className="h-4 w-4"/>Reconnect Meta</Link>:<div className="inline-flex items-center gap-2 rounded-xl border border-emerald-300 bg-emerald-50 px-4 py-2 text-sm font-black text-emerald-950"><CheckCircle2 className="h-4 w-4"/>Full kommunikasjon klar</div>}</div></div></article>)}</div></section>
  <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><div className="rounded-2xl border border-slate-300 bg-white p-5"><Send className="h-5 w-5 text-cyan-800"/><h3 className="mt-3 font-black">Publisering</h3><p className="mt-2 text-sm text-slate-600">Eksisterende publishing pipeline brukes når kanal-token og Runtime tillater det.</p></div><div className="rounded-2xl border border-slate-300 bg-white p-5"><MessageCircle className="h-5 w-5 text-cyan-800"/><h3 className="mt-3 font-black">Kommentarer</h3><p className="mt-2 text-sm text-slate-600">Read-only sync brukes når readComments er verifisert. Reply-write krever egen capability.</p></div><div className="rounded-2xl border border-slate-300 bg-white p-5"><MessagesSquare className="h-5 w-5 text-cyan-800"/><h3 className="mt-3 font-black">DM</h3><p className="mt-2 text-sm text-slate-600">Ingen DM-sync uten verifisert non-WhatsApp messaging capability.</p></div><div className="rounded-2xl border border-slate-300 bg-white p-5"><ShieldCheck className="h-5 w-5 text-cyan-800"/><h3 className="mt-3 font-black">Autonomi</h3><p className="mt-2 text-sm text-slate-600">Capability gir ikke automatisk tillatelse. Runtime, confidence, rate limits og policy gjelder fortsatt.</p></div></section>
  <div className="flex gap-3 rounded-2xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0"/><div><b>Standard:</b> Social Auto-Reply LIVE er AV. Read-only 0 er bare meningsfullt for kanaler som faktisk har blitt synkronisert med nødvendig capability; skipped kanaler behandles som ukjent.</div></div>
 </div>;
}
