"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AlertTriangle, ArrowLeft, BarChart3, CheckCircle2, Loader2, RefreshCw, Sparkles } from "lucide-react";

const LABELS:Record<string,string>={zeneco:"Zen Eco Homes",soleada:"Soleada.no",pinosoecolife:"Pinoso EcoLife",chatgenius:"ChatGenius.pro",donaanna:"Doña Anna",freddyb:"Freddy Bremseth",freddypublishing:"Freddy Publishing",remasterfreddy:"Re-Master Freddy"};

type Data={generatedAt:string;windowDays:number;summary:any;byBrand:Record<string,any>;rules:any[];policy:any};
function pct(v:any){return `${Math.round(Number(v||0)*100)}%`;}

export default function CommunicationsLearningPage(){
  const [data,setData]=useState<Data|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [brand,setBrand]=useState("all");
  async function load(){setLoading(true);setError("");try{const r=await fetch("/api/nexus/communications/learning",{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b?.error||`HTTP ${r.status}`);setData(b);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  const rules=useMemo(()=>brand==="all"?(data?.rules||[]):(data?.rules||[]).filter((r:any)=>r.brand_id===brand),[data,brand]);
  const brands=Object.keys(data?.byBrand||{}).sort();
  return <div className="mx-auto max-w-[1500px] space-y-6 p-4 text-slate-950 sm:p-6">
    <header className="rounded-3xl border border-violet-800 bg-gradient-to-br from-slate-950 via-slate-900 to-violet-950 p-6 text-white shadow-xl">
      <div className="text-xs font-black uppercase tracking-[.22em] text-violet-200">Nexus OS · Communications Learning</div>
      <div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-black text-white">Hvordan Nexus lærer kommunikasjon</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-200">Måler hva AI foreslår, hva du endrer og hvilke svar som faktisk gir respons. Regler må bygge evidens før de får påvirke framtidige drafts.</p></div><div className="flex gap-2"><Link href="/nexus-os/communications" className="rounded-xl border border-white/30 px-4 py-2 text-sm font-bold text-white"><ArrowLeft className="mr-2 inline h-4 w-4"/>Communications</Link><button onClick={load} className="rounded-xl bg-violet-300 px-4 py-2 text-sm font-black text-slate-950">{loading?<Loader2 className="mr-2 inline h-4 w-4 animate-spin"/>:<RefreshCw className="mr-2 inline h-4 w-4"/>}Oppdater</button></div></div>
    </header>
    {error&&<div className="rounded-xl border border-rose-400 bg-rose-50 p-4 text-sm font-semibold text-rose-950"><AlertTriangle className="mr-2 inline h-4 w-4"/>{error}</div>}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{[["Brands",data?.summary?.brands??"—"],["Observasjoner",data?.summary?.observations??"—"],["Regler",data?.summary?.rules??"—"],["Actionable",data?.summary?.actionable??"—"],["Strong evidence",data?.summary?.strong??"—"],["Drafts med læring",data?.summary?.draftsWithLearning??0]].map(([l,v])=><div key={String(l)} className="rounded-2xl border border-slate-300 bg-white p-4 text-slate-950 shadow-sm"><BarChart3 className="h-5 w-5 text-violet-800"/><div className="mt-3 text-xs font-bold uppercase text-slate-600">{l}</div><div className="mt-1 text-2xl font-black text-slate-950">{v}</div></div>)}</section>
    <section className="rounded-2xl border border-slate-300 bg-white p-5 text-slate-950 shadow-sm"><h2 className="text-xl font-black text-slate-950">90-dagers læringsgrunnlag</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{brands.map(b=>{const x=data!.byBrand[b];return <div key={b} className="rounded-xl border border-slate-300 bg-slate-50 p-4 text-slate-950"><div className="font-black text-slate-950">{LABELS[b]||b}</div><div className="mt-3 grid grid-cols-2 gap-2 text-xs text-slate-700"><div>Drafts <b className="text-slate-950">{x.drafts}</b></div><div>Med læring <b className="text-slate-950">{x.draftsWithLearning??0}</b></div><div>Edits <b className="text-slate-950">{x.edits}</b></div><div>Sent <b className="text-slate-950">{x.sent}</b></div><div>Replies <b className="text-slate-950">{x.replies}</b></div><div>Reply rate <b className="text-slate-950">{pct(x.replyRate)}</b></div><div>Avg edit <b className="text-slate-950">{pct(x.avgEditRatio)}</b></div></div></div>})}</div></section>
    <section className="rounded-2xl border border-slate-300 bg-white text-slate-950 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-300 p-5"><div><h2 className="text-xl font-black text-slate-950">Læringsregler</h2><p className="mt-1 text-sm text-slate-600">Tone, språk og intent vurderes mot reply-rate og hvor mye du redigerer. “Brukt i drafts” viser faktisk anvendelse, ikke bare at regelen finnes.</p></div><select value={brand} onChange={e=>setBrand(e.target.value)} className="rounded-xl border border-slate-400 bg-white px-3 py-2 text-sm font-semibold text-slate-950"><option value="all">Alle brands</option>{brands.map(b=><option key={b} value={b}>{LABELS[b]||b}</option>)}</select></div><div className="divide-y divide-slate-200">{rules.length===0?<div className="p-8 text-center text-sm text-slate-600">Ingen regler ennå. Nexus trenger først faktiske sendte drafts og outcomes.</div>:rules.map((r:any)=><article key={`${r.brand_id}:${r.dimension}:${r.value}`} className="p-5"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-slate-950 px-2.5 py-1 text-[10px] font-black text-white">{LABELS[r.brand_id]||r.brand_id}</span><span className="rounded-full bg-violet-100 px-2.5 py-1 text-[10px] font-black text-violet-900">{r.dimension}={r.value}</span><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${["moderate","strong"].includes(r.evidence)?"bg-emerald-100 text-emerald-900":"bg-amber-100 text-amber-900"}`}>{r.evidence}</span><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${r.verdict==="prefer"?"bg-emerald-100 text-emerald-900":r.verdict==="avoid"?"bg-rose-100 text-rose-900":"bg-slate-100 text-slate-800"}`}>{r.verdict}</span></div><div className="mt-3 grid gap-2 sm:grid-cols-4"><div className="text-sm">Sample <b>{r.sample}</b></div><div className="text-sm">Reply <b>{pct(r.reply_rate)}</b></div><div className="text-sm">Avg edit <b>{pct(r.avg_edit_ratio)}</b></div><div className="text-sm">Brukt i drafts <b>{r.appliedDrafts??0}</b></div></div><p className="mt-3 text-sm leading-6 text-slate-700">{r.finding}</p></article>)}</div></section>
    <div className="flex gap-3 rounded-2xl border border-violet-300 bg-violet-50 p-4 text-sm text-violet-950"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0"/><div><b>Evidensgrense:</b> 5 = limited, 10 = moderate, 25 = strong. Bare aktive prefer/avoid-regler med sample ≥10 og moderate/strong evidence kan påvirke nye drafts. De brukes som svak preferanse; fakta, brand-policy og sikkerhet vinner alltid.</div></div>
  </div>;
}
