"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Clock3, Inbox, Loader2, Mail, RefreshCw, ShieldCheck, Sparkles, Wrench, PauseCircle, X } from "lucide-react";

const BRAND_LABELS: Record<string,string> = { zeneco:"Zen Eco Homes",soleada:"Soleada.no",pinosoecolife:"Pinoso EcoLife",chatgenius:"ChatGenius.pro",donaanna:"Doña Anna",freddyb:"Freddy Bremseth",freddypublishing:"Freddy Publishing",remasterfreddy:"Re-Master Freddy" };
type InboxRow={id:string;brand_id:string;from_address:string;from_name:string|null;subject:string|null;ai_summary:string|null;ai_intent:string|null;ai_urgency:string|null;ai_sentiment:string|null;ai_suggested_action:string|null;is_read:boolean;has_draft_reply:boolean;replied_at:string|null;received_at:string|null;ageHours:number|null;score:number;reasons:string[];draft:null|{id:string;subject:string;body_text:string;confidence:number|null;status:string;created_at:string};ownerFocus:any};
type Data={generatedAt:string;summary:any;runtime:any[];emailAccounts:any[];ownerFocus:any[];inbox:InboxRow[];policy:any};
function fmtDate(v:string|null|undefined){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString("nb-NO",{dateStyle:"short",timeStyle:"short"});}
function urgencyClass(v:string|null){const x=String(v||"").toLowerCase();if(["critical","urgent","high"].includes(x))return"bg-rose-100 text-rose-900";if(["medium","normal"].includes(x))return"bg-amber-100 text-amber-900";return"bg-slate-100 text-slate-800";}
function healthStyle(status:string|undefined){const s=String(status||"unknown");if(s==="healthy")return"border-emerald-300 bg-emerald-50 text-emerald-950";if(s==="paused")return"border-rose-300 bg-rose-50 text-rose-950";if(s==="degraded")return"border-amber-300 bg-amber-50 text-amber-950";return"border-slate-300 bg-slate-50 text-slate-950";}
function healthLabel(status:string|undefined){const s=String(status||"unknown");if(s==="healthy")return"Frisk";if(s==="paused")return"Pauset";if(s==="degraded")return"Degradert";return"Ukjent";}

export default function NexusCommunicationsPage(){
 const[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState(""),[brand,setBrand]=useState("all");
 const[repair,setRepair]=useState<any|null>(null),[provider,setProvider]=useState<"hostinger"|"gmail">("hostinger"),[repairEmail,setRepairEmail]=useState(""),[repairPassword,setRepairPassword]=useState(""),[repairBusy,setRepairBusy]=useState(false),[repairMessage,setRepairMessage]=useState("");
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/nexus/communications",{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b?.error||`HTTP ${r.status}`);setData(b);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function analyze(emailId:string){setBusy(emailId);setError("");try{const r=await fetch("/api/email/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email_id:emailId})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error||`HTTP ${r.status}`);await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(null);}}
 function openRepair(a:any){setRepair(a);setRepairEmail(a.email_address||"");setProvider(String(a.email_address||"").endsWith("@gmail.com")?"gmail":"hostinger");setRepairPassword("");setRepairMessage("");}
 async function reconnect(){if(!repair)return;setRepairBusy(true);setRepairMessage("");try{const r=await fetch("/api/nexus/communications/email-account",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({accountId:repair.id,provider,emailAddress:repairEmail,password:repairPassword})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error||`HTTP ${r.status}`);setRepairMessage("Tilkoblingen er testet og aktivert.");setRepairPassword("");await load();setTimeout(()=>setRepair(null),900);}catch(e){setRepairMessage(e instanceof Error?e.message:String(e));}finally{setRepairBusy(false);}}
 const brands=useMemo(()=>Array.from(new Set((data?.inbox||[]).map(x=>x.brand_id))).sort(),[data]);
 const rows=useMemo(()=>brand==="all"?(data?.inbox||[]):(data?.inbox||[]).filter(x=>x.brand_id===brand),[data,brand]);
 const runtime=(key:string)=>data?.runtime.find((x:any)=>x.control_key===key)?.enabled;const autoDraftConfig=data?.runtime.find((x:any)=>x.control_key==="cron:/api/cron/email-auto-draft")?.config;
 return <div className="mx-auto max-w-[1500px] space-y-6 p-4 text-slate-950 sm:p-6">
  <header className="rounded-3xl border border-cyan-800 bg-gradient-to-br from-slate-950 via-slate-900 to-cyan-950 p-6 text-white shadow-xl"><div className="text-xs font-black uppercase tracking-[.22em] text-cyan-200">Nexus OS · Communications</div><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-black text-white">Communications Director</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-200">Prioritert innboks, AI-analyse, svarutkast, nurture og kontohelse. Nexus forbereder arbeidet 24/7; sending styres separat av Runtime og Autonomy.</p></div><button onClick={load} disabled={loading} className="rounded-xl bg-cyan-300 px-4 py-2 text-sm font-black text-slate-950 disabled:opacity-60">{loading?<Loader2 className="mr-2 inline h-4 w-4 animate-spin"/>:<RefreshCw className="mr-2 inline h-4 w-4"/>}{loading?"Oppdaterer":"Oppdater"}</button></div></header>
  {error&&<div className="rounded-xl border border-rose-400 bg-rose-50 p-4 text-sm font-semibold text-rose-950"><AlertTriangle className="mr-2 inline h-4 w-4"/>{error}</div>}
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{[["Innboks",data?.summary?.inbox??"—",Inbox],["Ulest",data?.summary?.unread??"—",Mail],["Uten utkast",data?.summary?.withoutDraft??"—",Sparkles],[">24t uten svar",data?.summary?.unreplied24h??"—",Clock3],["Kontoer med feil",data?.summary?.unhealthyEmailAccounts??"—",AlertTriangle],["Nurture sent 30d",data?.summary?.nurture30d?.sent??0,CheckCircle2]].map(([label,value,Icon]:any)=><div key={label} className="rounded-2xl border border-slate-300 bg-white p-4 text-slate-950 shadow-sm"><Icon className="h-5 w-5 text-cyan-800"/><div className="mt-3 text-xs font-bold uppercase text-slate-600">{label}</div><div className="mt-1 text-2xl font-black text-slate-950">{value}</div></div>)}</section>
  <section className="grid gap-3 lg:grid-cols-4"><div className="rounded-2xl border border-slate-300 bg-white p-5"><div className="text-xs font-black uppercase text-slate-600">Email ingest</div><div className={`mt-2 text-lg font-black ${runtime("cron:/api/cron/email-ingest")?"text-emerald-800":"text-slate-600"}`}>{runtime("cron:/api/cron/email-ingest")?"PÅ":"AV"}</div></div><div className="rounded-2xl border border-slate-300 bg-white p-5"><div className="text-xs font-black uppercase text-slate-600">AI Auto-draft</div><div className={`mt-2 text-lg font-black ${runtime("cron:/api/cron/email-auto-draft")?"text-emerald-800":"text-slate-600"}`}>{runtime("cron:/api/cron/email-auto-draft")?"PÅ":"AV"}</div><div className="mt-2 text-sm text-slate-600">Batch {autoDraftConfig?.max_per_run??"—"}</div></div><div className="rounded-2xl border border-slate-300 bg-white p-5"><div className="text-xs font-black uppercase text-slate-600">Nurture LIVE</div><div className={`mt-2 text-lg font-black ${runtime("feature:nurture_live")?"text-emerald-800":"text-slate-600"}`}>{runtime("feature:nurture_live")?"PÅ":"AV / dry-run"}</div></div><div className="rounded-2xl border border-slate-300 bg-white p-5"><div className="text-xs font-black uppercase text-slate-600">Routine auto-reply</div><div className={`mt-2 text-lg font-black ${runtime("feature:routine_email_reply_live")?"text-emerald-800":"text-slate-600"}`}>{runtime("feature:routine_email_reply_live")?"PÅ":"AV"}</div></div></section>
  <section className="rounded-2xl border border-slate-300 bg-white p-5 shadow-sm"><div><h2 className="text-xl font-black">E-postkontoer</h2><p className="mt-1 text-sm text-slate-600">Reparer kontoer her. Nexus tester tilkoblingen før kryptert credential lagres og auto-fetch reaktiveres.</p></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{(data?.emailAccounts||[]).map((a:any)=><div key={a.id||`${a.brand_id}:${a.email_address}`} className={`rounded-xl border p-4 ${healthStyle(a.health_status)}`}><div className="flex items-start justify-between gap-3"><div><div className="font-black">{BRAND_LABELS[a.brand_id]||a.brand_id}</div><div className="mt-1 text-xs opacity-80">{a.email_address}</div></div><span className="rounded-full border border-current/20 bg-white/70 px-2 py-1 text-[10px] font-black uppercase">{healthLabel(a.health_status)}</span></div><div className="mt-3 text-xs opacity-80">Sist hentet: {fmtDate(a.last_fetched_at)}</div>{a.health_message&&<div className="mt-3 rounded-lg border border-current/20 bg-white/70 p-2 text-xs font-semibold">{a.health_message}</div>}<div className="mt-2 text-xs opacity-80">Feil på rad: {Number(a.consecutive_failures||0)}</div>{a.needsReconnect&&<button onClick={()=>openRepair(a)} className="mt-3 inline-flex items-center gap-1 rounded-lg bg-slate-950 px-3 py-2 text-xs font-black text-white"><Wrench className="h-3.5 w-3.5"/>Koble/reparer</button>}{a.auto_fetch_paused_by_system&&<div className="mt-2 flex items-center gap-1 text-xs font-black"><PauseCircle className="h-3.5 w-3.5"/>Auto-fetch stoppet av Nexus</div>}</div>)}</div></section>
  <section className="rounded-2xl border border-slate-300 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-300 p-5"><div><h2 className="text-xl font-black">Prioritert innboks</h2><p className="mt-1 text-sm text-slate-600">Ulest, urgency, svartid og Owner Focus løfter prioriteten.</p></div><select value={brand} onChange={e=>setBrand(e.target.value)} className="rounded-xl border border-slate-400 bg-white px-3 py-2 text-sm font-semibold text-slate-950"><option value="all">Alle brands</option>{brands.map(b=><option key={b} value={b}>{BRAND_LABELS[b]||b}</option>)}</select></div><div className="divide-y divide-slate-200">{rows.length===0?<div className="p-8 text-center text-sm text-slate-600">Ingen meldinger.</div>:rows.map(row=><article key={row.id} className="p-5"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-slate-950 px-2.5 py-1 text-[10px] font-black text-white">Score {row.score}</span><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${urgencyClass(row.ai_urgency)}`}>{row.ai_urgency||"uanalysert"}</span>{row.ownerFocus&&<span className="rounded-full bg-fuchsia-100 px-2.5 py-1 text-[10px] font-black text-fuchsia-900">OWNER FOCUS</span>}</div><h3 className="mt-3 text-lg font-black">{row.subject||"(uten emne)"}</h3><div className="mt-1 text-sm text-slate-700">{row.from_name||row.from_address} · {BRAND_LABELS[row.brand_id]||row.brand_id} · {fmtDate(row.received_at)}</div>{row.ai_summary&&<p className="mt-3 text-sm leading-6 text-slate-800">{row.ai_summary}</p>}{row.draft&&<details className="mt-4 rounded-xl border border-emerald-300 bg-emerald-50 p-3"><summary className="cursor-pointer text-sm font-black text-emerald-950">Svarutkast · confidence {row.draft.confidence==null?"—":Math.round(Number(row.draft.confidence)*100)+"%"}</summary><div className="mt-3 whitespace-pre-wrap text-sm text-slate-800"><b>{row.draft.subject}</b>{"\n\n"}{row.draft.body_text}</div></details>}</div><button onClick={()=>analyze(row.id)} disabled={busy===row.id} className="shrink-0 rounded-xl bg-slate-950 px-4 py-2 text-sm font-black text-white disabled:opacity-50">{busy===row.id?<Loader2 className="mr-2 inline h-4 w-4 animate-spin"/>:<Sparkles className="mr-2 inline h-4 w-4"/>}{row.has_draft_reply?"Analyser på nytt":"Analyser + lag utkast"}</button></div></article>)}</div></section>
  <div className="flex gap-3 rounded-2xl border border-cyan-300 bg-cyan-50 p-4 text-sm text-cyan-950"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0"/><div><b>Standard:</b> Nexus kan forberede og lære 24/7. Autonom sending krever separat policy og skal ikke aktiveres av reconnect.</div></div>
  {repair&&<div className="fixed inset-0 z-[90] flex items-end bg-slate-950/70 p-3 sm:items-center sm:justify-center"><div className="w-full max-w-lg rounded-2xl bg-white p-5 text-slate-950 shadow-2xl"><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-black uppercase text-cyan-800">Nexus e-post reconnect</div><h3 className="mt-1 text-xl font-black">{BRAND_LABELS[repair.brand_id]||repair.brand_id}</h3><div className="text-sm text-slate-600">Eksisterende passord vises aldri.</div></div><button onClick={()=>setRepair(null)} className="rounded-lg border border-slate-300 p-2"><X className="h-4 w-4"/></button></div><div className="mt-5 space-y-4"><label className="block"><span className="text-xs font-black uppercase text-slate-600">Provider</span><select value={provider} onChange={e=>setProvider(e.target.value as any)} className="mt-1 w-full rounded-xl border border-slate-400 bg-white px-3 py-2.5 text-slate-950"><option value="hostinger">Hostinger</option><option value="gmail">Gmail</option></select></label><label className="block"><span className="text-xs font-black uppercase text-slate-600">E-postadresse</span><input value={repairEmail} onChange={e=>setRepairEmail(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-400 px-3 py-2.5"/></label><label className="block"><span className="text-xs font-black uppercase text-slate-600">Nytt passord / app-passord</span><input type="password" value={repairPassword} onChange={e=>setRepairPassword(e.target.value)} autoComplete="new-password" className="mt-1 w-full rounded-xl border border-slate-400 px-3 py-2.5"/></label>{provider==="gmail"&&<div className="rounded-xl border border-amber-300 bg-amber-50 p-3 text-xs text-amber-950">Gmail krever normalt et gyldig app-passord/tilgang som tillater IMAP. Nexus tester før lagring.</div>}{repairMessage&&<div className={`rounded-xl border p-3 text-sm font-semibold ${repairMessage.startsWith("Tilkoblingen er")?"border-emerald-300 bg-emerald-50 text-emerald-950":"border-rose-300 bg-rose-50 text-rose-950"}`}>{repairMessage}</div>}<button onClick={reconnect} disabled={repairBusy||!repairPassword||!repairEmail} className="w-full rounded-xl bg-slate-950 px-4 py-3 text-sm font-black text-white disabled:opacity-50">{repairBusy?<><Loader2 className="mr-2 inline h-4 w-4 animate-spin"/>Tester tilkobling…</>:"Test og aktiver"}</button></div></div></div>}
 </div>;
}
