// ─── Brand-specific 5×5 scene templates ───────────────────────────────
// Each brand type maps to a 25-scene matrix that's been adapted to its
// category. All scenes use {LABEL} placeholder which is resolved per
// product in the prompt builder.

import type { BrandTemplate, BrandTemplateKey, SceneTemplate } from "@/types/ads";

// ─── REAL ESTATE (Soleada, Zen Eco, Pinosos) ─────────────────────────
const realEstateScenes: SceneTemplate[] = [
  // Angle: Lifestyle Living
  { id: "A1", angle: "Lifestyle Living", mood: "bright/airy",
    prompt_body: "Bright airy lifestyle photography of {LABEL} family enjoying morning coffee on a sun-drenched terrace overlooking the Mediterranean, soft warm light, relaxed elegance." },
  { id: "A2", angle: "Lifestyle Living", mood: "bright/airy",
    prompt_body: "Bright airy poolside photography of {LABEL} with infinity pool merging into Costa Blanca horizon, palm trees, white loungers, golden hour." },
  { id: "A3", angle: "Lifestyle Living", mood: "moody/premium",
    prompt_body: "Editorial evening photography of {LABEL} with warm interior lights glowing through floor-to-ceiling windows, twilight sky, refined Mediterranean modernism." },
  { id: "A4", angle: "Lifestyle Living", mood: "bright/airy",
    prompt_body: "Open-plan kitchen photography of {LABEL} with a couple cooking together, fresh herbs and olive oil on a marble island, natural daylight, slow living." },
  { id: "A5", angle: "Lifestyle Living", mood: "minimal/clean",
    prompt_body: "Nordic-inspired interior photography of {LABEL} with light oak floors, linen sofa, ceramic vase, soft morning light, calm Scandinavian-Mediterranean fusion." },

  // Angle: Location Hero
  { id: "B1", angle: "Location Hero", mood: "bold/contrasty",
    prompt_body: "Aerial drone photography of {LABEL} property surrounded by Costa Blanca coastline, turquoise sea, golden cliffs, dramatic perspective." },
  { id: "B2", angle: "Location Hero", mood: "moody/premium",
    prompt_body: "Sunset cinematic photography of {LABEL} villa silhouetted against orange Mediterranean sky, mountains behind, premium destination mood." },
  { id: "B3", angle: "Location Hero", mood: "bright/airy",
    prompt_body: "Charming village street photography of {LABEL} with whitewashed Spanish houses, bougainvillea, cobblestone, warm afternoon light." },
  { id: "B4", angle: "Location Hero", mood: "rustic/artisanal",
    prompt_body: "Rural landscape photography of {LABEL} surrounded by olive groves and almond blossoms, pastel hills, dust motes in golden light." },
  { id: "B5", angle: "Location Hero", mood: "bright/airy",
    prompt_body: "Beachfront promenade photography of {LABEL} with Mediterranean walking path, palm trees, sailboats on horizon, calm midday light." },

  // Angle: Architectural Detail
  { id: "C1", angle: "Architectural Detail", mood: "minimal/clean",
    prompt_body: "Architectural detail photography of {LABEL} showing clean white stucco walls, dark wood beams, single olive tree, sharp midday shadows." },
  { id: "C2", angle: "Architectural Detail", mood: "moody/premium",
    prompt_body: "Premium architectural photography of {LABEL} with stone-clad facade, large pivot door, warm interior light spilling out at dusk." },
  { id: "C3", angle: "Architectural Detail", mood: "minimal/clean",
    prompt_body: "Studio-style architectural photography of {LABEL} highlighting a sculptural staircase, polished concrete, single statement art piece." },
  { id: "C4", angle: "Architectural Detail", mood: "bright/airy",
    prompt_body: "Open-air patio photography of {LABEL} with terracotta floor, white pergola, climbing jasmine, soft diffused light." },
  { id: "C5", angle: "Architectural Detail", mood: "moody/premium",
    prompt_body: "Bathroom suite photography of {LABEL} with travertine walls, freestanding tub, brass fixtures, soft moody light." },

  // Angle: Investment Story
  { id: "D1", angle: "Investment Story", mood: "moody/premium",
    prompt_body: "Editorial photography of {LABEL} with key handover moment, two professional hands exchanging keys over a marble desk, warm conference room mood." },
  { id: "D2", angle: "Investment Story", mood: "minimal/clean",
    prompt_body: "Clean infographic-style photography of {LABEL} with property exterior overlaid with subtle market data graphics, professional finance aesthetic." },
  { id: "D3", angle: "Investment Story", mood: "bright/airy",
    prompt_body: "Lifestyle photography of {LABEL} with relaxed couple reviewing property documents on a sunny terrace, espresso cups, confident decision moment." },
  { id: "D4", angle: "Investment Story", mood: "moody/premium",
    prompt_body: "Boardroom-style photography of {LABEL} with property model on a dark walnut desk, premium pen and notebook, low warm lighting." },
  { id: "D5", angle: "Investment Story", mood: "bright/airy",
    prompt_body: "Real estate agent professional photography of {LABEL} with welcoming gesture toward camera (only hand and forearm visible) presenting property keys." },

  // Angle: Family / Community
  { id: "E1", angle: "Family Story", mood: "bright/airy",
    prompt_body: "Warm family photography of {LABEL} with children playing in a garden of olive trees and lavender, parents watching from doorway, golden hour." },
  { id: "E2", angle: "Family Story", mood: "moody/premium",
    prompt_body: "Editorial dinner photography of {LABEL} with multi-generational family at long candlelit outdoor table, vineyards in the background, warm intimate atmosphere." },
  { id: "E3", angle: "Family Story", mood: "bright/airy",
    prompt_body: "Bright morning photography of {LABEL} with grandparents and grandchildren cooking together in a sunny Mediterranean kitchen, slow domestic luxury." },
  { id: "E4", angle: "Family Story", mood: "rustic/artisanal",
    prompt_body: "Rustic outdoor photography of {LABEL} with friends gathered around a wood-fired pizza oven, terracotta plates, hand-torn bread, sunset glow." },
  { id: "E5", angle: "Family Story", mood: "bright/airy",
    prompt_body: "Calm photography of {LABEL} with parent reading a book to child on a sun-warmed terrace, linen throw, ceramic mug of tea, mindful moment." },
];

// ─── SAAS (ChatGenius) ───────────────────────────────────────────────
const saasScenes: SceneTemplate[] = [
  // Pain Point
  { id: "A1", angle: "Pain Point", mood: "moody/premium",
    prompt_body: "Editorial photography of {LABEL} on a cluttered desk with overflowing email notifications glowing on a dark monitor, frustrated late-night atmosphere." },
  { id: "A2", angle: "Pain Point", mood: "bold/contrasty",
    prompt_body: "Dramatic close-up photography of {LABEL} with a smartphone screen showing dozens of unread messages, hand reaching toward it, high contrast." },
  { id: "A3", angle: "Pain Point", mood: "minimal/clean",
    prompt_body: "Minimalist photography of {LABEL} on a white desk beside a clock showing 11pm, single coffee cup, lonely productivity scene." },
  { id: "A4", angle: "Pain Point", mood: "moody/premium",
    prompt_body: "Office photography of {LABEL} with paper customer-support tickets spilling out of an inbox tray, dim lighting, overwhelm visualized." },
  { id: "A5", angle: "Pain Point", mood: "bright/airy",
    prompt_body: "Modern home-office photography of {LABEL} with a small business owner staring at multiple browser tabs, soft daylight, contemplative mood." },

  // Demo / Product Hero
  { id: "B1", angle: "Demo", mood: "minimal/clean",
    prompt_body: "Crisp product screenshot photography of {LABEL} interface displayed on a sleek MacBook on a marble desk, clean modern SaaS aesthetic." },
  { id: "B2", angle: "Demo", mood: "minimal/clean",
    prompt_body: "Studio photography of {LABEL} on a smartphone showing chatbot conversation in mid-flow, soft gradient backdrop, premium tech feel." },
  { id: "B3", angle: "Demo", mood: "bold/contrasty",
    prompt_body: "Dynamic photography of {LABEL} with multiple device screens (laptop, tablet, phone) all showing the platform, cinematic dark backdrop." },
  { id: "B4", angle: "Demo", mood: "minimal/clean",
    prompt_body: "Top-down flat lay photography of {LABEL} laptop displaying dashboard, stylish notebook, premium pen, soft daylight, clean editorial styling." },
  { id: "B5", angle: "Demo", mood: "moody/premium",
    prompt_body: "Cinematic photography of {LABEL} screen glowing in a dim modern home office, holographic interface accent, premium SaaS storytelling." },

  // Social Proof
  { id: "C1", angle: "Social Proof", mood: "bright/airy",
    prompt_body: "Editorial photography of {LABEL} with smiling diverse founder team in a bright modern office, casual confidence, success story." },
  { id: "C2", angle: "Social Proof", mood: "minimal/clean",
    prompt_body: "Clean studio photography of {LABEL} with floating customer logo grid behind, minimal premium credibility aesthetic." },
  { id: "C3", angle: "Social Proof", mood: "bright/airy",
    prompt_body: "Lifestyle photography of {LABEL} with a small business owner smiling at her laptop in a sunlit cafe, satisfied user moment." },
  { id: "C4", angle: "Social Proof", mood: "moody/premium",
    prompt_body: "Studio photography of {LABEL} on a shelf surrounded by industry awards, premium recognition aesthetic." },
  { id: "C5", angle: "Social Proof", mood: "minimal/clean",
    prompt_body: "Top-down photography of {LABEL} on a desk beside a printed customer testimonial card with 5-star rating, clean, focused, trustworthy." },

  // Hero Feature
  { id: "D1", angle: "Hero Feature", mood: "bold/contrasty",
    prompt_body: "Studio hero photography of {LABEL} interface with dynamic glowing data flow lines emanating from it, dark futuristic backdrop." },
  { id: "D2", angle: "Hero Feature", mood: "minimal/clean",
    prompt_body: "Premium product photography of {LABEL} chat widget appearing on a soft pastel website mockup, minimalist composition." },
  { id: "D3", angle: "Hero Feature", mood: "moody/premium",
    prompt_body: "Cinematic photography of {LABEL} showing AI-powered automation visualization, glowing nodes and connections, premium tech atmosphere." },
  { id: "D4", angle: "Hero Feature", mood: "minimal/clean",
    prompt_body: "Architectural-style photography of {LABEL} sitting on a clean cream backdrop with a single sculptural shadow, museum-object styling for software." },
  { id: "D5", angle: "Hero Feature", mood: "bright/airy",
    prompt_body: "Cheerful flat-lay photography of {LABEL} with playful icons of integrations (Slack, email, calendar) arranged around it, modern editorial look." },

  // ROI Story
  { id: "E1", angle: "ROI Story", mood: "minimal/clean",
    prompt_body: "Clean photography of {LABEL} on a desk beside a printed graph showing dramatic upward growth curve, ambitious business mood." },
  { id: "E2", angle: "ROI Story", mood: "bold/contrasty",
    prompt_body: "Dramatic photography of {LABEL} with a glowing 'ROI 380%' floating headline behind it, dark moody backdrop, results-focused energy." },
  { id: "E3", angle: "ROI Story", mood: "bright/airy",
    prompt_body: "Lifestyle photography of {LABEL} with a confident founder reviewing growth metrics on a tablet at a sunlit cafe, success ritual." },
  { id: "E4", angle: "ROI Story", mood: "moody/premium",
    prompt_body: "Editorial photography of {LABEL} with elegant gold-foil-printed monthly report card highlighting time-saved metrics, premium feel." },
  { id: "E5", angle: "ROI Story", mood: "bright/airy",
    prompt_body: "Calm photography of {LABEL} with a relaxed business owner enjoying a coffee while the platform works in the background, work-life balance achieved." },
];

// ─── AGRICULTURE (Doña Anna) ─────────────────────────────────────────
// Validated template from real campaign — the original 25-scene matrix.
const agricultureScenes: SceneTemplate[] = [
  { id: "A1", angle: "Lifestyle Ritual", mood: "bright/airy",
    prompt_body: "Bright airy lifestyle photography of {LABEL} stands on a linen-draped breakfast table next to a slice of toasted sourdough drizzled with golden olive oil, a small ceramic dish of flaky sea salt, sprigs of fresh thyme, soft warm morning sunlight streaming through a sheer linen curtain, slow domestic Mediterranean luxury, shallow depth of field." },
  { id: "A2", angle: "Lifestyle Ritual", mood: "bright/airy",
    prompt_body: "Bright airy kitchen photography of {LABEL} stands on a polished marble counter beside a small ceramic bowl of vibrant cherry tomatoes, fresh basil leaves, flaky sea salt, soft natural daylight from a side window, clean Mediterranean styling, shallow depth of field." },
  { id: "A3", angle: "Lifestyle Ritual", mood: "moody/premium",
    prompt_body: "Editorial food photography of {LABEL} on a linen-covered table beside a plate of fresh burrata cheese topped with heirloom tomatoes being drizzled with golden olive oil from above (bottle in foreground), soft window light from the left, shadows falling gently, refined feminine mood." },
  { id: "A4", angle: "Lifestyle Ritual", mood: "bright/airy",
    prompt_body: "Mediterranean lifestyle photography of {LABEL} stands on a whitewashed window sill, olive branches in a small terracotta clay vase beside it, distant sun-drenched hills blurred softly through the open window, warm golden afternoon light." },
  { id: "A5", angle: "Lifestyle Ritual", mood: "minimal/clean",
    prompt_body: "Nordic minimalist kitchen photography of {LABEL} stands on a light oak wooden cutting board next to a perfectly toasted sourdough avocado toast, a small glass of oat milk latte, scandinavian aesthetic, cool soft daylight, very clean composition." },
  { id: "B1", angle: "Chef Authority", mood: "moody/premium",
    prompt_body: "Moody cinematic restaurant kitchen photography of {LABEL} on a chef's pass beside a beautifully plated pan-seared sea bass with herbs, faint steam rising, dark moody backdrop, single warm overhead pendant light, professional fine dining atmosphere." },
  { id: "B2", angle: "Chef Authority", mood: "moody/premium",
    prompt_body: "Moody premium product photography of {LABEL} stands on a brushed stainless steel chef's station next to a small white ceramic ramekin of flaky sea salt, fresh thyme and rosemary sprigs, polished chef's tweezers, low cinematic chiaroscuro lighting, dark moody background." },
  { id: "B3", angle: "Chef Authority", mood: "moody/premium",
    prompt_body: "Editorial dark food photography of {LABEL} beside a tasting flight of three small glass dishes paired with crusty bread chunks on a dark slate board, single warm candle glow, intimate restaurant tasting moment." },
  { id: "B4", angle: "Chef Authority", mood: "moody/premium",
    prompt_body: "Fine dining restaurant photography of {LABEL} stands on a crisp white tablecloth next to a low burning candle, blurred wine glass bokeh in background, warm intimate evening atmosphere, premium hospitality mood." },
  { id: "B5", angle: "Chef Authority", mood: "moody/premium",
    prompt_body: "Cinematic open kitchen photography of {LABEL} held forward by a chef's hand in clean white sleeve toward camera (only hand and lower forearm visible), soft warm directional light, blurred professional kitchen background, presenting moment." },
  { id: "C1", angle: "Studio Hero", mood: "minimal/clean",
    prompt_body: "Premium minimal studio product photography of {LABEL} stands centered on a soft cream backdrop, sculptural hard sidelight from the right casting a long elegant shadow to the left, museum-object styling, lots of negative space." },
  { id: "C2", angle: "Studio Hero", mood: "minimal/clean",
    prompt_body: "Premium minimal studio photography of {LABEL} stands on a warm terracotta plinth, soft gradient cream-to-peach backdrop, museum-object styling, refined sculptural lighting, lots of negative space." },
  { id: "C3", angle: "Studio Hero", mood: "bold/contrasty",
    prompt_body: "Dynamic studio photography of {LABEL} with a frozen splash of liquid mid-pour around its base, dark moody backdrop, dramatic high-contrast lighting, frozen motion, hyperrealistic liquid splash." },
  { id: "C4", angle: "Studio Hero", mood: "minimal/clean",
    prompt_body: "Minimalist studio photography of {LABEL} stands on a raw travertine stone pedestal, single thematic prop laid beside it, cream textured wall backdrop, soft directional light, refined natural luxury." },
  { id: "C5", angle: "Studio Hero", mood: "bright/airy",
    prompt_body: "Top-down flat lay photography of {LABEL} laid horizontally on a cream linen surface beside a small gold spoon, fresh thematic sprig, scattered flaky sea salt, soft even daylight, refined editorial styling." },
  { id: "D1", angle: "Origin Story", mood: "rustic/artisanal",
    prompt_body: "Rustic artisanal landscape photography of {LABEL} stands in the foreground in the product's region of origin at golden hour, characteristic landscape stretching into soft-focus background, warm afternoon light, dust motes in air, terroir storytelling." },
  { id: "D2", angle: "Origin Story", mood: "rustic/artisanal",
    prompt_body: "Rustic harvest photography of {LABEL} stands on a weathered dark wooden harvest crate filled with fresh raw ingredients, late afternoon warm sunlight, farmhouse setting, authentic artisan atmosphere." },
  { id: "D3", angle: "Origin Story", mood: "rustic/artisanal",
    prompt_body: "Rustic regional photography of {LABEL} stands on a weathered stone wall with terracotta roof tiles in the background, sun-bleached farmhouse, warm afternoon light, climbing vines, timeless artisan setting." },
  { id: "D4", angle: "Origin Story", mood: "rustic/artisanal",
    prompt_body: "Rustic harvest photography of {LABEL} sits on rough wood beside two weathered farmer hands cupping a small pile of freshly picked raw ingredients (only hands visible), dirt-marked apron edge, golden harvest light, authentic moment." },
  { id: "D5", angle: "Origin Story", mood: "moody/premium",
    prompt_body: "Atmospheric provenance photography of {LABEL} stands on top of a vintage wooden barrel with the words of the product's origin subtly etched in wood beside it, antique production tools nearby, warm low light, heritage storytelling." },
  { id: "E1", angle: "Wellness", mood: "minimal/clean",
    prompt_body: "Clean wellness lifestyle photography of {LABEL} stands beside a small white ceramic spoon of the product, fresh greens, half a lemon, on a clean white surface, soft even daylight, daily ritual minimalism." },
  { id: "E2", angle: "Wellness", mood: "bright/airy",
    prompt_body: "Bright airy spa-wellness photography of {LABEL} stands on a polished white marble shelf, eucalyptus sprigs in a small clear glass beside it, soft diffused morning light, calming modern wellness aesthetic." },
  { id: "E3", angle: "Wellness", mood: "minimal/clean",
    prompt_body: "Clean wellness photography of {LABEL} stands beside a tall glass of water with cucumber slices, a small green smoothie, a few amber vitamin capsules, on a bright white minimalist countertop, morning health routine." },
  { id: "E4", angle: "Wellness", mood: "bold/contrasty",
    prompt_body: "Dramatic macro pour photography of {LABEL} with a thick stream of the product cascading into a shallow white ceramic bowl below, fresh herbs scattered nearby, dark moody backdrop, high contrast hero shot." },
  { id: "E5", angle: "Wellness", mood: "bright/airy",
    prompt_body: "Calm longevity ritual photography of {LABEL} on a beige linen yoga mat next to a small ceramic mug of herbal tea, an open journal, a single unlit candle, soft morning daylight, mindful wellness mood." },
];

// ─── PERSONAL (Freddy Bremseth) ──────────────────────────────────────
const personalScenes: SceneTemplate[] = [
  { id: "A1", angle: "Authority Speaking", mood: "moody/premium",
    prompt_body: "Editorial speaker photography of {LABEL} on stage with confident gesture, single spotlight, blurred audience, professional credibility." },
  { id: "A2", angle: "Authority Speaking", mood: "minimal/clean",
    prompt_body: "Clean studio photography of {LABEL} with subject mid-presentation gesture, neutral background, professional headshot energy." },
  { id: "A3", angle: "Authority Speaking", mood: "moody/premium",
    prompt_body: "Cinematic interview photography of {LABEL} in a high-end lounge, leather chair, warm tungsten lighting, podcast aesthetic." },
  { id: "A4", angle: "Authority Speaking", mood: "bright/airy",
    prompt_body: "Bright workshop photography of {LABEL} leading a small group, whiteboard behind, natural daylight, expert facilitator mood." },
  { id: "A5", angle: "Authority Speaking", mood: "moody/premium",
    prompt_body: "Editorial portrait of {LABEL} at a desk with confident arms-crossed pose, premium office, soft directional light." },
  { id: "B1", angle: "Behind the Scenes", mood: "bright/airy",
    prompt_body: "Candid behind-the-scenes photography of {LABEL} reviewing strategy on a cafe table, espresso, notebook, morning light." },
  { id: "B2", angle: "Behind the Scenes", mood: "rustic/artisanal",
    prompt_body: "Lifestyle photography of {LABEL} walking a Costa Blanca property with a client, casual but professional, late afternoon sun." },
  { id: "B3", angle: "Behind the Scenes", mood: "bright/airy",
    prompt_body: "Modern home-office photography of {LABEL} on a video call, laptop, light streaming through window, productive remote-work mood." },
  { id: "B4", angle: "Behind the Scenes", mood: "moody/premium",
    prompt_body: "Late-night editorial photography of {LABEL} at a desk with multiple monitors, dim warm light, deep-work atmosphere." },
  { id: "B5", angle: "Behind the Scenes", mood: "bright/airy",
    prompt_body: "Travel photography of {LABEL} arriving at a Spanish airport with luggage, blue sky, motion blur, on-the-go entrepreneur." },
  { id: "C1", angle: "Client Win", mood: "bright/airy",
    prompt_body: "Joyful key-handover photography of {LABEL} smiling with a happy couple in front of their new villa, bright daylight." },
  { id: "C2", angle: "Client Win", mood: "moody/premium",
    prompt_body: "Editorial photography of {LABEL} signing documents with client in an elegant office, low warm light, professional milestone." },
  { id: "C3", angle: "Client Win", mood: "bright/airy",
    prompt_body: "Toast photography of {LABEL} clinking glasses with a client on a sunlit terrace, celebration moment, candid joy." },
  { id: "C4", angle: "Client Win", mood: "moody/premium",
    prompt_body: "Editorial portrait of {LABEL} with a confident handshake silhouette, premium dark backdrop, deal-closed atmosphere." },
  { id: "C5", angle: "Client Win", mood: "bright/airy",
    prompt_body: "Lifestyle photography of {LABEL} with a happy family in their new home, golden hour through window, life-changing moment." },
  { id: "D1", angle: "Insight Quote", mood: "minimal/clean",
    prompt_body: "Minimalist studio photography of {LABEL} with a single thoughtful pose, vast negative space for overlay text, editorial elegance." },
  { id: "D2", angle: "Insight Quote", mood: "moody/premium",
    prompt_body: "Cinematic photography of {LABEL} in soft contemplative profile, dark moody background, perfect for a wisdom quote overlay." },
  { id: "D3", angle: "Insight Quote", mood: "bright/airy",
    prompt_body: "Bright minimalist photography of {LABEL} reading by a window, soft daylight, calm wisdom moment, room for text overlay." },
  { id: "D4", angle: "Insight Quote", mood: "minimal/clean",
    prompt_body: "Clean studio photography of {LABEL} with arms relaxed, neutral wall, deliberate negative space for headline placement." },
  { id: "D5", angle: "Insight Quote", mood: "moody/premium",
    prompt_body: "Editorial photography of {LABEL} writing in a notebook by candlelight, warm intimate scholar atmosphere, room for quote." },
  { id: "E1", angle: "Lifestyle", mood: "bright/airy",
    prompt_body: "Bright lifestyle photography of {LABEL} on a Mediterranean morning run, sea behind, relaxed athletic energy." },
  { id: "E2", angle: "Lifestyle", mood: "moody/premium",
    prompt_body: "Editorial dinner photography of {LABEL} with friends at a long candlelit table, vineyards, refined social atmosphere." },
  { id: "E3", angle: "Lifestyle", mood: "rustic/artisanal",
    prompt_body: "Rustic photography of {LABEL} cooking paella outdoors with friends, terracotta plates, sunset glow, authentic celebration." },
  { id: "E4", angle: "Lifestyle", mood: "bright/airy",
    prompt_body: "Travel photography of {LABEL} on a sunny terrace with a coffee and laptop, Mediterranean view, work-from-anywhere mood." },
  { id: "E5", angle: "Lifestyle", mood: "moody/premium",
    prompt_body: "Cinematic photography of {LABEL} driving along a coastal highway in a convertible at golden hour, Costa Blanca freedom." },
];

// ─── MUSIC (Neural Beat) ─────────────────────────────────────────────
const musicScenes: SceneTemplate[] = [
  { id: "A1", angle: "Studio Production", mood: "moody/premium",
    prompt_body: "Editorial studio photography of {LABEL} with vintage analog synth, glowing knobs, dim purple light, producer atmosphere." },
  { id: "A2", angle: "Studio Production", mood: "bold/contrasty",
    prompt_body: "Dramatic photography of {LABEL} with hands on a mixing console, neon RGB glow, high contrast techno aesthetic." },
  { id: "A3", angle: "Studio Production", mood: "minimal/clean",
    prompt_body: "Minimalist studio photography of {LABEL} with a single MIDI controller, clean white desk, soft directional light, focused production." },
  { id: "A4", angle: "Studio Production", mood: "moody/premium",
    prompt_body: "Cinematic close-up of {LABEL} with headphones reflecting waveform glow, dark studio background, immersive listening moment." },
  { id: "A5", angle: "Studio Production", mood: "bold/contrasty",
    prompt_body: "Dynamic photography of {LABEL} with monitor speakers and DAW screen lit up, dramatic lighting, late-night session vibe." },
  { id: "B1", angle: "Performance Energy", mood: "bold/contrasty",
    prompt_body: "Live performance photography of {LABEL} on stage with crowd silhouettes, laser lights, fog, festival energy." },
  { id: "B2", angle: "Performance Energy", mood: "moody/premium",
    prompt_body: "Cinematic DJ booth photography of {LABEL} with hands raised, club lights, premium underground venue atmosphere." },
  { id: "B3", angle: "Performance Energy", mood: "bold/contrasty",
    prompt_body: "Wide stage photography of {LABEL} at a sunset open-air festival, crowd dancing, golden warm light, euphoric peak." },
  { id: "B4", angle: "Performance Energy", mood: "moody/premium",
    prompt_body: "Backstage photography of {LABEL} prepping equipment, dim warm light, anticipation moment before performance." },
  { id: "B5", angle: "Performance Energy", mood: "bold/contrasty",
    prompt_body: "Photography of {LABEL} mid-drop with confetti and lasers, peak-time energy, electric atmosphere." },
  { id: "C1", angle: "Visual Beats", mood: "bold/contrasty",
    prompt_body: "Abstract studio photography of {LABEL} with audio waveform projection on backdrop, dark contrasty composition, music-as-art." },
  { id: "C2", angle: "Visual Beats", mood: "vibrant/playful",
    prompt_body: "Vibrant pop photography of {LABEL} with prismatic light beams refracting around it, bold colorful music aesthetic." },
  { id: "C3", angle: "Visual Beats", mood: "minimal/clean",
    prompt_body: "Minimalist photography of {LABEL} with a single sound-wave shadow on a clean wall, conceptual elegance." },
  { id: "C4", angle: "Visual Beats", mood: "moody/premium",
    prompt_body: "Editorial photography of {LABEL} with vinyl records floating around it on dark backdrop, premium music object styling." },
  { id: "C5", angle: "Visual Beats", mood: "bold/contrasty",
    prompt_body: "Dynamic photography of {LABEL} with frozen liquid splash mid-motion, dark contrasty backdrop, energy made visible." },
  { id: "D1", angle: "Lifestyle Vibe", mood: "moody/premium",
    prompt_body: "Cinematic night photography of {LABEL} in a candlelit listening room, leather couch, vinyl player, premium audiophile mood." },
  { id: "D2", angle: "Lifestyle Vibe", mood: "bright/airy",
    prompt_body: "Lifestyle photography of {LABEL} on a sunny terrace with someone wearing premium headphones, beach view, summer EDM mood." },
  { id: "D3", angle: "Lifestyle Vibe", mood: "moody/premium",
    prompt_body: "Editorial nightclub VIP photography of {LABEL} on a marble bar, premium cocktail, dim atmospheric light, exclusive scene." },
  { id: "D4", angle: "Lifestyle Vibe", mood: "bold/contrasty",
    prompt_body: "Photography of {LABEL} with city skyline at night through floor-to-ceiling windows, urban DJ apartment vibe." },
  { id: "D5", angle: "Lifestyle Vibe", mood: "vibrant/playful",
    prompt_body: "Pool party photography of {LABEL} with floats, palm trees, sunset, ibiza-style hedonism, vibrant energy." },
  { id: "E1", angle: "Track Aesthetic", mood: "bold/contrasty",
    prompt_body: "Album-cover-style photography of {LABEL} with bold typographic composition, striking color palette, art-direction quality." },
  { id: "E2", angle: "Track Aesthetic", mood: "minimal/clean",
    prompt_body: "Minimalist photography of {LABEL} like a high-end vinyl release, embossed details, premium music brand styling." },
  { id: "E3", angle: "Track Aesthetic", mood: "moody/premium",
    prompt_body: "Editorial photography of {LABEL} as if it's a limited-edition release box, foil details, dark backdrop, collector aesthetic." },
  { id: "E4", angle: "Track Aesthetic", mood: "bold/contrasty",
    prompt_body: "Photography of {LABEL} with abstract spectrum-analyzer shapes around it, like a music visualizer frozen in time." },
  { id: "E5", angle: "Track Aesthetic", mood: "vibrant/playful",
    prompt_body: "Bright pop photography of {LABEL} with playful retro music symbols, cassette tapes, neon colors, nostalgic-futuristic vibe." },
];

// ─── TOURISM ─────────────────────────────────────────────────────────
const tourismScenes: SceneTemplate[] = [
  { id: "A1", angle: "Destination Hero", mood: "bright/airy",
    prompt_body: "Wide landscape photography of {LABEL} at a stunning Mediterranean coast at golden hour, dreamy escape feel." },
  { id: "A2", angle: "Destination Hero", mood: "bold/contrasty",
    prompt_body: "Aerial drone photography of {LABEL} with crystal turquoise waters and white sand below, dramatic perspective." },
  { id: "A3", angle: "Destination Hero", mood: "moody/premium",
    prompt_body: "Cinematic photography of {LABEL} at sunset overlooking historic Spanish village, cobblestone, twilight glow." },
  { id: "A4", angle: "Destination Hero", mood: "bright/airy",
    prompt_body: "Photography of {LABEL} with infinity pool merging into Mediterranean horizon, palm trees, midday brilliance." },
  { id: "A5", angle: "Destination Hero", mood: "rustic/artisanal",
    prompt_body: "Photography of {LABEL} in an ancient olive grove, terraced hills, golden light, timeless terroir." },
  { id: "B1", angle: "Experience", mood: "bright/airy",
    prompt_body: "Lifestyle photography of {LABEL} with guests sipping wine on a sunlit vineyard terrace, joyful escape." },
  { id: "B2", angle: "Experience", mood: "moody/premium",
    prompt_body: "Editorial photography of {LABEL} with multi-course tasting menu being served, candlelit fine dining." },
  { id: "B3", angle: "Experience", mood: "rustic/artisanal",
    prompt_body: "Photography of {LABEL} with hands-on cooking class, fresh local ingredients, rustic chef-led moment." },
  { id: "B4", angle: "Experience", mood: "bright/airy",
    prompt_body: "Photography of {LABEL} with sailboat on calm Mediterranean, swimsuits, summer escape mood." },
  { id: "B5", angle: "Experience", mood: "moody/premium",
    prompt_body: "Spa photography of {LABEL} with hot stones, eucalyptus, dim sanctuary lighting, wellness retreat." },
  { id: "C1", angle: "Accommodation", mood: "minimal/clean",
    prompt_body: "Architectural photography of {LABEL} with minimalist boutique villa interior, large windows, premium calm." },
  { id: "C2", angle: "Accommodation", mood: "moody/premium",
    prompt_body: "Editorial photography of {LABEL} with king-size bed, candlelit, luxurious linens, suite atmosphere." },
  { id: "C3", angle: "Accommodation", mood: "bright/airy",
    prompt_body: "Bright photography of {LABEL} with breakfast spread on a sunlit terrace, fresh fruit, coffee, sea view." },
  { id: "C4", angle: "Accommodation", mood: "rustic/artisanal",
    prompt_body: "Photography of {LABEL} with rustic stone-walled bedroom, terracotta floor, warm afternoon light." },
  { id: "C5", angle: "Accommodation", mood: "minimal/clean",
    prompt_body: "Photography of {LABEL} with bathtub overlooking ocean through floor-to-ceiling windows, ultimate luxury." },
  { id: "D1", angle: "Local Story", mood: "rustic/artisanal",
    prompt_body: "Photography of {LABEL} with local Spanish farmer harvesting produce, authentic regional connection." },
  { id: "D2", angle: "Local Story", mood: "rustic/artisanal",
    prompt_body: "Photography of {LABEL} in a traditional weekly market with vibrant produce stalls, cultural immersion." },
  { id: "D3", angle: "Local Story", mood: "moody/premium",
    prompt_body: "Editorial photography of {LABEL} with master craftsman at work, hands shaping clay, heritage trade story." },
  { id: "D4", angle: "Local Story", mood: "bright/airy",
    prompt_body: "Photography of {LABEL} with festive Spanish village celebration, dancers, bright Mediterranean joy." },
  { id: "D5", angle: "Local Story", mood: "moody/premium",
    prompt_body: "Cinematic photography of {LABEL} with old fisherman returning at dusk, harbor lights, slow-life rhythm." },
  { id: "E1", angle: "Wellness Escape", mood: "minimal/clean",
    prompt_body: "Photography of {LABEL} with morning yoga on terrace overlooking sea, calm mindfulness moment." },
  { id: "E2", angle: "Wellness Escape", mood: "bright/airy",
    prompt_body: "Photography of {LABEL} with hands receiving spa treatment, soft natural light, premium relaxation." },
  { id: "E3", angle: "Wellness Escape", mood: "moody/premium",
    prompt_body: "Editorial photography of {LABEL} with cold-plunge pool surrounded by greenery, longevity ritual aesthetic." },
  { id: "E4", angle: "Wellness Escape", mood: "rustic/artisanal",
    prompt_body: "Photography of {LABEL} with hiking trail through Spanish hills, vista, restorative nature moment." },
  { id: "E5", angle: "Wellness Escape", mood: "bright/airy",
    prompt_body: "Photography of {LABEL} with healthy Mediterranean breakfast bowl, fresh fruit, ceramic, slow ritual." },
];

// ─── ECOMMERCE (generic fallback for product brands) ─────────────────
const ecommerceScenes: SceneTemplate[] = agricultureScenes;  // Reuse agriculture template — works for most consumer products

// ─── Registry ────────────────────────────────────────────────────────
const TEMPLATES: Record<BrandTemplateKey, BrandTemplate> = {
  real_estate: {
    key: "real_estate",
    angles: ["Lifestyle Living", "Location Hero", "Architectural Detail", "Investment Story", "Family Story"],
    scenes: realEstateScenes,
    default_moods: ["bright/airy", "moody/premium", "minimal/clean"],
    caption_style_hint: "Aspirational, lifestyle-first. Lead with the feeling of living there. Mention location subtly. Strong CTA.",
  },
  saas: {
    key: "saas",
    angles: ["Pain Point", "Demo", "Social Proof", "Hero Feature", "ROI Story"],
    scenes: saasScenes,
    default_moods: ["minimal/clean", "bold/contrasty", "moody/premium"],
    caption_style_hint: "Direct, benefit-driven. Quantify ROI/time saved. Address objections. Demo CTA.",
  },
  agriculture: {
    key: "agriculture",
    angles: ["Lifestyle Ritual", "Chef Authority", "Studio Hero", "Origin Story", "Wellness"],
    scenes: agricultureScenes,
    default_moods: ["bright/airy", "moody/premium", "rustic/artisanal"],
    caption_style_hint: "Sensory, premium, terroir-focused. Reference origin and craftsmanship. Subtle CTA.",
  },
  personal: {
    key: "personal",
    angles: ["Authority Speaking", "Behind the Scenes", "Client Win", "Insight Quote", "Lifestyle"],
    scenes: personalScenes,
    default_moods: ["moody/premium", "bright/airy", "minimal/clean"],
    caption_style_hint: "First-person, authentic, expert-positioning. Mix wisdom with relatability.",
  },
  music: {
    key: "music",
    angles: ["Studio Production", "Performance Energy", "Visual Beats", "Lifestyle Vibe", "Track Aesthetic"],
    scenes: musicScenes,
    default_moods: ["bold/contrasty", "moody/premium", "vibrant/playful"],
    caption_style_hint: "Energetic, evocative, hint at the sound. Track titles. Drop dates. Listen-now CTA.",
  },
  tourism: {
    key: "tourism",
    angles: ["Destination Hero", "Experience", "Accommodation", "Local Story", "Wellness Escape"],
    scenes: tourismScenes,
    default_moods: ["bright/airy", "moody/premium", "rustic/artisanal"],
    caption_style_hint: "Escapist, evocative, sensory. Lead with the feeling. Book-now CTA.",
  },
  ecommerce: {
    key: "ecommerce",
    angles: ["Lifestyle Ritual", "Chef Authority", "Studio Hero", "Origin Story", "Wellness"],
    scenes: ecommerceScenes,
    default_moods: ["bright/airy", "minimal/clean", "moody/premium"],
    caption_style_hint: "Benefit-led, sensory. Strong CTA with offer.",
  },
};

export function getBrandTemplate(brandType: string): BrandTemplate {
  // Map "other" or unknown to ecommerce as safe fallback
  const key = (brandType in TEMPLATES ? brandType : "ecommerce") as BrandTemplateKey;
  return TEMPLATES[key];
}

export function listBrandTemplateKeys(): BrandTemplateKey[] {
  return Object.keys(TEMPLATES) as BrandTemplateKey[];
}
