"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import {
  AlertTriangle, ArrowRight, Banknote, CalendarDays, CheckCircle2, CircleDollarSign,
  Flag, Gauge, KeyRound, Loader2, RefreshCw, RotateCcw, Save, ShieldCheck,
  Target, TrendingUp, Users, type LucideIcon,
} from "lucide-react";
import { Button } from "@/components/ui/button";

type Scope = "all" | "zeneco" | "soleada" | "pinosoecolife" | "keyholding";
type GoalStatus = "UNSET" | "ACHIEVED" | "ON_TRACK" | "AT_RISK" | "BEHIND";
type Metric = { id: "commission" | "deals" | "keyholding-mrr" | "keyholding-contracts" | "recovery"; label: string; unit: "EUR" | "COUNT"; target: number | null; actual: number; projected: number | null; progressPercent: number | null; status: GoalStatus; detail: string };
type Plan = { id: string; priority: "CRITICAL" | "HIGH" | "MEDIUM"; title: string; description: string; targetThisWeek: number | null; unit: "EUR" | "COUNT" | null; href: string };
type Scorecard = {
  generatedAt: string; configured: boolean; headline: string;
  config: { commissionTargetEur: number | null; closedDealsTarget: number | null; keyholdingMrrTargetEur: number | null; keyholdingContractsTarget: number | null; recoveredLeadsTarget: number | null; notes: string | null; updatedAt: string | null };
  period: { elapsedPercent: number; daysRemaining: number; weeksRemaining: number };
  summary: { earnedCommission: number; collectedCommission: number; forecast30Commission: number; wonDeals: number; currentKeyholdingMrr: number; newKeyholdingContracts: number; recoveredLeads: number; dataQualityScore: number };
  metrics: Metric[]; weeklyPlan: Plan[]; warnings: string[]; assumptions: string[];
};
type FormState = { commissionTargetEur: string; closedDealsTarget: string; keyholdingMrrTargetEur: string; keyholdingContractsTarget: string; recoveredLeadsTarget: string; notes: string };

const scopes: Array<{ id: Scope; label: string }> = [
  { id: "all", label: "Alle eiendomsbrands" }, { id: "zeneco", label: "Zen Eco Homes" },
  { id: "soleada", label: "Soleada.no" }, { id: "pinosoecolife", label: "Pinoso EcoLife" }, { id: "keyholding", label: "Keyholding" },
];
const icons: Record<Metric["id"], LucideIcon> = { commission: CircleDollarSign, deals: Users, "keyholding-mrr": KeyRound, "keyholding-contracts": ShieldCheck, recovery: RotateCcw };
const blank: FormState = { commissionTargetEur: "", closedDealsTarget: "", keyholdingMrrTargetEur: "", keyholdingContractsTarget: "", recoveredLeadsTarget: "", notes: "" };

function currentMonth() { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`; }
function money(v: number) { return new Intl.NumberFormat("nb-NO", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(v || 0); }
function display(v: number | null, unit: "EUR" | "COUNT" | null) { return v === null ? "—" : unit === "EUR" ? money(v) : new Intl.NumberFormat("nb-NO", { maximumFractionDigits: 1 }).format(v); }
function badge(value: GoalStatus | Plan["priority"]) {
  if (["ACHIEVED", "ON_TRACK"].includes(value)) return "border-emerald-500/35 bg-emerald-500/10 text-emerald-200";
  if (["CRITICAL", "BEHIND"].includes(value)) return "border-red-500/35 bg-red-500/10 text-red-200";
  if (["HIGH", "AT_RISK"].includes(value)) return "border-amber-500/35 bg-amber-500/10 text-amber-200";
  return "border-slate-600 bg-slate-800 text-slate-300";
}
function formFrom(data: Scorecard): FormState { const c = data.config; return { commissionTargetEur: c.commissionTargetEur?.toString() || "", closedDealsTarget: c.closedDealsTarget?.toString() || "", keyholdingMrrTargetEur: c.keyholdingMrrTargetEur?.toString() || "", keyholdingContractsTarget: c.keyholdingContractsTarget?.toString() || "", recoveredLeadsTarget: c.recoveredLeadsTarget?.toString() || "", notes: c.notes || "" }; }

export default function RevenueGoalsPage() {
  const [scope, setScope] = useState<Scope>("all"); const [month, setMonth] = useState(currentMonth());
  const [data, setData] = useState<Scorecard | null>(null); const [form, setForm] = useState<FormState>(blank);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [saved, setSaved] = useState("");
  async function load() { setLoading(true); setError(""); try { const r = await fetch(`/api/revenue/goals?scope=${scope}&month=${month}`, { cache: "no-store" }); const b = await r.json().catch(() => null); if (!r.ok) throw new Error(b?.error || "Kunne ikke hente mål."); setData(b.scorecard); setForm(formFrom(b.scorecard)); } catch (e) { setError(e instanceof Error ? e.message : "Kunne ikke hente mål."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [scope, month]);
  async function save() { setSaving(true); setError(""); setSaved(""); try { const r = await fetch("/api/revenue/goals", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ scope, month, ...form }) }); const b = await r.json().catch(() => null); if (!r.ok) throw new Error(b?.error || "Kunne ikke lagre målene."); setSaved("Målene er lagret og ukeplanen er oppdatert."); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Kunne ikke lagre målene."); } finally { setSaving(false); } }
  const cards: Array<[string, string | number, LucideIcon]> = data ? [["Opptjent provisjon", money(data.summary.earnedCommission), CircleDollarSign], ["Innbetalt provisjon", money(data.summary.collectedCommission), Banknote], ["30-dagers prognose", money(data.summary.forecast30Commission), TrendingUp], ["Vunne salg", data.summary.wonDeals, Users], ["Keyholding MRR", money(data.summary.currentKeyholdingMrr), KeyRound], ["Nye Keyholding-avtaler", data.summary.newKeyholdingContracts, ShieldCheck], ["Reaktiverte leads", data.summary.recoveredLeads, RotateCcw], ["Datakvalitet", `${data.summary.dataQualityScore} %`, Gauge]] : [];
  const fields: Array<[keyof FormState, string]> = [["commissionTargetEur", "Provisjon (€)"], ["closedDealsTarget", "Vunne salg"], ["keyholdingMrrTargetEur", "Keyholding MRR (€)"], ["keyholdingContractsTarget", "Nye Keyholding-avtaler"], ["recoveredLeadsTarget", "Reaktiverte leads"]];

  return <div className="mx-auto max-w-7xl space-y-6">
    <header className="flex flex-col gap-4 rounded-2xl border border-slate-700/70 bg-slate-900/70 p-6 lg:flex-row lg:items-center lg:justify-between"><div><div className="mb-2 flex items-center gap-2 text-sm font-medium text-emerald-300"><Flag size={18} /> Freddy Revenue OS</div><h1 className="text-3xl font-bold text-white">Revenue Goals & Weekly Plan</h1><p className="mt-2 max-w-3xl text-sm text-slate-400">Sett egne månedsmål og få en ukeplan basert på faktiske resultater, prognose og gjenværende gap.</p></div><div className="flex flex-wrap gap-2"><Button asChild variant="outline"><Link href="/revenue-command">Command Center</Link></Button><Button asChild variant="outline"><Link href="/forecast">Forecast</Link></Button><Button onClick={load} disabled={loading}>{loading ? <Loader2 size={16} className="mr-2 animate-spin" /> : <RefreshCw size={16} className="mr-2" />}Oppdater</Button></div></header>
    <div className="flex gap-3 rounded-xl border border-emerald-500/25 bg-emerald-500/5 p-4 text-sm text-slate-300"><ShieldCheck size={20} className="shrink-0 text-emerald-300" /><div><strong className="text-white">Du eier målene:</strong> systemet lager aldri mål automatisk og sender eller endrer ingenting.</div></div>
    <section className="grid gap-3 md:grid-cols-2"><label className="rounded-xl border border-slate-700 bg-slate-900/60 p-4 text-sm"><span className="mb-2 block text-xs uppercase text-slate-500">Måned</span><input type="month" value={month} onChange={(e) => setMonth(e.target.value)} className="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white" /></label><label className="rounded-xl border border-slate-700 bg-slate-900/60 p-4 text-sm"><span className="mb-2 block text-xs uppercase text-slate-500">Scope</span><select value={scope} onChange={(e) => setScope(e.target.value as Scope)} className="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white">{scopes.map((s) => <option key={s.id} value={s.id}>{s.label}</option>)}</select></label></section>
    {error && <div className="flex gap-2 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-200"><AlertTriangle size={18} />{error}</div>}{saved && <div className="flex gap-2 rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-4 text-sm text-emerald-100"><CheckCircle2 size={18} />{saved}</div>}{data?.warnings?.length ? <div className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm text-amber-100"><strong>Datavarsler:</strong> {data.warnings.join(" · ")}</div> : null}
    {loading && !data ? <div className="flex min-h-52 items-center justify-center rounded-xl border border-slate-700 bg-slate-900/50 text-slate-400"><Loader2 size={20} className="mr-2 animate-spin" />Bygger målbildet …</div> : data ? <>
      <section className="rounded-2xl border border-emerald-500/25 bg-emerald-500/5 p-6"><p className="text-xs uppercase tracking-[0.2em] text-emerald-300">Anbefalt fokus</p><h2 className="mt-2 text-2xl font-semibold text-white">{data.headline}</h2><div className="mt-3 flex flex-wrap gap-4 text-xs text-slate-400"><span><CalendarDays size={14} className="mr-1 inline" />{data.period.daysRemaining} dager igjen</span><span>{data.period.weeksRemaining} uker igjen</span><span>{data.period.elapsedPercent} % av måneden gått</span></div></section>
      <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label, value, Icon]) => <article key={label} className="rounded-xl border border-slate-700/70 bg-slate-900/60 p-4"><Icon size={20} className="text-emerald-300" /><p className="mt-3 text-[11px] uppercase text-slate-500">{label}</p><strong className="mt-1 block text-2xl text-white">{value}</strong></article>)}</section>
      <section className="rounded-2xl border border-slate-700/70 bg-slate-900/60 p-6"><h2 className="text-xl font-semibold text-white">Dine mål for perioden</h2><p className="mt-1 text-sm text-slate-400">La felt stå tomme når de ikke skal måles.</p><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-5">{fields.map(([key, label]) => <label key={key} className="text-sm text-slate-300"><span className="mb-2 block text-xs text-slate-500">{label}</span><input type="number" min="0" value={form[key]} onChange={(e) => setForm((f) => ({ ...f, [key]: e.target.value }))} className="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white" /></label>)}</div><textarea value={form.notes} onChange={(e) => setForm((f) => ({ ...f, notes: e.target.value }))} maxLength={1000} rows={3} className="mt-4 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white" placeholder="Månedsnotat" /><div className="mt-4 flex justify-end"><Button onClick={save} disabled={saving}>{saving ? <Loader2 size={16} className="mr-2 animate-spin" /> : <Save size={16} className="mr-2" />}Lagre mål</Button></div></section>
      <section><h2 className="mb-3 text-xl font-semibold text-white">Faktisk resultat mot mål</h2><div className="grid gap-4 lg:grid-cols-2">{data.metrics.map((m) => { const Icon = icons[m.id]; return <article key={m.id} className="rounded-xl border border-slate-700/70 bg-slate-900/60 p-5"><div className="flex justify-between gap-3"><div className="flex gap-3"><Icon size={20} className="text-emerald-300" /><div><h3 className="font-semibold text-white">{m.label}</h3><p className="mt-1 text-xs text-slate-500">{m.detail}</p></div></div><span className={`h-fit rounded-full border px-2.5 py-1 text-[10px] font-semibold ${badge(m.status)}`}>{m.status}</span></div><div className="mt-5 grid grid-cols-3 gap-3 text-sm"><div><p className="text-xs text-slate-500">Faktisk</p><strong className="text-white">{display(m.actual, m.unit)}</strong></div><div><p className="text-xs text-slate-500">Mål</p><strong className="text-white">{display(m.target, m.unit)}</strong></div><div><p className="text-xs text-slate-500">Projisert</p><strong className="text-white">{display(m.projected, m.unit)}</strong></div></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full bg-emerald-500" style={{ width: `${Math.min(100, m.progressPercent || 0)}%` }} /></div></article>; })}</div></section>
      <section><h2 className="mb-3 text-xl font-semibold text-white">Ukeplan</h2><div className="space-y-3">{data.weeklyPlan.map((p, i) => <article key={p.id} className="rounded-xl border border-slate-700/70 bg-slate-900/60 p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex gap-2"><span className="font-bold text-slate-500">#{i + 1}</span><span className={`rounded-full border px-2.5 py-1 text-[10px] font-semibold ${badge(p.priority)}`}>{p.priority}</span></div><h3 className="mt-3 text-lg font-semibold text-white">{p.title}</h3><p className="mt-1 text-sm text-slate-400">{p.description}</p></div><div className="flex items-center gap-3">{p.targetThisWeek !== null && <strong className="text-white">{display(p.targetThisWeek, p.unit)}</strong>}<Button asChild size="sm"><Link href={p.href}>Åpne <ArrowRight size={14} className="ml-1" /></Link></Button></div></div></article>)}</div></section>
      <section className="rounded-xl border border-slate-700/70 bg-slate-900/50 p-5"><h2 className="font-semibold text-white">Forutsetninger</h2><ul className="mt-3 space-y-2 text-sm text-slate-400">{data.assumptions.map((a) => <li key={a} className="flex gap-2"><Target size={15} className="mt-0.5 shrink-0 text-emerald-300" />{a}</li>)}</ul></section>
    </> : null}
  </div>;
}
