"use client";

import { useEffect, useMemo, useState } from "react";

type BookRow={bookId:string;slug:string;title:string;language:string|null;likelyLanguage:string|null;seriesTitle:unknown;seriesSlug:string|null;seriesNumber:number|null;hasCover:boolean;hasSample:boolean;hasAsin:boolean;hasWork:boolean;workVerified:boolean;issues:string[];score:number};
type Payload={generatedAt:string;summary:{totalBooks:number;healthScore:number;missingCover:number;missingSample:number;missingAsin:number;missingWork:number;duplicateSeriesNumber:number;languageReview:number;cleanBooks:number};books:BookRow[]};

const LABELS:Record<string,string>={missing_cover:"Mangler cover",missing_sample:"Mangler sample",missing_asin:"Mangler ASIN",missing_work_link:"Mangler work-link",duplicate_series_number:"Serienummer-kollisjon",language_review:"Språk må vurderes"};

function Metric({label,value,sub}:{label:string;value:string|number;sub?:string}){return <div style={{border:"1px solid #e2e8f0",borderRadius:12,padding:14,background:"white"}}><div style={{fontSize:12,color:"#64748b",fontWeight:800}}>{label}</div><div style={{fontSize:26,fontWeight:900,marginTop:3}}>{value}</div>{sub&&<div style={{fontSize:11,color:"#94a3b8",marginTop:3}}>{sub}</div>}</div>}
function titleText(v:unknown){if(typeof v==="string")return v;if(v&&typeof v==="object"){const o=v as Record<string,unknown>;return String(o.en??o.no??o.es??Object.values(o)[0]??"")}return ""}

export default function CatalogQualityPage(){
 const[data,setData]=useState<Payload|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[filter,setFilter]=useState("all");const[analyzing,setAnalyzing]=useState(false);
 const load=async()=>{setLoading(true);setError(null);try{const r=await fetch("/api/book-growth/catalog-quality",{cache:"no-store",credentials:"same-origin"});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error||`Load failed (${r.status})`);setData(b)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}};
 const analyze=async()=>{setAnalyzing(true);setError(null);try{const r=await fetch("/api/book-growth/analyze/catalog-quality",{method:"POST",credentials:"same-origin"});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error||`Analyze failed (${r.status})`);await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setAnalyzing(false)}};
 useEffect(()=>{void load()},[]);
 const rows=useMemo(()=>filter==="all"?(data?.books??[]):(data?.books??[]).filter(b=>b.issues.includes(filter)),[data,filter]);const s=data?.summary;
 return <div style={{maxWidth:1500,margin:"0 auto",padding:24,fontFamily:"system-ui,sans-serif"}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><h1 style={{margin:0,fontSize:27}}>Catalog Quality</h1><p style={{margin:"6px 0 0",color:"#64748b"}}>Kataloghelse, metadata-avvik og reviewbare forbedringer.</p></div><div style={{display:"flex",gap:8}}><button onClick={()=>void load()} disabled={loading} style={{border:"1px solid #cbd5e1",borderRadius:9,padding:"9px 13px",background:"white",fontWeight:800}}>Oppdater</button><button onClick={()=>void analyze()} disabled={analyzing} style={{border:0,borderRadius:9,padding:"9px 13px",background:"#0f172a",color:"white",fontWeight:800}}>{analyzing?"Analyserer…":"Lag review-forslag"}</button></div></div>
  {error&&<div style={{marginTop:16,padding:12,borderRadius:8,background:"#fef2f2",color:"#b91c1c"}}>⛔ {error}</div>}
  {s&&<><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10,marginTop:18}}><Metric label="Catalog health" value={`${s.healthScore}/100`} sub={`${s.cleanBooks}/${s.totalBooks} uten flagg`}/><Metric label="Mangler ASIN" value={s.missingAsin}/><Metric label="Mangler cover" value={s.missingCover}/><Metric label="Mangler sample" value={s.missingSample}/><Metric label="Work-link" value={s.missingWork} sub="mangler"/><Metric label="Serienummer" value={s.duplicateSeriesNumber} sub="bøker i kollisjon"/><Metric label="Språk-review" value={s.languageReview} sub="heuristisk, ikke auto-fix"/></div>
  <section style={{marginTop:18,padding:14,border:"1px solid #e2e8f0",borderRadius:12,background:"#f8fafc"}}><b>Regel:</b><span style={{marginLeft:6,color:"#475569",fontSize:13}}>Dashboardet identifiserer avvik. Språkdeteksjon er bare et review-signal. Ingen katalogfelt endres automatisk.</span></section>
  <div style={{display:"flex",gap:7,flexWrap:"wrap",marginTop:16}}>{["all","missing_asin","missing_cover","missing_sample","missing_work_link","duplicate_series_number","language_review"].map(f=><button key={f} onClick={()=>setFilter(f)} style={{border:"1px solid #cbd5e1",borderRadius:999,padding:"6px 10px",background:filter===f?"#0f172a":"white",color:filter===f?"white":"#334155",fontSize:12,fontWeight:700}}>{f==="all"?`Alle (${data?.books.length??0})`:LABELS[f]}</button>)}</div>
  <div style={{overflowX:"auto",marginTop:12,border:"1px solid #e2e8f0",borderRadius:12,background:"white"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr style={{background:"#f8fafc",textAlign:"left"}}>{["Score","Bok","Serie","Språk","ASIN","Cover","Sample","Work","Avvik"].map(h=><th key={h} style={{padding:9,borderBottom:"1px solid #e2e8f0"}}>{h}</th>)}</tr></thead><tbody>{rows.map(b=><tr key={b.bookId}><td style={{padding:9,borderBottom:"1px solid #f1f5f9",fontWeight:900}}>{b.score}</td><td style={{padding:9,borderBottom:"1px solid #f1f5f9",minWidth:220}}><b>{b.title}</b><div style={{color:"#94a3b8"}}>{b.slug}</div></td><td style={{padding:9,borderBottom:"1px solid #f1f5f9"}}>{titleText(b.seriesTitle)||"Standalone"}{b.seriesNumber!=null?` · #${b.seriesNumber}`:""}</td><td style={{padding:9,borderBottom:"1px solid #f1f5f9"}}>{b.language??"—"}{b.issues.includes("language_review")?<div style={{color:"#b45309"}}>review → {b.likelyLanguage}</div>:null}</td><td style={{padding:9,borderBottom:"1px solid #f1f5f9"}}>{b.hasAsin?"✓":"—"}</td><td style={{padding:9,borderBottom:"1px solid #f1f5f9"}}>{b.hasCover?"✓":"—"}</td><td style={{padding:9,borderBottom:"1px solid #f1f5f9"}}>{b.hasSample?"✓":"—"}</td><td style={{padding:9,borderBottom:"1px solid #f1f5f9"}}>{b.hasWork?(b.workVerified?"✓ verified":"linked"):"—"}</td><td style={{padding:9,borderBottom:"1px solid #f1f5f9",minWidth:230}}>{b.issues.length?b.issues.map(x=><span key={x} style={{display:"inline-block",margin:"2px 4px 2px 0",padding:"3px 6px",borderRadius:999,background:"#fff7ed",color:"#9a3412"}}>{LABELS[x]??x}</span>):<span style={{color:"#166534",fontWeight:800}}>Clean</span>}</td></tr>)}</tbody></table></div></>}
 </div>
}
