"use client";
import { useEffect, useState } from "react";

type Candidate={id:string;candidate_type:string;storage_path:string|null;confidence:number|null;match_type:string|null;status:string;evidence:Record<string,unknown>;book?:{title:string;language:string;ebook_file_path:string|null}|null};
type Payload={summary:{total:number;pendingLinks:number;duplicateGroups:number;approved:number;applied:number};candidates:Candidate[]};

export default function FileReconciliationPage(){
 const[data,setData]=useState<Payload|null>(null),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null);
 const load=async()=>{const r=await fetch("/api/book-growth/file-reconciliation",{cache:"no-store",credentials:"same-origin"});const b=await r.json();if(!r.ok)throw new Error(b.error||`HTTP ${r.status}`);setData(b)};
 useEffect(()=>{void load().catch(e=>setError(String(e)))},[]);
 const act=async(action:string,candidateId?:string)=>{setBusy(candidateId||action);setError(null);setMessage(null);try{const r=await fetch("/api/book-growth/file-reconciliation",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,candidateId})});const b=await r.json();if(!r.ok)throw new Error(b.error||`HTTP ${r.status}`);setMessage(action==="scan"?`Skannet ${b.scannedFiles} filer og fant ${b.proposedLinks} koblingsforslag.`:`Forslaget er nå ${b.status||b.result?.candidate_status}.`);await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(null)}};
 const s=data?.summary;
 return <div style={{maxWidth:1500,margin:"0 auto",padding:24,fontFamily:"system-ui,sans-serif"}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><h1 style={{margin:0}}>Book File Reconciliation</h1><p style={{color:"#64748b"}}>Koble eksisterende private bokfiler til riktig kanonisk utgave – alltid med godkjenning.</p></div><button onClick={()=>void act("scan")} disabled={busy!==null} style={{padding:"10px 14px",border:0,borderRadius:9,background:"#0f172a",color:"white",fontWeight:900}}>Skann book-ebooks</button></div>
  {error&&<div style={{marginTop:12,padding:12,background:"#fef2f2",color:"#b91c1c",borderRadius:8}}>⛔ {error}</div>}{message&&<div style={{marginTop:12,padding:12,background:"#ecfdf5",color:"#047857",borderRadius:8}}>✓ {message}</div>}
  {s&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10,marginTop:16}}>{[["Forslag",s.total],["Filkoblinger",s.pendingLinks],["Dublettgrupper",s.duplicateGroups],["Godkjent",s.approved],["Utført",s.applied]].map(([l,v])=><div key={String(l)} style={{background:"white",padding:14,border:"1px solid #cbd5e1",borderRadius:12}}><div style={{fontSize:12,color:"#64748b",fontWeight:800}}>{l}</div><div style={{fontSize:26,fontWeight:900}}>{v}</div></div>)}</div>}
  <section style={{marginTop:16,padding:12,background:"#f8fafc",border:"1px solid #cbd5e1",borderRadius:10,fontSize:13}}><b>Sikker regel:</b> Skanningen oppretter bare forslag. Godkjenn og Utfør er separate handlinger. Dublettfiler slettes aldri her.</section>
  <div style={{display:"grid",gap:10,marginTop:16}}>{(data?.candidates||[]).map(c=><article key={c.id} style={{background:"white",border:"1px solid #cbd5e1",borderRadius:12,padding:14}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><b>{c.book?.title||"Mulig filduplikat"}</b><div style={{fontSize:12,color:"#64748b",marginTop:3}}>{c.storage_path||"—"} {c.book?.language?`· ${c.book.language}`:""}</div></div><b>{c.status.toUpperCase()}</b></div><div style={{marginTop:8,fontSize:12}}>Type: {c.candidate_type} · Treff: {c.match_type||"—"} · Konfidens: {c.confidence==null?"—":`${Math.round(c.confidence*100)}%`}</div>{c.candidate_type==="duplicate_file"&&<pre style={{whiteSpace:"pre-wrap",fontSize:11}}>{JSON.stringify(c.evidence,null,2)}</pre>}<div style={{display:"flex",gap:8,marginTop:10}}>{c.status==="pending"&&<><button onClick={()=>void act("approve",c.id)} disabled={busy!==null}>Godkjenn</button><button onClick={()=>void act("reject",c.id)} disabled={busy!==null}>Avvis</button></>}{c.status==="approved"&&c.candidate_type==="link_file"&&<button onClick={()=>void act("apply",c.id)} disabled={busy!==null}>Utfør kobling</button>}</div></article>)}</div>
 </div>;
}
