"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { Activity, AlertTriangle, ArrowRight, Clock3, Gauge, Loader2, PauseCircle, RefreshCw, Route, SlidersHorizontal, Sparkles, Target, TrendingUp, UserRoundSearch } from "lucide-react";

type Learning = { samples:number; hits:number; hitRate:number; avgHoursToTarget:number|null; outcomeWindowDays:number };
type NextMove = { action:string; reason:string; href:string; targetStage?:string|null; score?:number; priority?:string; cause?:string; causeLabel?:string; reactivationSegment?:string|null; reactivationScore?:number|null; learning?:Learning|null };
type Row = { id:string; name:string; email?:string|null; brand?:string|null; pipelineStatus:string; pipelineValue?:number; activityAt?:string|null; staleDays?:number|null; openWork:number; nextMove?:NextMove|null };
type HealthRun = { status:string; at:string } | null;
type Health = { emailHealthy:boolean; pendingInbound:number|null; lastIngest:HealthRun; lastAutoDraft:HealthRun; lastCrmSync:HealthRun; outcomeLearningStarted:boolean; movementRecommendations:number; pipelineTransitions:number; note:string };
type Payload = { generatedAt:string; movementVersion?:number; health?:Health; learning?:{ active:boolean; recommendationGroups:number; outcomeWindowDays:number; note?:string }; summary:{ activePipeline:number; inboundReplies24h:number; needsMovement:number; plannedWaiting:number; noActivity7d:number; openWork:number; unknownPipelineStatus:number; highPriorityMovement:number; dormantReactivation:number }; stages:Record<string,number>; causes:Record<string,number>; targetStages:Record<string,number>; stalled:Row[]; plannedWaiting:Row[]; recentlyMoved:Row[]; note?:string };

function timeLabel(value?:string|null){if(!value)return "aldri";const d=new Date(value);return Number.isNaN(d.getTime())?"ukjent":d.toLocaleString("nb-NO",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"});}

export default function PipelineDailyPage() {
  const [data,setData] = useState<Payload|null>(null);
  const [loading,setLoading] = useState(true);
  const [error,setError] = useState("");
  const load = useCallback(async()=>{
    setLoading(true); setError("");
    try {
      const response = await fetch("/api/nexus/pipeline-daily", { cache:"no-store", credentials:"same-origin" });
      const body = await response.json().catch(()=>({}));
      if (!response.ok) throw new Error(body?.error || "Kunne ikke lese pipeline");
      setData(body as Payload);
    } catch(e) { setError(e instanceof Error ? e.message : String(e)); }
    finally { setLoading(false); }
  },[]);
  useEffect(()=>{ void load(); },[load]);
  return <main className="mx-auto max-w-[1450px] space-y-6 p-4 sm:p-6">
    <header className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[0.2em] text-cyan-700"><Route size={16}/> Pipeline Movement Intelligence</div><h1 className="mt-2 text-3xl font-black text-slate-950">Bevegelse, stagnasjonsårsak og neste steg</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Kombinerer pipeline-status, planlagt venting, dormant reaktivering og CRM-prioritet. Målet er ikke flere aktiviteter, men å flytte riktig kunde til riktig neste steg.</p></div><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-black text-white disabled:opacity-60">{loading?<Loader2 size={16} className="mr-2 animate-spin"/>:<RefreshCw size={16} className="mr-2"/>}Oppdater</button></div>
    </header>
    {error && <div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-950"><AlertTriangle size={17} className="mr-2 inline"/>{error}</div>}
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">
      <Metric label="Aktiv pipeline" value={data?.summary.activePipeline ?? 0}/><Metric label="Svar 24t" value={data?.summary.inboundReplies24h ?? 0}/><Metric label="Trenger bevegelse" value={data?.summary.needsMovement ?? 0}/><Metric label="Høy prioritet" value={data?.summary.highPriorityMovement ?? 0}/><Metric label="Dormant reaktivering" value={data?.summary.dormantReactivation ?? 0}/><Metric label="Planlagt venting" value={data?.summary.plannedWaiting ?? 0}/><Metric label="Ingen aktivitet 7d" value={data?.summary.noActivity7d ?? 0}/><Metric label="Åpne oppgaver" value={data?.summary.openWork ?? 0}/>
    </section>
    {data?.health&&<section className={`rounded-2xl border p-5 ${data.health.emailHealthy&&Number(data.health.pendingInbound||0)===0?"border-emerald-200 bg-emerald-50":"border-amber-200 bg-amber-50"}`}><div className="flex items-center gap-2"><Activity size={18}/><h2 className="font-black text-slate-950">Pipeline Health</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><HealthMetric label="Email ingest" value={data.health.lastIngest?.status||"ukjent"} sub={timeLabel(data.health.lastIngest?.at)}/><HealthMetric label="Auto-draft" value={data.health.lastAutoDraft?.status||"ukjent"} sub={timeLabel(data.health.lastAutoDraft?.at)}/><HealthMetric label="CRM sync" value={data.health.lastCrmSync?.status||"ukjent"} sub={timeLabel(data.health.lastCrmSync?.at)}/><HealthMetric label="Pending inbound" value={data.health.pendingInbound==null?"?":String(data.health.pendingInbound)} sub={data.health.pendingInbound===0?"ingen kø":"venter på CRM"}/><HealthMetric label="Outcome Learning" value={data.health.outcomeLearningStarted?"aktiv":"venter"} sub={`${data.health.movementRecommendations} anbefalinger · ${data.health.pipelineTransitions} overganger`}/></div><p className="mt-3 text-xs text-slate-600">{data.health.note}</p></section>}
    <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><Gauge size={17}/><h2 className="font-black text-slate-950">Pipeline nå</h2></div><div className="flex flex-wrap gap-2">{Object.entries(data?.stages || {}).sort((a,b)=>b[1]-a[1]).map(([stage,count])=><span key={stage} className="rounded-full bg-slate-100 px-3 py-2 text-xs font-black text-slate-700">{stage} · {count}</span>)}</div></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><Target size={17}/><h2 className="font-black text-slate-950">Hvor Nexus prøver å flytte kundene</h2></div><div className="flex flex-wrap gap-2">{Object.entries(data?.targetStages || {}).filter(([stage])=>stage!=="NO_TARGET").sort((a,b)=>b[1]-a[1]).map(([stage,count])=><span key={stage} className="rounded-full bg-cyan-50 px-3 py-2 text-xs font-black text-cyan-800">→ {stage} · {count}</span>)}</div></div></section>
    {data?.learning?.active&&<section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-950"><TrendingUp size={16} className="mr-2 inline"/><b>Outcome Learning aktiv:</b> historisk effekt vises på anbefalinger når vi har målbare observasjoner. Dette påvirker ikke Movement Score ennå.</section>}
    <section className="grid gap-4 lg:grid-cols-2">
      <Link href="/nexus-os/stage-readiness" className="flex flex-col gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-950 transition hover:border-amber-300 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 font-black"><UserRoundSearch size={17}/> Stage Readiness</div><p className="mt-1 text-sm text-amber-900">Se nøyaktig hva som mangler for å flytte kunder fra QUALIFIED → MATCHING → VIEWING: buyer profile, kriterier, shortlist eller boligsignal.</p></div><span className="inline-flex shrink-0 items-center text-sm font-black">Åpne kø <ArrowRight size={14} className="ml-2"/></span></Link>
      <Link href="/nexus-os/rule-improvements" className="flex flex-col gap-3 rounded-2xl border border-cyan-200 bg-cyan-50 p-5 text-cyan-950 transition hover:border-cyan-300 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 font-black"><SlidersHorizontal size={17}/> Systemforbedringer</div><p className="mt-1 text-sm text-cyan-900">Se hvilke Movement-regler som er svake, trege, sterke eller fortsatt har for lite datagrunnlag. Ingen regler endres automatisk.</p></div><span className="inline-flex shrink-0 items-center text-sm font-black">Åpne forbedringskø <ArrowRight size={14} className="ml-2"/></span></Link>
    </section>
    <section className="space-y-3"><div><h2 className="text-xl font-black text-slate-950">Kontakt først</h2><p className="mt-1 text-sm text-slate-500">Sortert etter Movement Score og deretter pipeline-verdi. Planlagt venting er fjernet fra denne listen.</p></div>{(data?.stalled||[]).map(row=><article key={row.id} className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2 text-[10px] font-black uppercase tracking-wider text-slate-500"><span>{row.pipelineStatus}</span><span>·</span><span>{row.brand||"ukjent brand"}</span><span>·</span><span><Clock3 size={12} className="mr-1 inline"/>{row.staleDays ?? "–"} dager</span>{row.nextMove?.priority&&<span className="rounded-full bg-white px-2 py-1">{row.nextMove.priority}</span>}</div><div className="mt-2 flex flex-wrap items-center gap-2"><h3 className="font-black text-slate-950">{row.name}</h3>{typeof row.nextMove?.score==="number"&&<span className="rounded-full bg-slate-950 px-2.5 py-1 text-xs font-black text-white">Movement {row.nextMove.score}/100</span>}{row.nextMove?.causeLabel&&<span className="rounded-full bg-amber-100 px-2.5 py-1 text-xs font-black text-amber-900">{row.nextMove.causeLabel}</span>}</div><div className="mt-1 text-xs text-slate-500">{row.email}</div><div className="mt-3 rounded-xl border border-amber-200 bg-white p-3 text-sm text-amber-950"><Sparkles size={15} className="mr-2 inline"/><b>Neste handling:</b> {row.nextMove?.action}<div className="mt-1 text-xs text-slate-600">{row.nextMove?.reason}</div>{row.nextMove?.targetStage&&<div className="mt-2 text-xs font-black text-cyan-800">Mål: {row.pipelineStatus} → {row.nextMove.targetStage}</div>}{row.nextMove?.reactivationSegment&&<div className="mt-1 text-xs text-slate-600">Reaktivering: {row.nextMove.reactivationSegment} · score {row.nextMove.reactivationScore ?? "–"}</div>}{row.nextMove?.learning&&<div className="mt-3 rounded-lg bg-emerald-50 px-3 py-2 text-xs text-emerald-900"><TrendingUp size={13} className="mr-1 inline"/><b>Historisk effekt:</b> {row.nextMove.learning.hitRate}% nådde {row.nextMove.targetStage} innen {row.nextMove.learning.outcomeWindowDays} dager · {row.nextMove.learning.samples} observasjoner{row.nextMove.learning.avgHoursToTarget!=null?` · snitt ${row.nextMove.learning.avgHoursToTarget} t`:""}</div>}</div></div><Link href={row.nextMove?.href || `/customers?contactId=${encodeURIComponent(row.id)}`} className="inline-flex items-center rounded-xl bg-slate-950 px-3 py-2 text-sm font-black text-white">Åpne Customer 360 <ArrowRight size={14} className="ml-2"/></Link></div></article>)}{!loading && data && data.stalled.length===0 && <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 text-sm text-emerald-900">Ingen aktive saker trenger bevegelse akkurat nå.</div>}</section>
    {(data?.plannedWaiting?.length||0)>0&&<section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><PauseCircle size={17}/><h2 className="font-black text-slate-950">Planlagt venting</h2></div><p className="mt-1 text-sm text-slate-500">Disse skal ikke behandles som stagnasjon før avtalt ventetid utløper.</p><div className="mt-4 flex flex-wrap gap-2">{data?.plannedWaiting.slice(0,12).map(row=><Link key={row.id} href={row.nextMove?.href || `/customers?contactId=${encodeURIComponent(row.id)}`} className="rounded-xl bg-slate-100 px-3 py-2 text-xs font-bold text-slate-700">{row.name} · {row.nextMove?.reason}</Link>)}</div></section>}
    {data?.note && <div className="text-xs text-slate-500">{data.note}</div>}
  </main>;
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="text-2xl font-black text-slate-950">{value}</div><div className="text-xs font-semibold text-slate-500">{label}</div></div>}
function HealthMetric({label,value,sub}:{label:string;value:string;sub:string}){return <div className="rounded-xl bg-white p-3 shadow-sm"><div className="text-xs font-semibold text-slate-500">{label}</div><div className="mt-1 text-lg font-black text-slate-950">{value}</div><div className="mt-1 text-[11px] text-slate-500">{sub}</div></div>}
