-- Ensure owned Growth OS brands have the Brand Brain required by the
-- controlled Meta pilot path. Existing rows are updated conservatively.

insert into public.brand_context (
  brand_id,
  brand_name,
  voice,
  audience,
  languages,
  markets,
  services,
  value_proposition,
  allowed_claims,
  forbidden_claims,
  preferred_cta,
  visual_direction,
  urls,
  contact,
  updated_at
)
values
  (
    'freddyb',
    'Freddy Bremseth',
    'Professional, analytical, practical and personal without sounding private.',
    'Readers, buyers, founders and followers who want clear advice about property, business, AI and books.',
    '["no","en"]'::jsonb,
    '["Spain","Norway","Costa Blanca","online"]'::jsonb,
    '["property advisory","books","business analysis","AI and automation"]'::jsonb,
    'A professional umbrella brand that connects Freddy Bremseth''s advisory work, writing and practical business building.',
    '["Can discuss verified projects, books, property advisory, AI workflows and business experience.","Can amplify owned brand stories when rewritten from a personal expertise angle."]'::jsonb,
    '["Do not present the private Facebook profile as an automated commercial channel.","Do not invent sales results, book reviews, client outcomes or product capabilities."]'::jsonb,
    'Read more or contact Freddy',
    'Clean professional visuals with books, Spain, property, business tools and AI product screenshots when verified.',
    '["https://freddybremseth.com"]'::jsonb,
    '{"email":"freddy@zenecohomes.com"}'::jsonb,
    now()
  ),
  (
    'freddypublishing',
    'Freddy Publishing',
    'Clear, reader-focused and catalog-oriented. Practical, intelligent and direct.',
    'Readers interested in nonfiction, thrillers, history, travel, property and practical learning series.',
    '["en","no","es"]'::jsonb,
    '["online","Amazon","Apple Books"]'::jsonb,
    '["book catalog","book launches","sample chapters","series pages"]'::jsonb,
    'A dedicated publishing brand for Freddy Bremseth books, series, samples and launch communication.',
    '["Can promote verified book titles, series, covers, descriptions, sample chapters and catalog pages.","Can invite readers to browse the catalog or read a sample."]'::jsonb,
    '["Do not invent reviews, rankings, awards, sales numbers or reader testimonials.","Do not quote unpublished book text unless the source is explicitly provided."]'::jsonb,
    'Read a sample',
    'Book covers, clean catalog layouts, series identity and readable excerpt cards.',
    '["https://books.freddybremseth.com"]'::jsonb,
    '{"email":"post@chatgenius.pro"}'::jsonb,
    now()
  ),
  (
    'freddyai',
    'Freddy AI Products',
    'Concrete, useful and product-led. Explain automation in plain language with honest limits.',
    'Small businesses, real estate operators, creators and founders who need practical AI systems.',
    '["no","en"]'::jsonb,
    '["Spain","Norway","online"]'::jsonb,
    '["RealtyFlow","Nexus OS","AI automation","product demos","business workflows"]'::jsonb,
    'Practical AI products and workflows that help businesses organize leads, content, operations and growth.',
    '["Can discuss verified RealtyFlow, Nexus OS and AI workflow capabilities.","Can show product demos, build-in-public updates and practical automation examples when sourced."]'::jsonb,
    '["Do not invent integrations, prices, customer numbers, revenue results or guaranteed outcomes.","Do not claim autonomous publishing on a channel unless the channel is connected and approved."]'::jsonb,
    'See the demo',
    'Product screenshots, workflow diagrams, clean UI crops and concise demo clips.',
    '["https://freddybremseth.com","https://realtyflow.chatgenius.pro"]'::jsonb,
    '{"email":"post@chatgenius.pro"}'::jsonb,
    now()
  ),
  (
    'remasterfreddy',
    'Re-Master Freddy',
    'Creative, energetic and music-focused while staying honest about source material and rights.',
    'YouTube listeners and social followers interested in original or authorized AI music and remaster-style releases.',
    '["en","no"]'::jsonb,
    '["YouTube","online"]'::jsonb,
    '["songs","music videos","playlists","short-form music promotion"]'::jsonb,
    'A creator/media brand for Re-Master Freddy songs, videos, playlists and music discovery.',
    '["Can promote verified songs, YouTube URLs, playlists, artwork and channel subscription CTAs.","Can use existing song metadata from the shared Re-Master source catalog."]'::jsonb,
    '["Do not imply ownership or licensing of third-party media without explicit proof.","Do not invent streaming numbers, chart positions, reviews or collaborations."]'::jsonb,
    'Watch on YouTube',
    'Music artwork, video stills, playlist visuals and short performance-style clips.',
    '["https://freddybremseth.com","https://remaster.freddybremseth.com"]'::jsonb,
    '{"email":"freddy@chatgenius.pro"}'::jsonb,
    now()
  )
on conflict (brand_id) do update set
  brand_name = excluded.brand_name,
  voice = excluded.voice,
  audience = excluded.audience,
  languages = excluded.languages,
  markets = excluded.markets,
  services = excluded.services,
  value_proposition = excluded.value_proposition,
  allowed_claims = excluded.allowed_claims,
  forbidden_claims = excluded.forbidden_claims,
  preferred_cta = excluded.preferred_cta,
  visual_direction = excluded.visual_direction,
  urls = excluded.urls,
  contact = excluded.contact,
  updated_at = now();
