create table if not exists public.remaster_playlist_recovery_audit (
  id bigint generated by default as identity primary key,
  job_id uuid not null,
  youtube_video_id text not null,
  playlist_name text not null,
  playlist_id text,
  playlist_created boolean,
  duplicate boolean,
  ok boolean not null,
  error_message text,
  checked_at timestamptz not null default now()
);

create index if not exists remaster_playlist_recovery_audit_job_checked_idx
  on public.remaster_playlist_recovery_audit (job_id, checked_at desc);

alter table public.remaster_playlist_recovery_audit enable row level security;

revoke all on public.remaster_playlist_recovery_audit from anon, authenticated;
grant all on public.remaster_playlist_recovery_audit to service_role;
