-- Keep ChatGenius/Olivia app links visible in SaaS Hub and Business Overview.
-- These rows are safe to re-run because slug is unique and used as conflict key.

INSERT INTO saas_apps (
  slug,
  name,
  domain,
  description,
  category,
  tech_stack,
  status,
  color,
  pricing_model,
  price_monthly,
  currency,
  repo_url,
  live_url,
  dev_platform,
  launched_at,
  updated_at
) VALUES
  (
    'chatgenius',
    'ChatGenius.pro',
    'chatgenius.pro',
    'Main platform and brand hub for AI agents, automations and SaaS products.',
    'ai-chat',
    ARRAY['next.js', 'supabase', 'openai', 'vercel'],
    'live',
    '#8b5cf6',
    'subscription',
    NULL,
    'USD',
    'https://github.com/freddybremseth-coder/ChatGenius-App',
    'https://chatgenius.pro',
    'codex',
    NOW(),
    NOW()
  ),
  (
    'olivia',
    'Olivia AI',
    'olivia.chatgenius.pro',
    'AI assistant connected to productivity and Olivia/Dona Anna workflows.',
    'ai-chat',
    ARRAY['next.js', 'supabase', 'ai'],
    'live',
    '#ec4899',
    'freemium',
    14.99,
    'USD',
    'https://github.com/freddybremseth-coder/olivia',
    'https://olivia.chatgenius.pro',
    'codex',
    NOW(),
    NOW()
  ),
  (
    'realtyflow',
    'RealtyFlow Pro',
    'realtyflow.chatgenius.pro',
    'AI real estate, publishing and brand operating system for Spain-focused businesses.',
    'real-estate',
    ARRAY['next.js', 'supabase', 'vercel', 'openai'],
    'live',
    '#06b6d4',
    'subscription',
    29.99,
    'USD',
    'https://github.com/freddybremseth-coder/realtyflow-pro',
    'https://realtyflow.chatgenius.pro',
    'codex',
    NOW(),
    NOW()
  ),
  (
    'donaanna',
    'Dona Anna',
    'donaanna.com',
    'Olive oil, farm story and Mediterranean product brand connected to Olivia farm data.',
    'ecommerce',
    ARRAY['next.js', 'supabase', 'content-commerce'],
    'live',
    '#f59e0b',
    'one-time',
    NULL,
    'EUR',
    'https://github.com/freddybremseth-coder/donaanna',
    'https://donaanna.com',
    'codex',
    NOW(),
    NOW()
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  domain = EXCLUDED.domain,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  tech_stack = EXCLUDED.tech_stack,
  status = EXCLUDED.status,
  color = EXCLUDED.color,
  pricing_model = EXCLUDED.pricing_model,
  price_monthly = EXCLUDED.price_monthly,
  currency = EXCLUDED.currency,
  repo_url = EXCLUDED.repo_url,
  live_url = EXCLUDED.live_url,
  dev_platform = EXCLUDED.dev_platform,
  updated_at = NOW();
