export type SeedPublishingBook = {
  id: string;
  brand_id: string;
  title: string;
  subtitle: string;
  asin: string;
  format: string;
  marketplace: string;
  amazon_url: string;
  niche: string;
  series_name: string;
  role: string;
  status: string;
  price: number | null;
  currency: string;
  reviews_count: number;
  average_rating: number | null;
  best_sellers_rank: number | null;
  main_category: string;
  keywords: string[];
  ad_spend: number;
  clicks: number;
  orders: number;
  royalties: number;
  acos: number | null;
  next_action: string;
  priority: number;
  notes: string;
  synthetic: boolean;
};

const amazonSearch = (query: string) => `https://www.amazon.com/s?k=${encodeURIComponent(query)}`;

const baseBook = {
  brand_id: "freddypublishing",
  marketplace: "amazon.com",
  currency: "USD",
  reviews_count: 0,
  average_rating: null,
  best_sellers_rank: null,
  ad_spend: 0,
  clicks: 0,
  orders: 0,
  royalties: 0,
  acos: null,
  synthetic: true,
};

export const seedBooks: SeedPublishingBook[] = [
  {
    ...baseBook,
    id: "seed-olive-oil-cure",
    title: "The Olive Oil Cure",
    subtitle: "A Mediterranean Guide to Extra Virgin Olive Oil, Polyphenols, Anti-Inflammatory Eating, Heart Health and Longevity",
    asin: "B0DKFTY16L",
    format: "kindle",
    amazon_url: amazonSearch("Freddy Bremseth The Olive Oil Cure"),
    niche: "olive_oil_mediterranean",
    series_name: "Mediterraneo Vital",
    role: "front_product",
    status: "optimize",
    price: 2.99,
    main_category: "Health, Fitness & Dieting > Nutrition",
    keywords: ["extra virgin olive oil guide", "mediterranean diet", "polyphenols", "heart healthy eating", "olive oil benefits"],
    next_action: "Oppdater metadata, tryggere sales copy, kategorier og cover før Ads-test.",
    priority: 98,
    notes: "Front product. Goodreads viser en utgave med 1 rating; Google Books viser 81 sider og Cooking/Health-nisje.",
  },
  {
    ...baseBook,
    id: "seed-premium-olive-oil",
    title: "Premium Olive Oil",
    subtitle: "The Complete Expert's Guide: Mastering Olive Varieties, Soil, and Processing for High-Quality Oil",
    asin: "",
    format: "paperback",
    amazon_url: amazonSearch("Freddy Bremseth Premium Olive Oil"),
    niche: "olive_oil_mediterranean",
    series_name: "Mediterraneo Vital",
    role: "support",
    status: "optimize",
    price: 19.99,
    main_category: "Business & Money > Industries > Agriculture",
    keywords: ["olive oil production", "olive farming guide", "extra virgin olive oil", "olive grove management", "sustainable agriculture"],
    next_action: "Skille tydelig fra consumer-boken: grower/producer/fagbok, ikke helsebok.",
    priority: 82,
    notes: "Fagbok og autoritetsprodukt for dyrkere/produsenter.",
  },
  {
    ...baseBook,
    id: "seed-polyfenolens-kraft",
    title: "Polyfenolens kraft",
    subtitle: "Naturlige antioksidanter i olivenolje",
    asin: "",
    format: "kindle",
    amazon_url: amazonSearch("Freddy Bremseth Polyfenolens kraft"),
    niche: "olive_oil_mediterranean",
    series_name: "Mediterraneo Vital",
    role: "support",
    status: "optimize",
    price: null,
    main_category: "Health, Fitness & Dieting > Nutrition",
    keywords: ["polyfenoler", "olivenolje helse", "antioksidanter", "middelhavskost", "extra virgin olive oil"],
    next_action: "Bruk som dybdebok som peker til The Olive Oil Cure og Doña Anna lead magnet.",
    priority: 78,
    notes: "Norsk supportbok i Mediterraneo Vital-serien.",
  },
  {
    ...baseBook,
    id: "seed-lev-til-100",
    title: "Lev til du er 100 år",
    subtitle: "Hemmeligheter fra Middelhavsregionen for et langt, vitalt og meningsfullt liv",
    asin: "",
    format: "kindle",
    amazon_url: amazonSearch("Freddy Bremseth Lev til du er 100 år"),
    niche: "olive_oil_mediterranean",
    series_name: "Mediterraneo Vital",
    role: "support",
    status: "optimize",
    price: null,
    main_category: "Health, Fitness & Dieting > Healthy Living",
    keywords: ["leve lengre", "longevity", "middelhavsliv", "sunn aldring", "middelhavskost"],
    next_action: "Koble tydeligere til longevity, middelhavsmat og olivenolje i beskrivelse og interne lenker.",
    priority: 76,
    notes: "Sterk brand-bok for Middelhavsliv og personlig historie.",
  },
  {
    ...baseBook,
    id: "seed-fra-jord-til-bord",
    title: "Fra jord til bord",
    subtitle: "En Reise i Regenerativt Jordbruk og Sunn Olivenolje",
    asin: "",
    format: "kindle",
    amazon_url: amazonSearch("Freddy Bremseth Fra jord til bord"),
    niche: "olive_oil_mediterranean",
    series_name: "Mediterraneo Vital",
    role: "support",
    status: "optimize",
    price: null,
    main_category: "Business & Money > Industries > Agriculture",
    keywords: ["regenerativt jordbruk", "olivenolje", "bærekraftig landbruk", "jord til bord", "sustainable living"],
    next_action: "Bruk som autoritetsbok for Doña Anna, gårdshistorie og bærekraftig produksjon.",
    priority: 74,
    notes: "Medforfatter Anna Bremseth. God kobling til produkt- og merkevarehistorie.",
  },
  {
    ...baseBook,
    id: "seed-kunsten-a-hoste-tidlig",
    title: "Kunsten å høste tidlig",
    subtitle: "Vår reise mot den ultimate olivenoljen i Biar",
    asin: "",
    format: "kindle",
    amazon_url: amazonSearch("Freddy Bremseth Kunsten å høste tidlig"),
    niche: "olive_oil_mediterranean",
    series_name: "Mediterraneo Vital",
    role: "support",
    status: "optimize",
    price: null,
    main_category: "Cookbooks, Food & Wine > Reference",
    keywords: ["tidlig høsting", "olivenolje", "Biar Alicante", "premium olivenolje", "polyfenoler"],
    next_action: "Gjør tittelen mer søkbar i undertittel og bruk den som storytelling rundt kvalitet.",
    priority: 72,
    notes: "Medforfatter Anna Bremseth. Tett kobling til Doña Anna og Biar.",
  },
  {
    ...baseBook,
    id: "seed-birokt-og-oliven",
    title: "Birøkt og oliven i hjertet av Alicante",
    subtitle: "Økologisk og regenerativ drift i Biar",
    asin: "",
    format: "kindle",
    amazon_url: amazonSearch("Freddy Bremseth Birøkt og oliven i hjertet av Alicante"),
    niche: "olive_oil_mediterranean",
    series_name: "Mediterraneo Vital",
    role: "support",
    status: "optimize",
    price: null,
    main_category: "Crafts, Hobbies & Home > Gardening & Landscape Design",
    keywords: ["birøkt", "oliven", "Alicante", "regenerativ drift", "økologisk landbruk"],
    next_action: "Posisjoner som nisje/autoritet, ikke annonser bredt før hovedboken selger.",
    priority: 66,
    notes: "Nisjebok som styrker gårdsuniverset.",
  },
  {
    ...baseBook,
    id: "seed-spania-2030",
    title: "Spania 2030",
    subtitle: "Alt du må vite om energikrav og smarte boligkjøp",
    asin: "",
    format: "kindle",
    amazon_url: amazonSearch("Freddy Bremseth Spania 2030"),
    niche: "spain_property_advisory",
    series_name: "Let me Guide you",
    role: "authority_book",
    status: "optimize",
    price: null,
    main_category: "Business & Money > Real Estate",
    keywords: ["kjøpe bolig i Spania", "energikrav Spania", "Costa Blanca bolig", "Spania eiendom", "boligkjøp guide"],
    next_action: "Bruk som lead-generering til rådgivning og eiendomskunder, ikke som primær royalty-bok.",
    priority: 86,
    notes: "Authority book for RealtyFlow/Zen Eco Homes rådgivningsrollen.",
  },
  {
    ...baseBook,
    id: "seed-skatt-og-staten",
    title: "Let me Explain you: Skatt og Staten",
    subtitle: "Hvordan økonomien virkelig fungerer - og hvorfor den ikke gjør det",
    asin: "",
    format: "kindle",
    amazon_url: amazonSearch("Freddy Bremseth Skatt og Staten"),
    niche: "economics_society",
    series_name: "Let me Explain you",
    role: "secondary",
    status: "parked",
    price: null,
    main_category: "Business & Money > Economics",
    keywords: ["skatt", "staten", "økonomi", "samfunnsøkonomi", "politisk økonomi"],
    next_action: "Parker kommersielt til hovedplattformen har mer trafikk. Vurder egen norsk publikumskampanje senere.",
    priority: 42,
    notes: "Utenfor hovednisjen. Behold oversikt, men ikke prioriter nå.",
  },
  {
    ...baseBook,
    id: "seed-declutter-digital-life",
    title: "Declutter Your Digital Life",
    subtitle: "Reclaim Your Focus, Reduce Stress, and Master Your Tech with Simple Steps",
    asin: "",
    format: "kindle",
    amazon_url: amazonSearch("Freddy Bremseth Declutter Your Digital Life"),
    niche: "balanced_life",
    series_name: "The Balanced Life Series",
    role: "secondary",
    status: "audit",
    price: null,
    main_category: "Self-Help > Time Management",
    keywords: ["digital declutter", "focus", "reduce stress", "productivity", "technology habits"],
    next_action: "Vurder om Balanced Life skal bli egen penn/brand, ellers hold den sekundær.",
    priority: 54,
    notes: "Konkurranseutsatt self-help-nisje.",
  },
  {
    ...baseBook,
    id: "seed-time-mastery-long",
    title: "Time Mastery for High Achievers",
    subtitle: "A Practical Guide to Reclaiming Productivity and Balance",
    asin: "",
    format: "kindle",
    amazon_url: amazonSearch("Freddy Bremseth Time Mastery for High Achievers"),
    niche: "balanced_life",
    series_name: "The Balanced Life Series",
    role: "secondary",
    status: "audit",
    price: null,
    main_category: "Self-Help > Time Management",
    keywords: ["time mastery", "productivity", "high achievers", "work life balance", "focus"],
    next_action: "Sjekk om denne og den korte Time Mastery-utgaven bør slås sammen som editions.",
    priority: 52,
    notes: "Mulig duplikat/edition i Goodreads-listen.",
  },
  {
    ...baseBook,
    id: "seed-time-mastery-short",
    title: "Time Mastery for High Achievers",
    subtitle: "Practical Guide to Reclaiming Productivity and Balance",
    asin: "",
    format: "kindle",
    amazon_url: amazonSearch("Freddy Bremseth Time Mastery High Achievers Practical Guide"),
    niche: "balanced_life",
    series_name: "The Balanced Life Series",
    role: "secondary",
    status: "parked",
    price: null,
    main_category: "Self-Help > Time Management",
    keywords: ["time management", "productivity guide", "high achievers", "balance", "focus"],
    next_action: "Avklar om dette er egen bok eller duplikat-utgave før annonsering.",
    priority: 38,
    notes: "Mulig duplikat/edition. Bør ryddes i Amazon/Goodreads hvis det forvirrer.",
  },
  {
    ...baseBook,
    id: "seed-relationship-blueprint",
    title: "The Relationship Blueprint",
    subtitle: "Mastering Communication, Deepening Trust, and Creating Lasting Intimacy",
    asin: "",
    format: "kindle",
    amazon_url: amazonSearch("Freddy Bremseth The Relationship Blueprint"),
    niche: "balanced_life",
    series_name: "The Balanced Life Series",
    role: "secondary",
    status: "audit",
    price: null,
    main_category: "Self-Help > Relationships",
    keywords: ["relationship communication", "trust", "intimacy", "couples guide", "relationship blueprint"],
    next_action: "Ikke prioriter Ads før Balanced Life har en egen tydelig forfatterplattform.",
    priority: 48,
    notes: "Stor nisje, men svært konkurranseutsatt.",
  },
  {
    ...baseBook,
    id: "seed-mindful-balance",
    title: "Mindful Balance",
    subtitle: "Conquer Stress While Thriving in Motherhood & Career",
    asin: "",
    format: "kindle",
    amazon_url: amazonSearch("Freddy Bremseth Mindful Balance Motherhood Career"),
    niche: "balanced_life",
    series_name: "The Balanced Life Series",
    role: "secondary",
    status: "audit",
    price: null,
    main_category: "Self-Help > Stress Management",
    keywords: ["busy moms", "stress management", "motherhood career", "mindful balance", "productivity"],
    next_action: "Krev skarpere målgruppe/credibility før aktiv kampanje.",
    priority: 46,
    notes: "Målgruppen er klar, men trenger sterkere autoritetsgrunnlag.",
  },
  {
    ...baseBook,
    id: "seed-joy-code-book-1",
    title: "The Joy Code",
    subtitle: "Exploring Happiness: Science, Spirituality, and Personal Growth",
    asin: "",
    format: "kindle",
    amazon_url: amazonSearch("Freddy Bremseth The Joy Code Book 1"),
    niche: "personal_development",
    series_name: "Personal Development",
    role: "secondary",
    status: "audit",
    price: null,
    main_category: "Self-Help > Happiness",
    keywords: ["happiness", "personal growth", "spirituality", "joy", "science of happiness"],
    next_action: "Vurder ny posisjonering eller parker. Happiness er for bredt uten en sterk unik vinkel.",
    priority: 44,
    notes: "Book 1 i Goodreads-listen.",
  },
  {
    ...baseBook,
    id: "seed-joy-code-book-2",
    title: "The Joy Code",
    subtitle: "Exploring Happiness: Science, Spirituality, and Personal Growth",
    asin: "",
    format: "kindle",
    amazon_url: amazonSearch("Freddy Bremseth The Joy Code Book 2"),
    niche: "personal_development",
    series_name: "Personal Development",
    role: "secondary",
    status: "parked",
    price: null,
    main_category: "Self-Help > Happiness",
    keywords: ["joy code", "happiness", "personal development", "spiritual growth", "wellbeing"],
    next_action: "Avklar om Book 1 og Book 2 er reelle separate bøker eller edition-duplikater.",
    priority: 36,
    notes: "Book 2 i Goodreads-listen. Kan skape forvirring hvis ikke tydelig differensiert.",
  },
  {
    ...baseBook,
    id: "seed-olive-oil-cure-duplicate-edition",
    title: "The Olive Oil Cure",
    subtitle: "Unlocking the Health Secrets of Nature's Superfood",
    asin: "",
    format: "kindle",
    amazon_url: amazonSearch("Freddy Bremseth The Olive Oil Cure Unlocking the Health Secrets"),
    niche: "olive_oil_mediterranean",
    series_name: "Mediterraneo Vital",
    role: "parked",
    status: "parked",
    price: null,
    main_category: "Cooking > Health & Healing",
    keywords: ["olive oil", "superfood", "health", "mediterranean diet", "extra virgin olive oil"],
    next_action: "Sjekk om dette er duplikat edition. Slå sammen editions/anmeldelser hvis riktig.",
    priority: 34,
    notes: "Goodreads viser en ekstra Olive Oil Cure-utgave. Ikke annonser før edition-status er avklart.",
  },
  {
    ...baseBook,
    id: "seed-mediterranean-cookbook-next-launch",
    title: "The Mediterranean Olive Oil Cookbook for Beginners",
    subtitle: "100 Simple Anti-Inflammatory Recipes, 14-Day Meal Plan and Extra Virgin Olive Oil Guide for Heart-Healthy Everyday Living",
    asin: "",
    format: "kindle",
    amazon_url: "",
    niche: "olive_oil_mediterranean",
    series_name: "Mediterraneo Vital",
    role: "next_launch",
    status: "launch",
    price: null,
    main_category: "Cookbooks, Food & Wine > Special Diet > Heart Healthy",
    keywords: ["mediterranean olive oil cookbook", "anti inflammatory recipes", "14 day meal plan", "heart healthy cookbook", "mediterranean diet for beginners"],
    next_action: "Lag konkurrentanalyse, disposisjon, oppskriftspakke og lanseringsplan. Dette er mest kommersielle neste bok.",
    priority: 92,
    notes: "Planlagt salgsprodukt, ikke verifisert som eksisterende Goodreads/Amazon-tittel.",
  },
];
